Neuer Blogartikel: adesso goes Discord
adessoSE/devblog pull request #224
Opened 2022-01-19 09:59 UTC by Bolsei

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [X] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [X] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [X] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [X] "title" vergeben
    - [X] "author_ids" angegeben
    - [X] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [X] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [X] Rechtschreibung korrigiert
  - [X] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [X] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [X] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-01-26 17:10 UTC, jo2 requested changes
Der Artikel ist recht interessant, ein paar Sachen habe ich noch angemerkt. Außerdem ist der Artikel im Großteil im Passiv geschrieben, um die Leser besser mit einzubeziehen, wäre es schöner wenn du im Aktiv schreibst (bspw. "wir machen" statt "es wird gemacht"). Meiner Meinung nach können wir das für diesen Artikel aber auch so lassen, und du siehst es als Hinweis für zukünftige Artikel. @acetous was meinst du dazu?

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Zum Starten des Bots muss jetzt nur noch der SharedManager über die build() Methode erzeugt werden.
```suggestion
Zum Starten des Bots muss jetzt nur noch der SharedManager über die `build()`-Methode erzeugt werden.
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> + gesetzt werden.
```suggestion
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Damit der Bot nach dem Starten auch schon ein kleines Lebenszeichen von sich gibt, kann die Aktivität über die Zeile:
```suggestion
Damit der Bot nach dem Starten auch schon ein kleines Lebenszeichen von sich gibt, kann die Aktivität über folgende Zeile gesetzt werden:
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Die komplette Klasse mit der main-Methode sieht am Ende so aus
```suggestion
Die komplette Klasse mit der `main()`-Methode sieht am Ende so aus:
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Am einfachsten ist es einen eigenen Server für solche Tests anzulegen.
```suggestion
Am einfachsten ist es, einen eigenen Server für solche Tests anzulegen.
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Über die Discord App lässt sich dieser ganz einfach über das Plus auf der linken Seite erledigen.
```suggestion
Über die Discord-App lässt sich dies ganz einfach über das Plus auf der linken Seite erledigen.
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Um den programmierten Bot einem Server zu zuweisen, gibt man folgende URL in den Browser ein:
```suggestion
Um den programmierten Bot einem Server zuzuweisen, gibt man folgende URL in den Browser ein:
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Auf der [Applikations-Seite](https://discord.com/developers/applications) gibt es nach dem Auswählen des Bots unter dem Reiter Bot ein Tool um sich den Permission Integer in Abhängigkeit der Rechte z
```suggestion
Auf der [Applikationsseite](https://discord.com/developers/applications) gibt es nach dem Auswählen des Bots unter dem Reiter Bot ein Tool, um den Permission Integer abhängig von den benötigten Rechten zu ermitteln.
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Die client_id ist eine eindeutige Application Id von unserer Discord Applikation. Diese findet man unter dem Reiter General Information.
```suggestion
Die `client_id` ist eine eindeutige Application Id von unserer Discord-Applikation. Diese findet man unter dem Reiter "General Information".
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Nachdem Aufruf der URL muss nur noch bestätigt werden, dass der Bot dem Server beitreten darf.
```suggestion
Nach dem Aufruf der URL muss nur noch bestätigt werden, dass der Bot dem Server beitreten darf.
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Wenn nun die Applikation gestartet wird, autorisiert sich der Bot mit dem Token, der dem SharedManager übergeben wurde am Discord System.
```suggestion
Wenn nun die Applikation gestartet wird, autorisiert sich der Bot mit dem Token, der dem SharedManager übergeben wurde, am Discord-System.
```

2022-01-26 17:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +https://discord.com/oauth2/authorize?client_id=unsereClientId&scope=bot&permissions=8
```suggestion
[https://discord.com/oauth2/authorize?client_id=unsereClientId&scope=bot&permissions=8](https://discord.com/oauth2/authorize?client_id=unsereClientId&scope=bot&permissions=8)
```

2022-01-26 17:10 UTC, jo2 commented on _data/authors.yml
> +  github_username: Bolsei
```suggestion
  github_username: bolsei
```

2022-02-07 10:49 UTC, jo2 requested changes
Der Artikel liest sich sehr gut, vor allem durch die direkte Anrede. Ein paar Kleinigkeiten habe ich noch angemerkt. Die Ergänzung des Tests finde ich gut!

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Und natürlich zeige ich euch auch welche weiteren Schritte nötig sind.
```suggestion
Und natürlich zeige ich euch auch, welche weiteren Schritte nötig sind. 
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Zur Erstellung und Programmieren, benötigen wir folgende Dinge:
```suggestion
Zur Erstellung und Programmieren benötigen wir folgende Dinge:
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Bevor wir mit der Implementierung beginnen können müssen wir ein Maven Projekt anlegen.
```suggestion
Bevor wir mit der Implementierung beginnen können müssen wir ein Maven-Projekt anlegen.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Da sich die Discord API nicht im Maven-Repository befindet, müssen wir das Discord-Repository in die `pom.xml` aufnehmen:
```suggestion
Da sich die Discord API nicht im zentralen Maven-Repository befindet, müssen wir das Discord-Repository in die `pom.xml` aufnehmen:
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Zum Starten des Botes müssen wir jetzt nur noch den ShardManager über die `build()`-Methode erzeugen lassen.
```suggestion
Zum Starten des Bots müssen wir jetzt nur noch den ShardManager über die `build()`-Methode erzeugen lassen.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Um unsere Applikation jetzt noch starten zu können benötigt unsere Klasse `BotStartUp.java` nun noch eine `main()`-Methode.
```suggestion
Um unsere Applikation jetzt noch starten zu können, benötigt unsere Klasse `BotStartUp.java` nur noch eine `main()`-Methode.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Damit wir unseren Bot am Ende auch testen können, benötigen wir einen Server, auf dem wir die Rechte haben einen Bot hinzuzufügen.
```suggestion
Damit wir unseren Bot am Ende auch testen können, benötigen wir einen Server, auf dem wir die Rechte haben, einen Bot hinzuzufügen.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Die `client_id` ist eine Eindeutige Application Id von unserer Discord-Applikation.
```suggestion
Die `client_id` ist eine eindeutige Application Id von unserer Discord-Applikation.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Mit einem Permission Integer wird angegeben welche Rechte unser Bot auf dem Server besitzt.
```suggestion
Mit einem Permission Integer wird angegeben, welche Rechte unser Bot auf dem Server besitzt.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Natürlich ist es schön, zu sehen das der Bot auf unserem Discord Server Solitäre spielt.
```suggestion
Natürlich ist es schön, zu sehen, dass der Bot auf unserem Discord-Server Solitäre spielt.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Durch unseren erstellen Server können wir für diesen Test einfach das JUnit Framework nutzen.
```suggestion
Durch unseren erstellen Server können wir für diesen Test einfach das JUnit-Framework nutzen.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Da beide APIs nicht zum Java Standard gehören, müssen wir als erstes die Abhängigkeiten in unserer `pom.xml` aufnehmen.
```suggestion
Da beide APIs nicht zum Java-Standard gehören, müssen wir als erstes die Abhängigkeiten in unsere `pom.xml` aufnehmen.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Der Name der Methode ist für die Ausführung des Tests nicht relevant, wir sollten Trotzdem einen sprechenden Namen wählen.
```suggestion
Der Name der Methode ist für die Ausführung des Tests nicht relevant, wir sollten trotzdem einen sprechenden Namen wählen.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Für den Anfang haben wir nur einen Shard, dass heißt über ein `get(0)` bekommen wir unser `JDA`-Objekete mit dem wir unsere Tests durchführen können.
```suggestion
Für den Anfang haben wir nur einen Shard, dass heißt über ein `get(0)` bekommen wir unser `JDA`-Objekt mit dem wir unsere Tests durchführen können.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Als erstes wollen wir wissen ob unser Bot auch online ist, wenn die Methode `startBot` aufgerufen wurde.
```suggestion
Als erstes wollen wir wissen, ob unser Bot auch online ist, wenn die Methode `startBot()` aufgerufen wurde.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Für diesen Test brauchen wir den Status, von unserem Shard, den wir über die Methode `getStatus()` bekommen.
```suggestion
Für diesen Test brauchen wir den Status von unserem Shard, den wir über die Methode `getStatus()` bekommen.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Der Status wird über ein eigenes `enum` dargestellt und wir wollen prüfen ob unser Shard den Status `CONNECTED` hat.
```suggestion
Der Status wird über ein eigenes `enum` dargestellt und wir wollen prüfen, ob unser Shard den Status `CONNECTED` hat.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Dafür nutzen wir das vorher eingebunden Framework assertj um folgenden Code zu schreiben:
```suggestion
Dafür nutzen wir das vorher eingebunden Framework assertj, um folgenden Code zu schreiben:
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Die Aktivität selber wird in einem `Presence`-Objekete gespeichert, wir müssen also von unserem Shard ein `Presence`-Objekete bekommen.
```suggestion
Die Aktivität selber wird in einem `Presence`-Objekete gespeichert, wir müssen also von unserem Shard ein `Presence`-Objekt bekommen.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Nach dem wir nun das `Presence`-Objekete haben können wir uns die Aktivität holen und prüfen, ob sie unseren Erwartungen entspricht.
```suggestion
Nachdem wir nun das `Presence`-Objekt haben, können wir uns die Aktivität holen und prüfen, ob sie unseren Erwartungen entspricht.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Vom `SharedManager` können wir uns über die `getShards()`-Methode alle Shards zurückgeben lassen, die durch `JDA`-Objekete dargestellt werden.
```suggestion
Vom `SharedManager` können wir uns über die `getShards()`-Methode alle Shards zurückgeben lassen, die durch `JDA`-Objekt dargestellt werden.
```

2022-02-07 10:49 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Die neuste Version von JUnit ermöglicht es uns alle unsere Prüfungen auszuführen ohne, dass der Test abbricht so bald eine Prüfung nicht Erfolgreich ist.
```suggestion
Die neuste Version von JUnit ermöglicht es uns, alle unsere Prüfungen auszuführen, ohne dass der Test abbricht sobald eine Prüfung nicht erfolgreich ist.
```

2022-02-14 17:38 UTC, Bolsei commented on _posts/2022-01-05-adesso-goes-discord.md
> +Vom `SharedManager` können wir uns über die `getShards()`-Methode alle Shards zurückgeben lassen, die durch `JDA`-Objekete dargestellt werden.
Hier würde ich es bei Objekte belassen, da es sich ja auf die Shards bezieht, die alle durch JDA-Objekte dargestellt werden und nicht nur durch ein einzelnes JDA-Objekt.

2022-02-17 09:10 UTC, jo2 requested changes
Drei Kleinigkeiten sind noch drin, danach ist der Artikel mMn. fertig.

2022-02-17 09:10 UTC, jo2 commented on _posts/2022-01-05-adesso-goes-discord.md
> +Die neuste Version von JUnit ermöglicht es uns alle unsere Prüfungen auszuführen ohne, dass der Test abbricht sobald eine Prüfung nicht erfolgreich ist.
```suggestion
Die neuste Version von JUnit ermöglicht es uns, alle unsere Prüfungen auszuführen ohne, dass der Test abbricht sobald eine Prüfung nicht erfolgreich ist.
```

2022-02-21 11:45 UTC, jo2 submitted a review, later dismissed

2022-02-21 11:45 UTC, jo2 commented
@acetous von meiner Seite aus ist der Artikel soweit fertig.

2022-02-23 12:42 UTC, acetous approved these changes

2022-02-25 10:53 UTC, acetous submitted a review, later dismissed

2022-02-25 10:58 UTC, acetous approved these changes

2022-02-25 10:58 UTC, merged