Mit QGIS eine Fotolandkarte erstellen
adessoSE/devblog pull request #225
Opened 2022-01-26 17:34 UTC by c0c0bird

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-02-07 12:51 UTC, jo2 requested changes
Ein sehr interessanter Artikel, was mich persönlich noch interessieren würde wären Möglichkeiten zum kollaborativ Arbeiten, da die Daten ja wahrscheinlich nur in den seltensten von nur einer Person gesammelt werden. Ein paar Kleinigkeiten habe ich auch noch angemerkt.

2022-02-07 12:51 UTC, jo2 commented on _posts/2022-01-26-Mit-QGIS-eine-Fotolandkarte-erstellen.md
> +Was wir stattdessen brauchen, ist eine sogenannte "Datendefinierte Übersteuerung".
```suggestion
Was wir stattdessen brauchen, ist eine sogenannte "datendefinierte Übersteuerung".
```

2022-02-07 12:51 UTC, jo2 commented on _posts/2022-01-26-Mit-QGIS-eine-Fotolandkarte-erstellen.md
> +Jetzt fehlt noch eine große Ansicht, die sich bei Klick auf ein Vorschaubild öffnet.
```suggestion
Jetzt fehlt noch eine große Ansicht, die sich beim Klick auf ein Vorschaubild öffnet.
```

2022-02-07 14:01 UTC, c0c0bird commented on _posts/2022-01-26-Mit-QGIS-eine-Fotolandkarte-erstellen.md
> +Fast ohne Internet.
Danke, ist erledigt.

2022-02-07 14:05 UTC, c0c0bird commented
> was mich persönlich noch interessieren würde wären Möglichkeiten zum kollaborativ Arbeiten

Einen Hinweis auf "QGIS Server" habe ich am Ende angehängt.

2022-02-07 15:19 UTC, jo2 commented on _posts/2022-01-26-Mit-QGIS-eine-Fotolandkarte-erstellen.md
> + Um eine Karte als Team zu nutzen, lohnt sich ein Blick auf den Web Map Service [QGIS Server](https://www.qgis.org/de/site/about/features.html#qgis-server).
```suggestion
 Um eine Karte als Team zu nutzen, lohnt sich ein Blick auf den Web-Map-Service [QGIS Server](https://www.qgis.org/de/site/about/features.html#qgis-server).
```

2022-02-07 15:19 UTC, jo2 requested changes
Eine Kleinigkeit ist noch drin, danach ist der Artikel von meiner Seite aus fertig.

2022-02-07 16:18 UTC, c0c0bird commented
Okay, der Web-Map-Service ist jetzt eingedeutscht mit Bindestrichen. Hatte mich an der Schreibweise in der englischen Doku zu WMS orientiert.

2022-02-09 11:55 UTC, c0c0bird commented
Geht der Artikel diese Woche noch raus? Ansonsten würde ich ihn an jemanden, der auf die Anleitung wartet, auf anderem Wege verschicken.

2022-02-09 12:12 UTC, jo2 approved these changes

2022-02-09 12:13 UTC, jo2 commented
Von meiner Seite aus ist der so in Ordnung. Ob der diese Woche noch veröffentlich wird liegt bei @acetous.

2022-02-23 08:13 UTC, c0c0bird commented
Kann ich irgendwas tun, damit der Validator startet? Heute ist er abgebrochen mit der Meldung:

2022-02-23 08:08:08.629 ERROR 1 --- [           main] de.adesso.blogpostchecker.ConfigService  : Environment variable not provided: USERNAME. Please provide the username.
2022-02-23 08:08:08.629 ERROR 1 --- [           main] de.adesso.blogpostchecker.ConfigService  : Exiting BlogpostChecker.
Error: Process completed with exit code 15.

2022-02-23 12:46 UTC, acetous approved these changes

2022-03-04 10:02 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-10 10:30 UTC, acetous approved these changes

2022-03-10 10:31 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-10 10:37 UTC, merged