Initaler Pullrequest mit Bitte um Review
adessoSE/devblog pull request #227
Opened 2022-02-06 18:24 UTC by clunion

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-02-07 14:14 UTC, jo2 requested changes
Ein sehr interessanter Artikel, grade für mich als Java-Entwickler. Ein paar Kleinigkeiten habe ich dir noch angemerkt. Achte bitte auch auf eine geschlechtsneutrale Sprache (Anwender, Betreiber, ...)

2022-02-07 14:14 UTC, jo2 commented on _posts/2021-11-27-Rust_Rocks.md
> +2021-07-25: wurde die Vulnerability an das zuständige Rust Team gemeldet, welches mit der Arbeit an einer Lösung begann.
```suggestion
25.07.2021: Die Vulnerability wurde an das zuständige Rust-Team gemeldet, welches mit der Arbeit an einer Lösung begann.  
```

2022-02-07 14:14 UTC, jo2 commented on _posts/2021-11-27-Rust_Rocks.md
> +2021-11-01: Das Presse-Embargo wird aufgehoben, die Angreifbarkeit veröffentlicht und das gefixte Rust 1.56.1 herausgegeben. Zum Beispiel [schreibt heise hier darüber](https://www.heise.de/news/Angre
```suggestion
01.11.2021: Das Presse-Embargo wird aufgehoben, die Angreifbarkeit veröffentlicht und das gefixte Rust 1.56.1 herausgegeben. Zum Beispiel [schreibt heise hier darüber](https://www.heise.de/news/Angreifer-koennten-Source-Code-trojanisieren-der-trotzdem-legitim-aussieht-6237686.html).
```

2022-02-08 19:36 UTC, clunion commented on _posts/2021-11-27-Rust_Rocks.md
> +![rust_logo_rusty]
ok.

2022-02-17 10:48 UTC, jo2 commented
@clunion in dem Beitrag sind noch einige unresolved Threads. Kannst du dir die nochmal ansehen?

2022-02-17 11:41 UTC, clunion commented on _posts/2021-11-27-Rust_Rocks.md
> +Durchaus vorstellbar ist zudem, dass schon bald auf Nachhaltigkeit bedachte europäische Regierungen die Energieeffizienz von industriellen Erzeugnissen (also auch Software) einfordern werden. Viellei
Ja, Green IT ist eine art Fachbegriff, siehe den Link zur Seite des Europaparlaments oder auch hier: https://de.wikipedia.org/wiki/Green_IT.
Die dortmunder Green-IT hat mit ihrem Namen da schlicht Glück gehabt, oder visionär vorgegriffen...

2022-02-17 12:39 UTC, jo2 submitted a review, later dismissed

2022-02-17 12:40 UTC, jo2 commented
@acetous von meiner Seite aus ist der Artikel soweit fertig. Möchtest du nochmal drüber gucken? Ansonsten kann er veröffentlicht werden.

2022-02-23 12:49 UTC, acetous approved these changes

2022-04-14 07:15 UTC, acetous submitted a review, later dismissed

2022-04-14 07:16 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-04-14 07:16 UTC, acetous approved these changes

2022-04-14 07:18 UTC, merged