Reaktive Programmierung mit Spring Webflux
adessoSE/devblog pull request #228
Opened 2022-02-14 07:20 UTC by schroeerth

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-02-17 11:17 UTC, jo2 requested changes
Ein sehr interessanter Blogartikel, ein paar Sachen habe ich euch noch angemerkt. Was mich persönlich noch interessieren würde ist, wie teste ich das ganze? Vielleicht könnt ihr dazu in diesem oder einem folgenden Artikel noch etwas zu schreiben.

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Diese beschränken sich jedoch oft auf die Kommunikation nach außen, also auf Controller, Datenbank-Repositories und Webclients, die andere Rest-APIs konsumieren.
```suggestion
Diese beschränken sich jedoch oft auf die Kommunikation nach außen, also auf Controller, Datenbank-Repositories und Webclients, die andere REST APIs konsumieren.
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +In der Methode, die innerhalb des map-Befehls aufgerufen wird (Hier `buildAbbreviatedName`),
```suggestion
In der Methode, die innerhalb des `map`-Befehls aufgerufen wird (hier `buildAbbreviatedName`),
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Der Operator flatMap unterscheidet sich insofern von map, als er als Rückgabewert der übergebenen Methode wieder einen Publisher erwartet.
```suggestion
Der Operator `flatMap` unterscheidet sich insofern von `map`, als dass er als Rückgabewert der übergebenen Methode wieder einen Publisher erwartet.
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Das ist etwa dann sinnvoll, wenn diese Methode ihrerseits wieder einen API-Call absetzen muss.
```suggestion
Das ist etwa dann sinnvoll, wenn diese Methode ihrerseits wieder einen API-Aufruf absetzen muss. 
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Wir können also mit map und flatMap Ergebnisse eines Publishers umwandeln. Aber was, wenn die Daten zweier oder mehrerer Publisher kombiniert benötigt werden?
```suggestion
Wir können also mit `map` und `flatMap` Ergebnisse eines Publishers umwandeln. Aber was, wenn die Daten zweier oder mehrerer Publisher kombiniert benötigt werden?
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +In diesem Fall können die Methoden zipWith und zipWhen genutzt werden. In folgendem Beispiel wird die Methode zipWith genutzt,
```suggestion
In diesem Fall können die Methoden `zipWith` und `zipWhen` genutzt werden. In folgendem Beispiel wird die Methode `zipWith` genutzt, 
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Dann müssten wir mit Informationen aus der Response des Blogpost-Clients den UserClient aufrufen, um anschließend wieder mit beiden Ergebnissen
```suggestion
Dann müssten wir mit Informationen aus der Response des `BlogpostClients` den `UserClient` aufrufen, um anschließend wieder mit beiden Ergebnissen
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +weiterzuarbeiten. Hier kommt ``zipWhen`` ins Spiel. Mit dieser Methode kann man ähnlich wie mit ``flatMap``
```suggestion
weiterzuarbeiten. Hier kommt ``zipWhen`` ins Spiel. Mit dieser Methode kann man, ähnlich wie mit ``flatMap``,
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Außerdem ist der Aufruf von incrementViewCount wieder asynchron. Das bedeutet, dass man nicht davon ausgehen kann, dass der Zähler
```suggestion
Außerdem ist der Aufruf von `incrementViewCount` wieder asynchron. Das bedeutet, dass man nicht davon ausgehen kann, dass der Zähler
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +auf dem aktuellsten Stand ist, wenn getBlogpost sein Ergebnis zurückgibt. Wenn das erforderlich ist, muss statt ``doOnNext``
```suggestion
auf dem aktuellsten Stand ist, wenn `getBlogpost` sein Ergebnis zurückgibt. Wenn das erforderlich ist, muss statt ``doOnNext``
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Wenn in der Ausführsequenz eine Methode einen Fehler wirft, gibt der Publisher ein Error-Signal anstelle des Werts aus.
```suggestion
Wenn in der Ausführungssequenz eine Methode einen Fehler wirft, gibt der Publisher ein Error-Signal anstelle des Werts aus. 
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Dieses Signal wird wie normale RuntimeExceptions so lange an die nächsten Subscriber weitergereicht, bis es irgendwo explizit behandelt wird.
```suggestion
Dieses Signal wird wie eine normale `RuntimeException` so lange an die nächsten Subscriber weitergereicht, bis es irgendwo explizit behandelt wird.
```

2022-02-17 11:17 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +erwähnte [Operatorenübersicht](https://projectreactor.io/docs/core/release/reference/#which-operator) aus dem Project Reactor
```suggestion
erwähnte [Operatorenübersicht](https://projectreactor.io/docs/core/release/reference/#which-operator) aus dem Project-Reactor-
```

2022-03-10 11:42 UTC, acetous requested changes
Bearbeitet ihr noch bitte die Anmerkungen von Johannes und schaut einmal auf meine Kommentare? Danach kann der Blogpost dann live gehen.

2022-03-10 11:42 UTC, acetous commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +![image of reactive streams interfaces](/assets/images/posts/reaktive-programmierung-mit-spring-webflux/reativestream.png)
Könnt ihr hierzu bitte noch ein Sequenzdiagramm erstellen? Dann wird die Abfolge der Aufrufe, wer das initiiert und welcher Akteur wann aktiv ist auch klar.

2022-03-10 11:42 UTC, acetous commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +## map und flatMap
Mit dem Sequenzdiagramm (s.o.) könnt ihr dann ab hier auch zeigen, warum man im Service auch Webflux-APIs benutzen muss.

2022-03-10 11:42 UTC, acetous commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Mithilfe dieser 9 Methoden solltet ihr für den Start in die Programmierung mit Spring Webflux gerüstet sein.
Für einen gelungenen Abschluss könnt ihr noch die Überschrift "Fazit" oder "Zusammenfassung" einfügen und gerne nochmal auf den Inhalt zurückschauen.

2022-03-10 11:42 UTC, acetous commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +
Mir fehlt hier auch noch die Handhabung von APIs / Frameworks, welche kein Webflux inne haben. Wie integriere ich Java-APIs in meine reaktive Anwendung, welche keine reaktive Programierung unterstützen?

2022-03-25 14:46 UTC, schroeerth commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +
Darauf gehe ich ja sehr oberflächlich ein, bei map und flatMap:

"[...]muss nicht mit den Webflux-Publishern gearbeitet werden,
die eigentliche Geschäftslogik kann also mit gewöhnlichem Java-Code implementiert werden."

Das deckt natürlich nicht alle Möglichkeiten ab, aber für den Start fand ich die beschriebenen Methoden am relevantesten. Wir können aber auch noch fromCallable, fromRunnable u.Ä. mit einführen, aber wir haben ja bewusst geschrieben wir bieten erst einmal eine kleine Methodenauswahl, mit der man ins Thema starten kann.

2022-04-04 07:26 UTC, jo2 commented
@schroeerth guckt ihr euch das hier noch an?

2022-05-30 19:20 UTC, jo2 requested changes
Ein paar Sachen sind noch drin, könnt ihr die noch beheben?

2022-05-30 19:20 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Das Spring Framework nutzt das Open-Source-Projekt Reactor als Basis für die Umsetzung der reaktiven Programmierung.
```suggestion
Das Spring-Framework nutzt das Open-Source-Projekt Reactor als Basis für die Umsetzung der reaktiven Programmierung.
```

2022-05-30 19:20 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Sie sollten immer dann genutzt werden, wenn man das Ergebnis eines Monos oder Fluxes weiter verarbeiten möchte.
```suggestion
Sie sollten immer dann genutzt werden, wenn man das Ergebnis eines Mono oder Flux weiter verarbeiten möchte.
```

2022-05-30 19:20 UTC, jo2 commented on _posts/2022-02-11-Reaktive-Programmierung-mit-Spring-Webflux.md
> +Zu beachten ist hier, auch wenn sich am eigentlichen Inhalt des Monos nichts ändert, muss dennoch der Rückgabewert der ``doOnNext``-Methode
```suggestion
Zu beachten ist hier, auch wenn sich am eigentlichen Inhalt des Mono nichts ändert, muss dennoch der Rückgabewert der ``doOnNext``-Methode
```

2022-06-13 12:46 UTC, jo2 approved these changes
Der Artikel sieht soweit gut aus, ihr müsstet noch einmal den aktuellen master branch in euren Branch mergen, dann passt alles.

2022-07-01 13:55 UTC, merged