write artikel about loki
adessoSE/devblog pull request #230
Opened 2022-03-20 15:03 UTC by hesch

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-03-20 15:03 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-20 15:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-20 15:15 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-20 15:42 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-21 12:47 UTC, jo2 requested changes
Der Artikel liest sich shcon recht gut, Ein paar Sachen habe ich dir noch angemerkt. Allerdings ist der Artikel etwas dünn, kannst du den Artikel vielleicht noch etwas erweitern? Interessante Punkte wären:
* Wie schreibt man Loki Queries?
* Wie sieht die Integration in eine bestehende Microservicearchitektur aus?
* Loki ist kleiner und leichtgewichtiger als der Elastic-Stack. Gibt es irgendwelche Nachteile bei Loki?

2022-03-21 12:47 UTC, jo2 commented on _data/authors.yml
> +  bio: "Henri Schmidt ist seit 2015 bei adesso in Dortmund als Werkstudent tätig. Er ist Fullstack-Entwickler und arbeitet mit Microservice-Systemen basierend auf Java und Frontendanwendungen mit Ang
```suggestion
  bio: "Henri Schmidt ist seit 2015 bei adesso in Dortmund als Werkstudent tätig. Er ist Fullstack-Entwickler und arbeitet mit Microservice-Systemen basierend auf Java und mit Frontendanwendungen mit Angular."
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Gerade in verteilten Systemen ist es bei wachsender Zahl von Komponenten schwierig den Überblick über alle Logs zu behalten.
```suggestion
Gerade in verteilten Systemen ist es bei wachsender Zahl von Komponenten schwierig, den Überblick über alle Logs zu behalten.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Dieser Artikel beschreibt wie der Logaggregationsdienst Loki mit allen notwendigen Komponenten aufgesetzt werden kann und in ein bestehendes System aus Microservices eingebunden werden kann.
```suggestion
Dieser Artikel beschreibt, wie der Logaggregationsdienst Loki mit allen notwendigen Komponenten aufgesetzt und in ein bestehendes System aus Microservices eingebunden werden kann.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Wer kein großes ressourcenfressendes System aufsetzen möchte, kann aber auf Loki setzen.
```suggestion
Wer kein großes, ressourcenfressendes System aufsetzen möchte, kann aber auf Loki setzen.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Loki hat dabei gegenüber den anderen Technologien den Vorteil leichtgewichtiger zu sein.
```suggestion
Loki hat dabei gegenüber den anderen Technologien den Vorteil, leichtgewichtiger zu sein.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Promtail ist hier dafür zuständig, die Logs aus verschiedenen Quellen zu sammeln und an Loki weiterzuleiten.
```suggestion
Promtail ist dafür zuständig, die Logs aus verschiedenen Quellen zu sammeln und an Loki weiterzuleiten.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Hier ist ein einfaches Beispiel für eine docker-compose Konfiguration, um Promtail zu starten:
```suggestion
Hier ist ein einfaches Beispiel für eine docker-compose-Konfiguration, um Promtail zu starten:
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Unter der Portfreigabe sehen wir noch zwei Volumen.
```suggestion
Unter der Portfreigabe sehen wir noch zwei Volumes.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Das erste Volumen mounted unsere Konfigurationsdatei in den Container.
```suggestion
Das erste Volume mounted unsere Konfigurationsdatei in den Container.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Das zweite gibt hier in unserem Beispiel einfach einmal die Systemlogdateien an Promtail weiter.
```suggestion
Das zweite gibt hier in unserem Beispiel die Systemlogdateien an Promtail weiter.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Hier sehen wir einmal die in den Container gemountete Konfigurationsdatei von Promtail:
```suggestion
Hier sehen wir die in den Container gemountete Konfigurationsdatei von Promtail:
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Normalerweise sollte diese Datei auch in einem Dockervolumen liegen, aber für unser Testbeispiel liegt die Datei einfach im Container.
```suggestion
Normalerweise sollte diese Datei auch in einem Docker Volume liegen, aber für unser Testbeispiel liegt die Datei einfach im Container.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Unter `cients` wird die Loki-Instanz konfiguriert, welche Promtail verwenden soll.
```suggestion
Unter `clients` wird die Loki-Instanz konfiguriert, welche Promtail verwenden soll.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Eine weitere Möglichkeit Logs in Loki einzuliefern ist das Loki-Docker-Plugin, welches sich als Loggingtreiber in Docker einbindet und so die Logs an Loki weiterleitet.
```suggestion
Eine weitere Möglichkeit, Logs in Loki einzuliefern ist das Loki-Docker-Plugin, welches sich als Loggingtreiber in Docker einbindet und so die Logs an Loki weiterleitet.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Danach kann der Loggingtreiber in der docker-compose Datei durch einen logging-Block folgendermaßen eingebunden und konfiguriert werden:
```suggestion
Danach kann der Loggingtreiber in der docker-compose-Datei durch einen logging-Block folgendermaßen eingebunden und konfiguriert werden:
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Eine weitere Alternative Logs an Loki zu schicken ist beispielsweise der [loki-logback-appender](https://github.com/loki4j/loki-logback-appender), der in die Logging-Konfiguration der einzelnen Micro
```suggestion
Eine weitere Alternative, Logs an Loki zu schicken, ist der [loki-logback-appender](https://github.com/loki4j/loki-logback-appender), der in die Logging-Konfiguration der einzelnen Microservices eingebunden wird und dann selbstständig Logs zu Loki schickt.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Im Grunde genommen, ist Loki eine Datenbank, die Logzeilen abspeichert und einen sehr schlanken Index für diese anlegt.
```suggestion
Im Grunde genommen ist Loki eine Datenbank, die Logzeilen abspeichert und einen sehr schlanken Index für diese anlegt.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Zum Beispiel: Log-Level oder loggender Service.
```suggestion
Beispiele für diese Labels sind das Log-Level oder der loggender Service.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Zum einen kann Loki als einzelner Server oder im Microservice-Modus laufen.
```suggestion
Loki kann grundlegend in zwei Modi ausgeführt werden, entweder als einzelner Server oder im Microservice-Modus.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Kommen wir jetzt zum eigentlichen Herzstück der Loki Konfiguration.
```suggestion
Kommen wir jetzt zum eigentlichen Herzstück der Loki-Konfiguration.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Die docker-compose Datei für Loki sieht sehr ähnlich aus, wie die von Promtail.
```suggestion
Die docker-compose-Datei für Loki sieht sehr ähnlich aus, wie die von Promtail.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Dadurch funktioniert die Namensauflösung, damit die URLs von promtail funktionieren.
```suggestion
Dadurch funktioniert die Namensauflösung und die in Promtail definierten URLs funktionieren.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Loki benötigt als Volumen einmal einen Ort für die Daten und die Konfigurationsdatei.
```suggestion
Loki benötigt als Volume einen Ort für die Daten und die Konfigurationsdatei.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +In unserem Fall einfach das Dateiensystem.
```suggestion
In unserem Fall verwenden wir das Dateiensystem.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Als nächstes konfigurieren wir den `ring` ein Key-Value-Store, der von Loki intern zur Synchronisation der Instanzen verwendet wird.
```suggestion
Als nächstes konfigurieren wir den `ring`, einen Key-Value-Store, der von Loki intern zur Synchronisation der Instanzen verwendet wird.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Boltdb ist eine Alternative, die auf dem Dateinsystem funktioniert, ähnlich wie SQLite in der SQL Welt.
```suggestion
Boltdb ist eine Alternative, die auf dem Dateinsystem funktioniert, ähnlich wie SQLite in der SQL-Welt.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Grafana benötigt, wie die anderen Dienste auch, ein Volumen für die Datenbank und eine Portfreigabe.
```suggestion
Grafana benötigt, wie die anderen Dienste auch, ein Volume für die Datenbank und eine Portfreigabe.
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Also können wir mit folgender docker-compose Datei einfach Grafana starten:
```suggestion
Also können wir mit folgender docker-compose-Datei Grafana starten:
```

2022-03-21 12:47 UTC, jo2 commented on _posts/2022-03-20-Logaggregation-in-verteilten-Systemen-mit-Loki.md
> +Dazu einfach unter `Configuration>Data sources>Add Data source` Loki auswählen.
```suggestion
Dazu wählen wir in Grafana unter `Configuration>Data sources>Add Data source` Loki aus.
```

2022-04-04 07:24 UTC, jo2 commented
@hesch kannst du dir die eine Anmerkung in deiner Bio noch ansehen?

2022-04-20 14:53 UTC, acetous commented
Hallo @hesch! Das liest sich schon gut, allerdings würde ich mir noch wünschen, dass Du noch ein Feature erklärst. Gegenüber vielen Getting Started-Guides könntest Du hier noch erklären, wie wir ein typisches Log einer Spring Boot-Anwendung parsen können. Dazu gehört auch, Stacktraces als einen Eintrag durch die multiline-Stage in Promtail zu erfassen. Damit könntest Du die Blogpost nochmal von den anderen Guides im Netz abheben und für unsere Java-lastige Welt eine notwendige Config erläutern.

2022-11-21 08:35 UTC, acetous commented
Wird aufgrund Inaktivität geschlossen.

2022-11-21 08:35 UTC, closed without merging