Neuer Artikel: Digitalisierung für den Strukturwandel
adessoSE/devblog pull request #231
Opened 2022-03-23 11:42 UTC by c0c0bird

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-03-23 11:42 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 17:17 UTC, jo2 requested changes
Einige Anmerkungen habe ich noch gemacht.

2022-03-23 17:17 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +In 2016 waren ca. eine Million Menschen in der Landwirtschaft beschäftigt.
In Deutschland, Europa oder weltweit?

2022-03-23 17:17 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Zusätzlich werden die Ernteerträge durch Extremwetterereignisse und Dürren bedroht, den globalen Süßwassermangel und Biodiversitätsverluste wie das Bienensterben.
```suggestion
Zusätzlich werden die Ernteerträge durch Extremwetterereignisse und Dürren, dem globalen Süßwassermangel und Biodiversitätsverluste wie dem Bienensterben bedroht.
```

2022-03-23 17:17 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Ein Strukturwandel hin zu resilienten Geschäftsmodellen sind daher dringend geboten.
```suggestion
Ein Strukturwandel hin zu resilienten Geschäftsmodellen ist daher dringend geboten.
```

2022-03-23 17:17 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Neben der Landwirtschaft zählen die Forst- und die Holzwirtschaft mit 100.000 Beschäftigte zu den wichtigsten Produzenten nachwachsender Rohstoffe.
```suggestion
Neben der Landwirtschaft zählen die Forst- und die Holzwirtschaft mit 100.000 Beschäftigten zu den wichtigsten Produzenten nachwachsender Rohstoffe.
```

2022-03-23 17:52 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 17:55 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 17:55 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:01 UTC, c0c0bird commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Hier bestehen jedoch Möglichkeiten, Materialien nach zu nutzen und zu recyceln.
Danke, ich habe die Sätze jetzt entwirrt.

2022-03-23 18:02 UTC, c0c0bird commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Die Automobilbranche, die von einer hohen Komplexität gekennzeichnet ist, wird auch in Zukunft von der Digitalisierung profitieren.
Da hab ich doch das Schlagwort "Industrie 4.0" vergessen. Die fehlende Erklärung ist jetzt drin.

2022-03-23 18:07 UTC, c0c0bird commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +In 2016 waren ca. eine Million Menschen in der Landwirtschaft beschäftigt.
Danke, jetzt sind sie "in der deutschen Landwirtschaft".

2022-03-23 18:08 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:09 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:09 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:09 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:10 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:10 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:11 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:12 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:12 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:14 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:40 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-23 18:42 UTC, c0c0bird commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Sie kann helfen, Anpassungstechnologien für klimafreundliche Produkte in anderen Wirtschaftssektoren zu entwickeln.
Auch hier ist der Absatz nun etwas entwirrt.

2022-03-23 18:46 UTC, c0c0bird commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Ebenso eröffnet die Digitalisierung neue Möglichkeit für Kraftwerksbau, Heizungsbau und die Wassertechnologie.
Ok, da hab ich gleich mal einen Link zum Blogbeitrag über "virtuelle Kraftwerke" eingefügt.

2022-03-23 18:47 UTC, c0c0bird commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Bevölkerungswachstum, Anstieg der Energienachfrage und die Digitalisierung sind wesentliche Megatrends, die die Zukunft der Energiewirtschaft beeinflussen.
Ok, jetzt gehe ich auf die steigende Nachfrage ein und erkläre dabei gleich noch die Smart Grids.

2022-03-23 18:49 UTC, c0c0bird commented
Vielen Dank! Die Anmerkungen habe ich alle behoben, jetzt müsste der Artikel schon deutlich verständlicher sein.

2022-03-24 16:18 UTC, jo2 requested changes
Ein paar Kleinigkeiten sind noch drin, die Anpassungen sind gut.

2022-03-24 16:18 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Sie hat einen hohen Verbrauch an Rohstoffen in der Vorproduktion und Kraftstoffen in der Nutzungsphase.
```suggestion
Sie hat einen hohen Verbrauch an Rohstoffen in der Vorproduktion und an Kraftstoffen in der Nutzungsphase.
```

2022-03-24 16:18 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Im Fall elektrisch angetriebener Fahrzeuge ist von einer etwa doppelten Menge an Treibhausgas-Emissionen aus der Herstellungsphase auszugehen.
```suggestion
Im Fall elektrisch angetriebener Fahrzeuge ist von einer etwa doppelten Menge an Treibhausgasemissionen aus der Herstellungsphase auszugehen.
```

2022-03-24 16:18 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Digitale Automatisierungsverfahren, die der Maschinenbau entwickelt, helfen in der Landwirtschaft dabei, Abläufe zu optimieren und damit zur Nachhaltigkeit beitragen.
```suggestion
Digitale Automatisierungsverfahren, die der Maschinenbau entwickelt, helfen in der Landwirtschaft dabei, Abläufe zu optimieren und damit zur Nachhaltigkeit beizutragen.
```

2022-03-24 16:18 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Ein Smart Grid vernetzt Erzeugung, Speicherung und Verbrauch, so dass Verluste minimiert und Lastspitzen ausgeglichen werden.
```suggestion
Ein Smart Grid vernetzt Erzeugung, Speicherung und Verbrauch, sodass Verluste minimiert und Lastspitzen ausgeglichen werden können.
```

2022-03-24 16:18 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Damit kann die steigende Nachfrage bedient werden, ohne dass die Kraftwerkskapazitäten sofort mitwachsen.
```suggestion
Damit kann die steigende Nachfrage bedient werden, ohne dass die Kraftwerkskapazitäten sofort mitwachsen müssen.
```

2022-03-24 16:18 UTC, jo2 commented on _posts/2022-03-23-Digitalisierung-fuer-den-Strukturwandel.md
> +Zusätzlich werden die Ernteerträge durch Extremwetterereignisse und Dürren, dem globalen Süßwassermangel und Biodiversitätsverluste wie dem Bienensterben bedroht.
```suggestion
Zusätzlich werden die Ernteerträge durch Extremwetterereignisse und Dürren, den globalen Süßwassermangel und Biodiversitätsverluste wie dem Bienensterben bedroht.
```
Das war, glaube ich, mein Fehler.

2022-03-24 17:57 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-24 17:57 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-24 17:57 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-24 17:57 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-24 18:14 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-03-24 18:45 UTC, c0c0bird commented
Danke, die neuen Suggestions sind jetzt auch übernommen.

2022-03-29 12:25 UTC, jo2 approved these changes

2022-04-14 10:24 UTC, jo2 commented
@acetous willst du noch drüber gucken? Ansonsten ist der Artikel bereit zur Veröffentlichung.

2022-04-20 14:55 UTC, acetous approved these changes

2022-04-20 14:58 UTC, merged