Projekt Amber Teil Syntaktik Suggar
adessoSE/devblog pull request #233
Opened 2022-04-07 11:12 UTC by MBoegers

**On Hold, wird noch bearbeitet**

In diesem Blogpost verwandel ich einen Teil meines Talks vom Javaland "Schmuckes Java – Was Projekt Amber für Entwickler bietet", der Talk wird u.a. auf der Developer Week 2022 wiederholt.
Da der Inhalt einen Blogeintrag sprengen würde, werde ich die Teile als einzelne Posts einreichen.

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-04-07 11:12 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-04-07 11:27 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-04-11 14:53 UTC, jo2 requested changes
Einige Sachen habe ich noch korrigiert. Achte bitte außerdem auf eine einheitliche Verwendung des Genus bei JEP. Ich glaube, ich habe alle Stellen gefunden, guck aber bitte noch einmal drüber.

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Das `var` Keyword kann nur in Verbindung mit einer direkten Zuweisung verwendet werden und kann mit dem `final` Keyword kombiniert werden.
```suggestion
Das Keyword `var` kann nur in Verbindung mit einer direkten Zuweisung verwendet werden und es kann mit dem `final` Keyword kombiniert werden.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Seid [JEP-286](https://openjdk.java.net/jeps/286) und Java 10 finalisiert wurde, ist es nicht mehr notwendig Typinformationen zu doppeln oder komplexe generische Typen auszuschreiben.
```suggestion
Seid [JEP-286](https://openjdk.java.net/jeps/286) und dem finalen Stand von Java 10 ist es nicht mehr notwendig, Typinformationen zu doppeln oder komplexe generische Typen auszuschreiben.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Mit [JEP-323](https://openjdk.java.net/jeps/323) in Java 11 ist es möglich, das `var` Keyword auch bei der Definition von Lauda-Parametern zu verwenden.
```suggestion
Mit [JEP-323](https://openjdk.java.net/jeps/323) in Java 11 ist es möglich, das Keyword `var` auch bei der Definition von Lambda-Parametern zu verwenden.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Damit ist der Syntax für von Lamdas angeglichen worden und es ist möglich Lamda-Parameter mit Annotationen zu versehen.
```suggestion
Damit ist die Syntax von Lambdas angeglichen worden und es ist möglich, Lambda-Parameter mit Annotationen zu versehen.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Ein Textblock beginnt und endet mit `"""` sowie einem Zeilenumbruch.
```suggestion
Seit Java 15 und JEP-378 beginnt und endet ein Textblock mit `"""` sowie einem Zeilenumbruch.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Das Switch Statement hat in seiner Geschichte einige Verbesserungen erlebt, es gibt aber auch berechtigte Kritik.
```suggestion
Die `switch`-Anweisung hat in seiner Geschichte einige Verbesserungen erlebt, es gibt aber auch berechtigte Kritik.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Neben der leicht zu übersehenden Fall-Throught Semantik und unhandlichen Fehlerbehandlung ist es auch nicht möglich, dass switch einen Wert zurückliefert.
```suggestion
Neben der leicht zu übersehenden Fall-Through-Semantik und der unhandlichen Fehlerbehandlung ist es auch nicht möglich, dass die `switch`-Anweisung einen Wert zurückgibt.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> ++ die **switch Expression** liefert einen Wert zurück welche in `j` gespeichert wird. Bei einzeiligen Case-Blöcken kann die Werte einfach hingeschrieben werden, bei mehrzeiligen muss das Keyword `yie
```suggestion
+ Die **`switch`-Anweisung** liefert einen Wert zurück, welcher in `j` gespeichert wird. Bei einzeiligen `case`-Blöcken kann der Wert einfach ausgeschrieben werden, bei mehrzeiligen Blöcken muss das Keyword `yield` verwendet werden.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> ++ auf die **Fall-Throught Semantik** wird mit `->` verzichtet. Hier können mit Komma getrennt eine Liste von Case Labels angegeben werden, um mehrere Zweige zu gruppieren.
```suggestion
+ Auf die **Fall-Through-Semantik** wird mit `->` verzichtet. Hier können mit Komma getrennt eine Liste von Case Labels angegeben werden, um mehrere Zweige zu gruppieren.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> ++ die **Fehlerbehandlung** kann explizit geschehen, da `null` jetzt ein legales Case-Label ist. Wird der case `null` nicht explizite behandelt, so verhält sich switch wie gewohnt.
```suggestion
+ Die **Fehlerbehandlung** kann explizit geschehen, da `null` jetzt ein legales Case Label ist. Wird der case `null` nicht explizite behandelt, so verhält sich die `switch`-Anweisung wie gewohnt.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> ++ es müssen alle möglichen Cases abgedeckt werden oder default verwendet werden. Dies klappt auf für die neuen Sealed Classes.
```suggestion
+ Es müssen alle möglichen Cases abgedeckt oder default verwendet werden. Dies funktioniert auch für die neuen Sealed Classes.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Anhand der Draft und nicht targettted JEPs lässt sich erahnen auf welche Neuerungen wir hoffen können.
```suggestion
Anhand von Entwürfen und JEPs, die noch keine Zielversion haben, lässt sich erahnen, auf welche Neuerungen wir in Zukunft hoffen können.
```
Ich würde diese Überschrift als eigenes Kapitel ansehen und nur ein '#' verwenden. Dementsprechend müsstest du das, wenn du das übernimmst, auch bei den untergeordneten Überschriften anwenden.

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +### Nacharbeiten an Lamdas
```suggestion
### Nacharbeiten an Lambdas
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +[JEP-302: Lambda Leftovers](https://openjdk.java.net/jeps/302) soll die Benutzbarkeit von Lamdas verbessen in dem nicht genutzte Parameter nicht definiert werden müssen und Lamdaparameter keine Lokal
```suggestion
[JEP-302: Lambda Leftovers](https://openjdk.java.net/jeps/302) soll die Benutzbarkeit von Lambdas verbessen, indem nicht genutzte Parameter nicht definiert werden müssen und Lambda-Parameter keine lokalen Variablen mehr überschreiben können.
```
Vorher hattest du den Titel des JEP jeweils als Überschrift für den Absatz, mach das bitte einheitlich

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Die lokale Variable `String key` wird nicht durch den Lamda Parameter `Integer key` verschattet.
```suggestion
Die lokale Variable `String key` wird nicht durch den Lambda-Parameter `Integer key` überschrieben.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +[Concise Method Bodies](https://openjdk.java.net/jeps/8209434) soll die Zeremonie für einzeilige Methoden vereinfacht werden.
```suggestion
Mit [Concise Method Bodies](https://openjdk.java.net/jeps/8209434) soll die Zeremonie für einzeilige Methoden vereinfacht werden.
```
Bitte verwende anstelle von Zeremonie einen geeigneteren Begriff.

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Javas Sprachfeatures gelten als leicht gealtert und sehr zeremoniell.
Bitte verwende anstelle von zeremoniell einen geeigneteren Begriff.

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Dadurch sollen Classen mit vielen einfachen Methoden besser lesbar werden.
```suggestion
Dadurch sollen Klassen mit vielen einfachen Methoden besser lesbar gemacht werden.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Dieser JEP ist noch ein Entwurf und es ist nicht sicher, ob diese Änderungen jemals Teil der Sprache Java werden.
```suggestion
Dieses JEP ist noch ein Entwurf und es ist nicht sicher, ob diese Änderung jemals Teil der Sprache Java wird.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Durch einen Synttaks in Strings sollen lokal sichtbare Variablen in Strings eingebunden werden.
```suggestion
Durch eine Änderung in der Syntax von Strings sollen lokal sichtbare Variablen in Strings eingebunden werden können.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Für diese JEP ist noch nicht klar, ob und wie dieses Feature in Java integriert werden soll.
```suggestion
Für dieses JEP ist noch nicht klar, ob und wie dieses Feature in Java integriert werden soll.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Wir haben gesehen, welche neuen Sprachkonstrukte Projekt Amber eingebracht hat.
```suggestion
Wir haben gesehen, welche neuen Sprachkonstrukte Project Amber eingebracht hat.
```

2022-04-11 14:53 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Alle diese Konstrukte tragen zum _neue Java_ bei und vereinfachen die Arbeit mit Java.
```suggestion
Alle diese Konstrukte tragen zum _neue Java_ bei und vereinfachen die Arbeit mit der Sprache.
```

2022-04-14 10:26 UTC, jo2 commented
Ist es Absicht, dass der PR geschlossen wurde?

2022-04-14 10:38 UTC, MBoegers commented
Nein, es war ein Versehen. Kannst du das wieder rückgängig  machen? Sonst öffne ich ihn die Tage bei mir den neuen Anpassungen

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: johannesteklote ***@***.***>
Gesendet: Thursday, April 14, 2022 12:26:35 PM
An: adessoSE/devblog ***@***.***>
Cc: Merlin Bögershausen ***@***.***>; State change ***@***.***>
Betreff: Re: [adessoSE/devblog] Projekt Amber Teil Syntaktik Suggar (PR #233)


Ist es Absicht, dass der PR geschlossen wurde?

—
Reply to this email directly, view it on GitHub<https://github.com/adessoSE/devblog/pull/233#issuecomment-1099028852>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABZVCFN6K2PHYKMTNF4YMQ3VE7XFXANCNFSM5SZAHAFQ>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2022-04-18 11:47 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-04-18 12:25 UTC, MBoegers commented on _posts/2022-04-07-Schmuckes-Java.md
> +Javas Sprachfeatures gelten als leicht gealtert und sehr zeremoniell.
Was meinst, du passt 'verbose' ?

2022-04-18 19:46 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-04-19 08:56 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Javas Sprachfeatures gelten als leicht gealtert und sehr zeremoniell.
Ich würde vielleicht Boilerplate verwenden.

2022-04-19 09:00 UTC, jo2 commented
Du hast aus irgendwelchen Gründen in deinem PR auch den Artikel von Christian Lunau mit drin. Kannst du dir das nochmal angucken? Damit die Pipelines funktionieren, darf nur ein Artikel je PR vorhanden sein.

2022-04-19 10:14 UTC, MBoegers commented
> Du hast aus irgendwelchen Gründen in deinem PR auch den Artikel von Christian Lunau mit drin. Kannst du dir das nochmal angucken? Damit die Pipelines funktionieren, darf nur ein Artikel je PR vorhanden sein.

Ich habe meinen Branch auf den neusten Stand (rebase master) gebracht. Da ist der von Christian schon mit dabei. Sollte also nur ein neuer Artikel sein ;) wenn nicht dann versuche ich das wieder zurück zu bauen..

2022-04-19 10:46 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-04-19 10:49 UTC, MBoegers commented on _posts/2022-04-07-Schmuckes-Java.md
> +Javas Sprachfeatures gelten als leicht gealtert und sehr zeremoniell.
ersetzt

2022-04-19 11:37 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-04-19 13:23 UTC, jo2 requested changes
Ein paar Kleinigkeiten habe ich noch angemerkt, es ist aber nicht mehr viel.

2022-04-19 13:23 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +3. _Pattern Matching für Java_, um funktionale Paradigmen zu ermöglichen
Von der Benennung her würde ich sagen, sind die beiden Punkte vertauscht oder?

2022-04-19 13:23 UTC, jo2 commented on _posts/2022-04-07-Schmuckes-Java.md
> +Alle diese Konstrukte tragen zum _neue Java_ bei und vereinfachen die Arbeit mit der Sprache.
```suggestion
Alle diese Konstrukte tragen zum _neuen Java_ bei und vereinfachen die Arbeit mit der Sprache.
```

2022-04-19 14:07 UTC, MBoegers commented on _posts/2022-04-07-Schmuckes-Java.md
> +Dieser Prozess soll verhindern, dass Sprachfeatures übernommen werden, welche nicht die Anforderungen der Entwickler:innen befriedigt.
Ich dachte alle : ersetzt zu haben ... nehme Community

2022-04-19 14:32 UTC, MBoegers commented on _posts/2022-04-07-Schmuckes-Java.md
> +# Was ist ein OpenJDK-Project?
Eigentlich ist ein OpenJDK-Project ein fester Begriff aus der OpenJDK-Community, deswegen würde ich hier lieber _Project_ nutzten. Konsequenterweise müsste es dann aber auch in Zeile 20 _Project_ im Link heißen.

2022-04-19 14:52 UTC, MBoegers commented on _posts/2022-04-07-Schmuckes-Java.md
> +3. _Pattern Matching für Java_, um funktionale Paradigmen zu ermöglichen
Ich hoffe, das wird in den folge Artikeln zu den Punkten 2 und 3 klarer :D

2022-04-19 14:54 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-04-19 14:58 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-04-19 15:28 UTC, jo2 submitted a review, later dismissed

2022-05-20 07:58 UTC, MBoegers commented
Blocked by https://github.com/adessoSE/devblog/issues/242

2022-05-30 19:23 UTC, merged