Artikel: Energiemanagement im Rechenzentrum
adessoSE/devblog pull request #239
Opened 2022-05-09 15:10 UTC by c0c0bird

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-05-09 17:31 UTC, jo2 requested changes
Der Artikel liest sich sehr gut und ist sehr interessant. Aus persönlichem Interesse, haben wir bei adesso so etwas? Wenn wir sowas haben, wäre vielleicht noch eine Ergänzung oder ein weiterer Beitrag interessant, was wir da alles machen.

2022-05-09 17:31 UTC, jo2 commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Für kleine und mittlere Unternehmen kann ein freiwilliges Energieaudit nach der europäischen Norm EN 16247 sinnvoll sein, denn es hilft Kosten zu senken und das Zertifikat beweist Umweltbewusstsein.
```suggestion
Für kleine und mittlere Unternehmen kann ein freiwilliges Energieaudit nach der europäischen Norm EN 16247 sinnvoll sein, denn es hilft, Kosten zu senken, und das Zertifikat beweist Umweltbewusstsein.
```

2022-05-09 17:31 UTC, jo2 commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Bis zu 80% der Kosten werden jedoch vom Bundesamt für Wirtschaft und Ausfuhrkontrolle übernommen, wenn sich das Unternehmen für die [Bundesförderung für Energieberatung für Nichtwohngebäude, Anlagen
Das klingt nach einem sehr hohen bürokratischen Aufwand, bei dem es entspannter wäre, alles selbst zu zahlen. Hast du da zufällig Infos zu, wie lange sowas dauert und wie viel sowas kostet? Vielleicht Erfahrungswerte, ggf. sogar von adesso?

2022-05-09 17:31 UTC, jo2 commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Das ermöglicht fortlaufende Verbesserungen der Effizienz, während eine eventuelle Verschlechterung des Strombedarfs schnell erkannt und verhindert werden kann.
```suggestion
Das ermöglicht fortlaufende Verbesserungen der Effizienz, während eine eventuelle Verschlechterung des Strombedarfs schnell erkannt und behoben werden kann.
```

2022-05-09 17:31 UTC, jo2 commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Energieleistungskennzahlen sind relative Größen, das heißt sie setzen eine absolute Kennzahl zu einer anderen Größe in Beziehung.
```suggestion
Energieleistungskennzahlen sind relative Größen, das heißt, sie setzen eine absolute Kennzahl zu einer anderen Größe in Beziehung.
```

2022-05-09 20:47 UTC, c0c0bird commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Für kleine und mittlere Unternehmen kann ein freiwilliges Energieaudit nach der europäischen Norm EN 16247 sinnvoll sein, denn es hilft Kosten zu senken und das Zertifikat beweist Umweltbewusstsein.
Ist geändert.

2022-05-09 21:38 UTC, c0c0bird commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Bis zu 80% der Kosten werden jedoch vom Bundesamt für Wirtschaft und Ausfuhrkontrolle übernommen, wenn sich das Unternehmen für die [Bundesförderung für Energieberatung für Nichtwohngebäude, Anlagen
Sorry, in echt hab ich das noch nie gemacht. Wenn die eigene Rechtsabteilung die Fomrulare ausfüllt, geht es bestimmt. ;)

2022-05-09 21:42 UTC, c0c0bird commented
Wie das bei adesso gemacht wird, möchte ich nicht so direkt als Vorbild aufführen, weil es im Intranet danach aussieht, als wenn unsere Zertifikate nicht ganz komplett sind. Wir sind nach ISO 9001 und ISO 14001 zertifiziert, aber nicht nach EMAS.

Um zu erklären, dass das rechtlich kein Energiemanagement ersetzt, hab ich einen Schlussteil angehängt. Falls jemand vom Qualitätsmanagement das liest, wird der Wink mit dem Zaunpfahl schon ankommen. Für alle anderen liest es sich hoffentlich neutral.

Alle anderen Änderungswünsche sind natürlich auch übernommen.

2022-05-10 14:20 UTC, c0c0bird commented
Die Sache ist jetzt geklärt: adesso macht die Energieaudits, weil es günstiger ist als eine fortlaufendes Management. Wir sind schließlich nicht energieintensiv, sondern nur Mieter von normalen Büroräumen. Damit ist die "Lücke" in den Zertifikaten in Ordnung.
In den Artikel gehört das nicht, denn der handelt von Betrieben die selbst hosten.

2022-05-13 12:54 UTC, jo2 requested changes
Ein paar Kleinigkeiten sind noch drin, grade die Handlungsempfehlungen sind mMn. ein großer Mehrwert.

2022-05-13 12:54 UTC, jo2 commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Andere absolute Kennzahlen über das Unternehmen wären etwa Umsatz, Gebäudefläche, Anzahl an Mitarbeitenden oder die Produktionszahlen.
Dieser Satz ist doppelt drin.

2022-05-13 12:54 UTC, jo2 commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +In vielen Betrieben sind bereits ein ISO 9001 Qualitätsmanagementsystem sowie ein ISO 14001 Umweltmanagementsystem implementiert. Sie können diese und das Ergebnis ihres letzten Energieaudits nutzen,
```suggestion
In vielen Betrieben sind bereits ein ISO-9001-Qualitätsmanagementsystem sowie ein ISO-14001-Umweltmanagementsystem implementiert. Sie können diese und das Ergebnis ihres letzten Energieaudits nutzen, um mit relativ geringem Aufwand ein Energiemanagementsystem nach ISO 50001 aufzubauen.
```
Ist das im zweiten Satz als direkte Anrede gemeint? Dann müsstest du es groß schreiben, sonst passt es so.

2022-05-13 12:54 UTC, jo2 commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Wenn nur ein ISO 14001 Umweltmanagementsystem zur Verfügung steht, liegt die Weiterentwicklung zum EMAS-Umweltmanagementsystem nahe.
```suggestion
Wenn nur ein ISO-14001-Umweltmanagementsystem zur Verfügung steht, liegt die Weiterentwicklung zum EMAS-Umweltmanagementsystem nahe.
```

2022-05-13 12:54 UTC, jo2 commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Als Ersatz für ein regelmäßig wiederholtes Energieaudit zählt nur ein ISO 50001 Energiemanagementsysteme oder ein EMAS Umweltmanagementsystem.
```suggestion
Als Ersatz für ein regelmäßig wiederholtes Energieaudit zählt nur ein ISO-50001-Energiemanagementsysteme oder ein EMAS-Umweltmanagementsystem.
```

2022-05-13 13:07 UTC, c0c0bird commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Andere absolute Kennzahlen über das Unternehmen wären etwa Umsatz, Gebäudefläche, Anzahl an Mitarbeitenden oder die Produktionszahlen.
Danke, einer ist jetzt raus.

2022-05-13 13:07 UTC, c0c0bird commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +In vielen Betrieben sind bereits ein ISO 9001 Qualitätsmanagementsystem sowie ein ISO 14001 Umweltmanagementsystem implementiert. Sie können diese und das Ergebnis ihres letzten Energieaudits nutzen,
Ist geändert.

2022-05-13 13:09 UTC, c0c0bird commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Als Ersatz für ein regelmäßig wiederholtes Energieaudit zählt nur ein ISO 50001 Energiemanagementsysteme oder ein EMAS Umweltmanagementsystem.
Danke, ist korrigiert.

2022-05-13 13:10 UTC, c0c0bird commented on _posts/2022-05-09-Energiemanagement-im-Rechenzentrum.md
> +Wenn nur ein ISO 14001 Umweltmanagementsystem zur Verfügung steht, liegt die Weiterentwicklung zum EMAS-Umweltmanagementsystem nahe.
Ist auch geändert.

2022-05-13 13:11 UTC, c0c0bird commented
Danke, die Kleinigkeiten sind jetzt raus.

2022-05-19 08:37 UTC, jo2 approved these changes

2022-07-06 07:39 UTC, acetous approved these changes

2022-07-06 07:40 UTC, merged