Artikel: Seltene Erden
adessoSE/devblog pull request #241
Opened 2022-05-20 07:47 UTC by c0c0bird

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-05-20 07:57 UTC, MBoegers commented
Probleme mit dem Check siehe: https://github.com/adessoSE/devblog/issues/242

2022-05-31 10:08 UTC, jo2 requested changes
Der Artikel liest sich schon sehr gut. Ein paar Kleinigkeiten habe ich noch angemerkt.

2022-05-31 10:08 UTC, jo2 commented on _posts/2022-05-18-seltene-erden.md
> +Neodym-Eisen-Bor-Magneten wird es zugesetzt, um die Resistenz gegen Entmagnetisierung zu verbessern.
```suggestion
In Neodym-Eisen-Bor-Magneten wird es zugesetzt, um die Resistenz gegen Entmagnetisierung zu verbessern. 
```

2022-05-31 10:08 UTC, jo2 commented on _posts/2022-05-18-seltene-erden.md
> +Desweiteren findet man es, mit Blei legiert, als Abschirmmaterial in Kernreaktoren.
```suggestion
Darüber hinaus findet man es, mit Blei legiert, als Abschirmmaterial in Kernreaktoren.
```

2022-05-31 10:08 UTC, jo2 commented on _posts/2022-05-18-seltene-erden.md
> +Sein Name würdigst die Stadt Stockholm.
```suggestion
Sein Name würdigt die Stadt Stockholm.
```

2022-05-31 10:08 UTC, jo2 commented on _posts/2022-05-18-seltene-erden.md
> +Erbium wirkt als optischer Verstärker, das heißt, sie sind in der Lage, ein Lichtsignal zu verstärken, ohne es zuvor in ein elektrisches Signal zu wandeln.
```suggestion
Erbium wirkt als optischer Verstärker, das heißt, es ist in der Lage, ein Lichtsignal zu verstärken, ohne es zuvor in ein elektrisches Signal zu wandeln.
```

2022-05-31 12:01 UTC, c0c0bird commented
Danke für die Korrekturen! Die Tippfehler sind jetzt raus.

2022-05-31 12:06 UTC, jo2 approved these changes

2022-08-15 12:48 UTC, acetous approved these changes

2022-08-15 12:49 UTC, merged