AWS-Alarme mit Jira zähmen
adessoSE/devblog pull request #243
Opened 2022-05-31 11:53 UTC by kthielma

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-06-02 10:46 UTC, jo2 requested changes
Den Beitrag finde ich sehr interessant und hilfreich! Ein paar Kleinigkeiten habe ich noch angemerkt. Außerdem meine ich mich daran zu erinnern, dass man zur Nutzung der Jira API Project Administrator sein muss. Wenn das der Fall ist, möchtest du da noch in einem Satz drauf eingehen, oder ist die Jira-Einrichtung mit technischem Nutzer usw. außerhalb deines Scopes?

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Eine naive Implementierung könnte wie folgt aussehen (eine korrekte Fehlerbehandlung und die sichere Ermittlung des Filter Patterns wurde für eine bessere Lesbarkeit ausgelassen):
```suggestion
Eine naive Implementierung könnte wie folgt aussehen, eine korrekte Fehlerbehandlung und die sichere Ermittlung des Filter Patterns wurde für eine bessere Lesbarkeit ausgelassen:
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Auch wenn sich mithilfe des oben gezeigten Code-Ausschnitts die entsprechenden Logs zu einem Alarm finden lassen, so gibt es einige Stolpersteine, auf die man spätestens im Produktiveinsatz stößt.
```suggestion
Auch wenn sich mit Hilfe des oben gezeigten Code-Ausschnitts die entsprechenden Logs zu einem Alarm finden lassen, so gibt es einige Stolpersteine, auf die man spätestens im Produktiveinsatz stößt.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Betrachten wir einmal folgenden Fall: Wir suchen nach einem ERROR Log innerhalb der letzten 60 Minuten.
```suggestion
Betrachten wir einmal folgenden Fall: Wir suchen nach einem ERROR-Log innerhalb der letzten 60 Minuten.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Das bedeutet, dass wir die "filterLogEvents"-Anfrage so oft wiederholen müssen, bis in der Antwort kein "Next-Token" enthalten ist, um sicherzustellen, dass wirklich alle Logs des angeforderten Zeitr
```suggestion
Das bedeutet, dass wir die `filterLogEvents`-Anfrage so oft wiederholen müssen, bis in der Antwort kein "Next-Token" enthalten ist, um sicherzustellen, dass wirklich alle Logs des angeforderten Zeitraums durchsucht wurden:
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Wird die Anwendung als AWS Lambda Funktion bereitgestellt, so besitzt sie eine maximale Laufzeit von 15 Minuten.
```suggestion
Wird die Anwendung als AWS-Lambda-Funktion bereitgestellt, so besitzt sie eine maximale Laufzeit von 15 Minuten.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +`https://<AWS-REGION>.console.aws.amazon.com/cloudwatch/deeplink.js?region=<AWS-REGION>#alarmsV2:alarm/<ALARM-NAME>`
```suggestion
```https://<AWS-REGION>.console.aws.amazon.com/cloudwatch/deeplink.js?region=<AWS-REGION>#alarmsV2:alarm/<ALARM-NAME>```
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Diese Information bekommen wir aus dem "Context"-Objekt, welches der Lambda-Funktion beim Auslösen übergeben wird.
```suggestion
Diese Information bekommen wir aus dem `Context`-Objekt, welches der Lambda-Funktion beim Auslösen übergeben wird.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Kommt es zu einer solchen Exception können wir diese einfach fangen und die Suchanfrage nach einer kurzen Pause erneut absetzen.
```suggestion
Kommt es zu einer solchen Exception, können wir diese einfach fangen und die Suchanfrage nach einer kurzen Pause erneut absetzen.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +
Rein interessehalber, entstehen für Anfragen an der Cloudwatch API Kosten? Weißt du, wie hoch das Ratelimit ist?

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Die benötigte Ticketnummer (Pfadvariable "issueIdOrKey") bekommen wir als Rückgabe, nachdem wir das Ticket angelegt haben (siehe [Aus einem SNS Event wird ein Ticket](#aus-einem-sns-event-wird-ein-ti
```suggestion
Die benötigte Ticketnummer (Pfadvariable "issueIdOrKey") bekommen wir als Rückgabe, nachdem wir das Ticket angelegt haben (siehe [Aus einem SNS-Event wird ein Ticket](#aus-einem-sns-event-wird-ein-ticket)).
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Auf dieses SNS Topic horcht eine Lambda-Funktion, welche die Aufgabe übernimmt, auf SNS Events zu reagieren und daraus ein Jira-Ticket zu erzeugen.
```suggestion
Auf dieses SNS Topic horcht eine Lambda-Funktion, welche die Aufgabe übernimmt, auf SNS-Events zu reagieren und daraus ein Jira-Ticket zu erzeugen.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Die Informationen zu dem Zeitraum sowie den Namen der Log-Gruppe erhalten wir direkt aus dem auslösenden SNS Event (siehe [vorheriger Abschnitt](#aus-einem-sns-event-wird-ein-ticket)).
```suggestion
Die Informationen zu dem Zeitraum sowie den Namen der Log-Gruppe erhalten wir direkt aus dem auslösenden SNS-Event (siehe [vorheriger Abschnitt](#aus-einem-sns-event-wird-ein-ticket)).
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Eine nahezu beliebige Anzahl von Alarmen können auf Basis von Metriken oder Protokollfiltern definiert werden und senden ihre Events an ein SNS Topic ("Create Ticket").
```suggestion
Eine nahezu beliebige Anzahl von Alarmen kann auf Basis von Metriken oder Protokollfiltern definiert werden und sendet ihre Events an ein SNS Topic ("Create Ticket").
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Dieses stößt unsere erste Lambda an, die dafür zuständig ist das Ticket im Jira initial anzulegen.
```suggestion
Dieses stößt unsere erste Lambda an, die dafür zuständig ist, das Ticket im Jira initial anzulegen.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Auch, wenn Alarme aus viele Projekte daran angeschlossen werden, skaliert diese Lösung problemlos mit.
```suggestion
Auch wenn Alarme aus viele Projekte daran angeschlossen werden, skaliert diese Lösung problemlos mit.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Zum einen müssen wir betrachten wie viele Alarme bearbeitet werden müssen und wie stark das Team dadurch gebunden wird.
```suggestion
Zum einen müssen wir betrachten, wie viele Alarme bearbeitet werden müssen und wie stark das Team dadurch gebunden wird.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Das kann als JQL folgendermaßen aussehen:
```suggestion
Das kann in JQL folgendermaßen aussehen:
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Dabei ist es möglich die Bedingung der Regel auf Tickets einzuschränken, die seit dem letzten Lauf dazugekommen sind.
```suggestion
Dabei ist es möglich, die Bedingung der Regel auf Tickets einzuschränken, die seit dem letzten Lauf dazugekommen sind.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +**Erinnerung an Tickets, die nach 24 Stunden noch nicht bearbeitet wurden**
Gibt es einen Grund, dass du hier nicht einen Unterabschnitt verwendest?

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +**Projektbezogene Zuweisung von Tickets**
Gibt es einen Grund, dass du hier nicht einen Unterabschnitt verwendest?

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +**Weitere Ideen**
Gibt es einen Grund, dass du hier nicht einen Unterabschnitt verwendest?

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Wird das Projekt gefunden, so können wir den Vorgang einem Entwickler zuweisen und sogar direkt in den Status "In Progress" verschieben.
```suggestion
Wird das Projekt gefunden, so können wir den Vorgang einem bestimmten Teammitglied zuweisen und sogar direkt in den Status "In Progress" verschieben.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Alarme schnell und gründlich zu bearbeiten ist notwendig, aber keineswegs die Lieblingsbeschäftigung vieler Entwickler.
```suggestion
Alarme schnell und gründlich zu bearbeiten ist notwendig, aber keineswegs die Lieblingsbeschäftigung vieler Teammitglieder.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Die Übersichtlichkeit und mögliche Automatisierung in Jira, ist eine in vielen Projekten bereits gerne genutzte Selbstverständlichkeit geworden, die hier um ein neues Anwendungsfeld erweitert wird.
```suggestion
Die Übersichtlichkeit und mögliche Automatisierung in Jira ist eine in vielen Projekten bereits gerne genutzte Selbstverständlichkeit geworden, die hier um ein neues Anwendungsfeld erweitert wird.
```

2022-06-02 10:46 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Die laufenden Kosten sind marginal.
```suggestion
Die laufenden Kosten sind dabei marginal.
```

2022-06-02 12:01 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Es ist möglich, eine Dead Letter Queue (DLQ) für eine Lambda-Funktion zu konfigurieren.
An Ende ist eine DLQ eine normale in SQS konfigurierte Queue, die allerdings nicht automatisch abgefragt wird. Die Events sammeln sich darin und müssen manuell zurückgeschoben werden.

2022-06-02 12:04 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +
@StefanCzubek das kannst du beantworten, oder?

2022-06-02 12:22 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Auf dieses SNS Topic horcht eine Lambda-Funktion, welche die Aufgabe übernimmt, auf SNS Events zu reagieren und daraus ein Jira-Ticket zu erzeugen.
SNS Event würde ich genau wie SNS Topic als Englisch-Englisch betrachten und deswegen nicht mit Bindestrich schreiben.

2022-06-02 12:24 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Sind mehrere AWS Accounts im Einsatz oder ist das Projekt in mehreren Regionen deployed, so sind auch die Felder "AWSAccountId" und "Region" besonders interessant.
AWS Account, gleiches Argument wie SNS Topic oder SNS Event. In meinen Augen Englisch-Englisch, also ohne Bindestrich

2022-06-02 12:24 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Nachdem das SNS Event in einen Ticketnamen und eine aussagekräftige Beschreibung überführt wurde, kann die [Jira-REST-API](https://developer.atlassian.com/server/jira/platform/rest-apis/) (insbesonde
SNS Event würde ich genau wie SNS Topic als Englisch-Englisch betrachten und deswegen nicht mit Bindestrich schreiben.

2022-06-02 12:26 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Die Informationen zu dem Zeitraum sowie den Namen der Log-Gruppe erhalten wir direkt aus dem auslösenden SNS Event (siehe [vorheriger Abschnitt](#aus-einem-sns-event-wird-ein-ticket)).
SNS Event würde ich genau wie SNS Topic als Englisch-Englisch betrachten und deswegen nicht mit Bindestrich schreiben.

2022-06-02 12:26 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Die benötigte Ticketnummer (Pfadvariable "issueIdOrKey") bekommen wir als Rückgabe, nachdem wir das Ticket angelegt haben (siehe [Aus einem SNS Event wird ein Ticket](#aus-einem-sns-event-wird-ein-ti
SNS Event würde ich genau wie SNS Topic als Englisch-Englisch betrachten und deswegen nicht mit Bindestrich schreiben.

2022-06-02 12:29 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Sind mehrere AWS Accounts im Einsatz oder ist das Projekt in mehreren Regionen deployed, so sind auch die Felder "AWSAccountId" und "Region" besonders interessant.
deployt habe ich übernommen

2022-06-02 12:30 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +**Erinnerung an Tickets, die nach 24 Stunden noch nicht bearbeitet wurden**
Die Abschnitte hatten für mich den Charakter einer Aufzählung aber mit relativ wenig Inhalt, bei dem ich dachte, dass es keine Zwischenüberschrift rechtfertigt. Ich habe es trotzdem mal mit reingenommen.

2022-06-02 12:33 UTC, kthielma commented on _data/authors.yml
> +  email: stefan.czubek@adesso.de
Erledigt

2022-06-08 10:16 UTC, kthielma commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +
Kosten wurden im Text ergänzt.

2022-06-08 10:17 UTC, kthielma commented
Zu den Berechtigungen in JIRA für den API-Zugriff wurde die Beschreibung entsprechend erweitert.

2022-06-13 12:58 UTC, jo2 requested changes
3 Kleinigkeiten sind noch drin, danach ist der Artikel von meiner Seite aus fertig.

2022-06-13 12:58 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +### Aus einem SNS-Event wird ein Ticket
```suggestion
### Aus einem SNS Event wird ein Ticket
```

2022-06-13 12:58 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Der Benutzer benötigt für das Anlegen eines Tickets folgende Berechtigungen: `Browse projects` und auf Projekt-Ebene `Create issues`.
```suggestion
Der Benutzer benötigt für das Anlegen eines Tickets folgende Berechtigungen: auf Plattformebene `Browse projects` und auf Projektebene `Create issues`.
```

2022-06-13 12:58 UTC, jo2 commented on _posts/2022-05-31-AWS-Alarme_mit_Jira_zaehmen.md
> +Um einen Kommentar anzulegen, werden folgende Jira-Berechtigungen benötigt: `Browse projects` und auf Projektebene `Add comments`.
```suggestion
Um einen Kommentar anzulegen, werden folgende Jira-Berechtigungen benötigt: auf Plattformebene `Browse projects` und auf Projektebene `Add comments`.
```

2022-06-14 04:25 UTC, kthielma commented
@jo2 , @acetous: Dann mal auf zum Finale. Die Änderungen sind drin. @StefanCzubek tritt in dem Kontext erstmalig als Autor auf, da wird vermutlich noch was für angelegt werden müssen. Ansonsten sollte dem Artikel nichts mehr im Weg stehen.

2022-06-14 07:54 UTC, jo2 approved these changes
Mein "Go" hast du. @acetous ?

2022-07-11 14:08 UTC, merged