Berufsbegleitendes Studieren am ITC mit adesso als Partner
adessoSE/devblog pull request #245
Opened 2022-06-29 18:44 UTC by ccaylak

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [x] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-07-01 13:42 UTC, jo2 requested changes
Einige Sachen habe ich dir noch angemerkt. Achte außerdem bitte in deinem gesamten Text darauf, einheitlich entweder indirekt mit "man" zu schreiben oder die direkte Anrede mit "du" zu verwenden.

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Das ITC ist eine private Hochschule und bietet ein praxisnahe Informatik Studiengänge an.
```suggestion
Das ITC ist eine private Hochschule und bietet praxisnahe Informatikstudiengänge an.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Allerdings fokussiert sich der Erfahrungsbericht auf das Bachelorstudium.
Hier würde ich keinen Absatz machen, du beziehst dich inhaltlich noch auf exakt dasselbe Thema.

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Die ersten vier Semester entsprechen die duale Phase, was in der Woche drei Tage Vorlesungen und zwei Tage Arbeiten im Unternehmen bedeutet.
```suggestion
Die ersten vier Semester sind die duale Phase, was in der Woche drei Tage Vorlesungen und zwei Tage Arbeiten im Unternehmen bedeutet.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Im 3. Semester gibt es Wahlpflicht-Vertiefungsmodule für die genannten Module.
```suggestion
Im 3. Semester gibt es Wahlpflichtvertiefungsmodule zu den genannten Themen.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Die restlichen drei Semester bis zum Abschluss besten aus der berufsbegleitenden Phase.
```suggestion
Die restlichen drei Semester bis zum Abschluss bestehen aus der berufsbegleitenden Phase.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Anders als in der dualen Phase ist der Studierende Vollzeit in seinem Unternehmen beschäftigt und Vorlesungn werden Abends oder am Wochenende besucht.
```suggestion
Anders als in der dualen Phase ist der Studierende Vollzeit in seinem Unternehmen beschäftigt und Vorlesungen werden Abends oder am Wochenende besucht.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Zudem gibt es wieder Wahlpflicht-Vertiefungsmodule zur Auswahl und im letzten Semester des Studiums wird die Bachelorthesis geschrieben.
```suggestion
Zudem stehen weitere Wahlpflichtvertiefungsmodule zur Auswahl.
Im letzten Semester des Studiums wird die Bachelorthesis geschrieben.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Ist das Studium geschafft, ist die Wahrscheinlichkeit sehr hoch, dass du bei deinem Unternehmen in eine Festanstellung wechselst.
```suggestion
Ist das Studium geschafft, ist die Wahrscheinlichkeit sehr hoch, dass man bei seinem Unternehmen in eine Festanstellung wechselt.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Demnach kannst du dir selbst Schwerpunkte setzen und einen Stundenplan erstellen, welche Module du besuchen möchtest und welche nicht.
```suggestion
Demnach kannst du dir selbst Schwerpunkte setzen, einen Stundenplan erstellen, und entscheiden, welche Module du besuchen möchtest und welche nicht.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Für das Kolloqium wird eine Präsentation aus den wichtigsten Erkenntnissen der Arbeit erstellt und in einem 25-minütigen Referat gehalten und anschließend gibt es die Note.
```suggestion
Für das Kolloquium wird eine Präsentation aus den wichtigsten Erkenntnissen der Arbeit erstellt und in einem fünfundzwanzigminütigen Referat vorgestellt.
Anschließend werden die geschriebene Thesis und der gehaltene Vortrag benotet.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Der Bachelor wird dann von der FH-Dortmund verliehen.
```suggestion
Der Bachelortitel wird dann von der FH-Dortmund verliehen.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Besonders die Dozent:innen aus der Industrie hatten es mir angetan, weil diese die neuen und modernen Sachen lehren.
```suggestion
Besonders die Dozierenden aus der Industrie hatten es mir angetan, weil diese die neuen und modernen Themen und Technologien lehren.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Was ich auch gut finde ist, dass man ab der berufsbegleitenden ganz gutes Geld verdient und mit hoher Wahrscheinlichkeit nach dem Studium vom Arbeitgeber übernommen wird.
```suggestion
Was ich auch gut finde ist, dass man ab der berufsbegleitenden Phase ganz gutes Geld verdient und mit hoher Wahrscheinlichkeit nach dem Studium vom Arbeitgeber übernommen wird.
```

2022-07-01 13:42 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Jedoch muss ich zugeben, dass die berufsbegleitende Phase teilweise echt stressig sein kann und da eine gute Planung essenziell ist damit es reibunslos abläuft.
```suggestion
Jedoch muss ich zugeben, dass die berufsbegleitende Phase teilweise echt stressig sein kann und eine gute Planung essenziell ist, damit Studium und Arbeit reibungslos ablaufen.
```

2022-08-18 13:58 UTC, jo2 requested changes
Drei Kleinigkeiten sind noch drin, die ich übersehen hatte.

2022-08-18 13:58 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Durch den Wechsel hat der Studierende eine Vierzigstundenarbeitswoche.
```suggestion
Durch den Wechsel hat man dann eine Vierzigstundenarbeitswoche.
```

2022-08-18 13:58 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Demnach kannst du dir selbst Schwerpunkte setzen, einen Stundenplan erstellen, und entscheiden, welche Module du besuchen möchtest und welche nicht.
```suggestion
Demnach kann man sich selbst Schwerpunkte setzen, einen Stundenplan erstellen, und entscheiden, welche Module man besuchen möchte und welche nicht.
```

2022-08-18 13:58 UTC, jo2 commented on _posts/2022-06-29-Studieren-am-ITC-mit-adesso-2.md
> +Gar keine Module zu besuchen würde ich dringendst abraten, weil der Vorteil der kleinen Stufengrößen gut ist und der monatliche Beitrag für das Studium rausgeschmissenes Geld wäre.
```suggestion
Ich würde dringendst davon abraten, gar keine Module zu besuchen, weil der Vorteil der kleinen Gruppen gut ist und der monatliche Beitrag für das Studium rausgeschmissenes Geld wäre.
```

2022-08-23 13:24 UTC, jo2 submitted a review, later dismissed

2022-10-14 09:49 UTC, acetous approved these changes

2022-10-14 09:55 UTC, acetous approved these changes

2022-10-14 09:55 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-10-14 09:55 UTC, merged