Cloud native applications documentation
adessoSE/devblog pull request #246
Opened 2022-07-13 19:18 UTC by rezanirumand

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-07-15 11:18 UTC, jo2 requested changes
I've commented on some places in your article you have to fix. Also, I'm not a native speaker so please check your text with a grammar tool, for example [Grannar Check](https://www.grammarcheck.net/editor/).

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* **Macro-Architecture**: This document gives a big picture of the Project. All interfaces should follow the design/constraints specified in this document. The sections that are the same as all other
```suggestion
* **Macro-Architecture**: This document gives a big picture of the project. All interfaces should follow the design/constraints specified in this document. The sections that are the same as all other interfaces will be explained in this document to avoid redundant work. If any interface requires a deviation of design, it will be documented in the interface-specific architecture document. This document is based on an arc42 template.
```

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* **Release-Notes**: Is produced for each interface and release
```suggestion
* **Release-Notes**: Provides specific information on each interface and is produced for each release.
```

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* **Developer Guide**: Provides all the required information on how to develop, extend and run the interface. It provides information such as how to run mock systems, configuration, and anything that
```suggestion
* **Developer Guide**: Provides all the required information on how to develop, extend and run the interface. It provides information such as how to run mock systems, configuration, and anything that helps not to rely on the original developer for the tricks to run. Any team member, which has never seen its code, should be able to at least build and run the interface by reading this document.
```

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +**The challenge**: The source code is scattered in lots of git repositories and we need to combine them with the least effort using some kind of engine which we call `doc-centralizer`(see below).
```suggestion
**The challenge**: The source code is scattered in many git repositories and we need to combine them with the least effort using some kind of engine which we call `doc-centralizer`(see below).
```
Do you really intend to mark doc-centralizer as code? This is used for class or method names for example. Maybe you want to use quotes or double quotes.

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +![alt text](/assets/images/posts/cloud-native-applications-documentation/centrazlized-documentation-flow.png "Building Documentation with doc-centralizer")
```suggestion
![Building Documentation with doc-centralizer](/assets/images/posts/cloud-native-applications-documentation/centrazlized-documentation-flow.png)
```

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +[Antora][6] is a multi-repository documentation site generator for tech writers who writing in `AsciiDoc`.
```suggestion
[Antora][6] is a multi-repository documentation site generator for tech writers who are writing text or documentation in `AsciiDoc`. 
```

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +Our documentation is built based on various components. For example, Interface-Architecture, Interface Operation Manual etc.
This second part is not a complete sentence, please fix this.

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +Each of these components could have various versions. For example, different releases branches.
This second part is not a complete sentence, please fix this.

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +![alt text](/assets/images/posts/cloud-native-applications-documentation/camel-documentation-example.png "Camel Framework Documentation")
```suggestion
![Camel Framework Documentation](/assets/images/posts/cloud-native-applications-documentation/camel-documentation-example.png)
```

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +Also, We can choose a specific version of a component. For example, we can click on version `2.x` under `Camel components` to see the documentation. This is especially useful for readers to fast-swit
```suggestion
Also, we can choose a specific version of a component. For example, we can click on version `2.x` under `Camel components` to see the documentation. This is especially useful for readers to fast-switch and compare various versions.
```

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +*__Note__: discussing Antora is not the focus of this article and can be best learned by its website.*
```suggestion
*__Note__: discussing Antora is not the focus of this article and the usage of this framework can be best learned on its website.*
```

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +We use Anotra in a pipeline to fetch all the documentation and combine them into a static website. Once we have our website we can serve it using any webserver anywhere!
```suggestion
We use Anotra in a pipeline to fetch all the documentation and combine them into a static website. Once we have our website, we can serve it using any webserver anywhere!
```

2022-07-15 11:18 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +The build and delivery process is automated and uses something like the below to build a container image:
```suggestion
The build and delivery process is automated and uses something like the below dockerfile to build a container image:
```

2022-07-19 19:33 UTC, rezanirumand commented on _data/authors.yml
> +  bio: "Reza Nirumand is a Senior Software Engineer by adesso located in Dortmund. He is involved in various projects in the Banking industry for designing and delivery of Cloud-Native applications."
done

2022-07-19 19:34 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +Last year, we started migrating our single-repo, multi-module code-base (160+ Backend Interfaces) from the old OSGI Framework to a new multi-repo Cloud-Native architecture with the following characte
done

2022-07-19 19:36 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* Interfaces are delivered as a container image for an orchestration platform to a container registry along with their matching helm deployment manifests which are delivered to a helm registry
done

2022-07-19 19:36 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +# Old School Documentation
done

2022-07-19 19:37 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +We used to have various documents based on Microsoft word and some diagrams based on the application Enterprise Architect.
done

2022-07-19 19:39 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* __Release Notes__: Provided the User stories implemented and also configuration updates mostly useful for the Operation team. This document was saved as ms-word and versioned on the git repo along
done

2022-07-19 19:41 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +Since we were working in an agile team, the documentation artifacts were tagged with the application version and saved as a PDF and delivered to the customer via E-mail or some file-sharing platform.
Email is corrected by file-sharing would be the correct one

2022-07-19 19:43 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* Copping configuration would also take unknown or special characters.
done

2022-07-19 19:43 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +# Migration Project
done

2022-07-19 19:44 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +With the new migration project, we started to migrate our complete source code to new cloud-native architecture and one of the important goals of our migration was __zero-to-hero documentation__ whic
done

2022-07-19 19:44 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* Allows faster and easier onboarding of new team members
done

2022-07-19 19:46 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* Better communication with our stakeholders such as Product owners, Solution architects, Operation teams, and interface consumers.
done

2022-07-19 19:46 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +In the following section, we talk about our solution and how we achieved the above-mentioned goal.
done

2022-07-19 19:47 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +## Our Solution
done

2022-07-19 19:47 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +The very first step we took to achieve our documentation goal, was to migrate from binary formats to text-based formats which solve the problem of reviewing and diff-checks.
done

2022-07-19 19:48 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* It can be used by any text editor. We use [Asciidoctor][2], [Visual Studio Code][3]
done

2022-07-19 19:48 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* Since it is text-based, can be versioned on any version control system
done

2022-07-19 19:49 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* Most importantly, allows concentrating on writing!
done

2022-07-19 19:50 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* There are plenty of tools to draw diagrams as text such as [plantuml][4]
done

2022-07-19 20:25 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +#### Antora
fixed

2022-07-19 20:28 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* **Macro-Architecture**: This document gives a big picture of the Project. All interfaces should follow the design/constraints specified in this document. The sections that are the same as all other
updated and added reference

2022-07-19 20:29 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* **Release-Notes**: Is produced for each interface and release
done

2022-07-19 20:29 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* **Developer Guide**: Provides all the required information on how to develop, extend and run the interface. It provides information such as how to run mock systems, configuration, and anything that
done

2022-07-19 20:30 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +**The challenge**: The source code is scattered in lots of git repositories and we need to combine them with the least effort using some kind of engine which we call `doc-centralizer`(see below).
ok will correct doc-centralizer formatting.

2022-07-19 20:32 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +[Antora][6] is a multi-repository documentation site generator for tech writers who writing in `AsciiDoc`.
done

2022-07-19 20:33 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +Our documentation is built based on various components. For example, Interface-Architecture, Interface Operation Manual etc.
rewrited

2022-07-19 20:35 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +Each of these components could have various versions. For example, different releases branches.
done

2022-07-19 20:35 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +![alt text](/assets/images/posts/cloud-native-applications-documentation/camel-documentation-example.png "Camel Framework Documentation")
done

2022-07-19 20:35 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +Also, We can choose a specific version of a component. For example, we can click on version `2.x` under `Camel components` to see the documentation. This is especially useful for readers to fast-swit
done

2022-07-19 20:36 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +We use Anotra in a pipeline to fetch all the documentation and combine them into a static website. Once we have our website we can serve it using any webserver anywhere!
done

2022-07-19 20:36 UTC, rezanirumand commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +The build and delivery process is automated and uses something like the below to build a container image:
done

2022-07-20 06:45 UTC, jo2 requested changes
Ein paar Sachen habe ich noch angemerkt, das meiste davon hatte ich im ersten Durchlauf übersehen.

2022-07-20 06:45 UTC, jo2 commented on _data/authors.yml
> +  bio: "Reza Nirumand is a Senior Software Engineer at adesso located in Dortmund. He is involved in various projects in the Banking industry and he is responsible for the designing and delivering of
```suggestion
  bio: "Reza Nirumand is a Senior Software Engineer at adesso located in Dortmund. He is involved in various projects in the Banking industry and he is responsible for the designing and delivering of cloud-native applications."
```

2022-07-20 06:45 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* __Software Architecture__: Described the overall system architecture as well as all interfaces(OSGI Bundles) specific architecture. The document was based on Microsoft Word and saved on the git rep
```suggestion
* __Software Architecture__: Described the overall system architecture as well as all interfaces(OSGI Bundles) specific architecture. The document was based on Microsoft Word and saved on the git repository along with the source code.
```

2022-07-20 06:45 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* __Operation Manual__: Focused on the operational aspect of our applications and provided some introduction to installing the platform (Red Hat Fuse 6) and some of the main operations. This document
```suggestion
* __Operation Manual__: Focused on the operational aspect of our applications and provided some introduction to installing the platform (Red Hat Fuse 6) and some of the main operations. This document was based on Microsoft Word and saved on the git repository along with the source code.
```

2022-07-20 06:45 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* __Release Notes__: Provided the user stories implemented in the application and also the configuration updates mostly implemented by the operation team. This document was saved as a Microsoft Word
```suggestion
* __Release Notes__: Provided the user stories implemented in the application and also the configuration updates mostly implemented by the operation team. This document was saved as a Microsoft Word file and versioned on the git repository along with the source code.
```

2022-07-20 06:45 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* It is easy to learn
```suggestion
* It is easy to learn.
```

2022-07-20 06:45 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +* **Developer Guide**: Provides all the required information on how to develop, extend and run the interface. It provides information such as how to run mock systems, configuration, and anything that
```suggestion
* **Developer Guide**: Provides all the required information on how to develop, extend and run the interface. It provides information such as how to run mock systems, configuration, and anything that helps not to rely on the original developer for the tricks to run. Any team member, that has never seen its code, should be able to at least build and run the interface by reading this document.
```

2022-07-20 06:45 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +**The challenge**: The source code is scattered in many of git repositories and we need to combine them with the least effort using some kind of engine which we call _doc-centralizer_ (see below).
```suggestion
**The challenge**: The source code is scattered in many git repositories and we need to combine them with the least effort using some kind of engine which we call _doc-centralizer_ (see below).
```

2022-07-20 06:45 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +!["Building Documentation with doc-centralizer"](/assets/images/posts/cloud-native-applications-documentation/centrazlized-documentation-flow.png)
```suggestion
![Building Documentation with doc-centralizer](/assets/images/posts/cloud-native-applications-documentation/centrazlized-documentation-flow.png)
```

2022-07-20 06:45 UTC, jo2 commented on _posts/2022-06-27-cloud-native-applications-documentation.md
> +!["Camel Framework Documentation"](/assets/images/posts/cloud-native-applications-documentation/camel-documentation-example.png)
```suggestion
![Camel Framework Documentation](/assets/images/posts/cloud-native-applications-documentation/camel-documentation-example.png)
```

2022-07-20 13:57 UTC, jo2 approved these changes

2022-08-15 15:18 UTC, acetous commented
Hier ist noch ein bisschen Formatierung bei den Aufzählungen kaputt. @jo2 Schaust Du da einmal drauf?

2022-08-16 06:23 UTC, jo2 commented
@acetous ist behoben, das waren die Zeilenumbrüche in den Aufzählungen. Achte ich in Zukunft drauf.

2022-09-05 06:27 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-05 06:53 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-05 06:54 UTC, acetous approved these changes

2022-09-05 06:54 UTC, merged