Jewelj records sealed class
adessoSE/devblog pull request #247
Opened 2022-07-14 09:54 UTC by MBoegers

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-07-14 10:25 UTC, MBoegers commented
Es sieht so aus als würde der Blogpost Checker einen alten Commit nehmen. Deswegen kann ich das Preview und den blogpost-checker Punkt nicht abharken.

2022-07-15 12:13 UTC, jo2 requested changes
Der Artikel ist ganz interessant, vor allem, wo ich mich jetzt auch ein wenig mit den aktuelleren Java-Versionen beschäftigt habe. Ich bin mal gespannt, was da noch kommt. Ein paar Sachen habe ich noch angemerkt.

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Alle generierten Methoden können überschrieben werden und beliebige weitere Methoden definiert werden.
```suggestion
Alle generierten Methoden können überschrieben und beliebige weitere Methoden definiert werden.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Durch ihre Immutability und Transparenz eigen sich Records gut um Value Objekt aus dem [Domain Driven
```suggestion
Durch ihre Immutability und Transparenz eignen sich Records gut, um Value Objects aus dem [Domain Driven
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Viele berühmte Java Bibliotheken wie JSON-B arbeiten darauf hin Records so schnell wie möglich zu unterstützten um
```suggestion
Viele berühmte Java-Bibliotheken wie JSON-B arbeiten darauf hin, Records so schnell wie möglich zu unterstützten, um
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +und die Nutzung von Records zu ermöglichen.
```suggestion
die Nutzung von Records zu ermöglichen.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Mit [JEP 409](https://openjdk.java.net/jeps/409) hat Projekt Amber Sealed Classes in Java 17 eingeführt.
```suggestion
Mit [JEP 409](https://openjdk.java.net/jeps/409) hat Project Amber Sealed Classes in Java 17 eingeführt.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Das Konzept von `sealed` ist auch schon in anderen objektorientierten Sprache integriert und dient dazu während der Entwicklung mehr Kontrolle über die Vererbung zu geben.
```suggestion
Das Konzept von `sealed` ist auch schon in anderen objektorientierten Sprachen integriert und dient dazu, während der Entwicklung mehr Kontrolle über die Vererbung zu geben.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +War eine Klasse nicht als `final` markiert konnte noch mit der Sichtbarkeit gearbeitet werden um zu beeinflussen wie
```suggestion
War eine Klasse nicht als `final` markiert, konnte noch mit der Sichtbarkeit gearbeitet werden, um zu beeinflussen wie
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Mit der Semantik hinter Sealed Classes besteht nun die Möglichkeit eindeutig klarzustellen wie die
```suggestion
Mit der Semantik hinter Sealed Classes besteht nun die Möglichkeit, eindeutig klarzustellen, wie die
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Abstufung mit `sealed`
```suggestion
Abstufung mit `sealed`.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Die so definiert Interface Shape ist nun verschlossen und es muss zum Zeitpunkt des Kompilierens klar sein welche
```suggestion
Das so definierte Interface Shape ist nun verschlossen und es muss zum Zeitpunkt des Kompilierens klar sein, welche
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Implementation es gibt.
```suggestion
Implementationen es gibt.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Es gibt zwei Möglichkeiten zu erlauben ein verschlossenes Interface bzw. Klasse zu erweitern.
```suggestion
Es gibt zwei Möglichkeiten, zu erlauben, ein verschlossenes Interface bzw. Klasse zu erweitern.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> ++ erweiternden Klassen befinden sich in derselben Compile-unit, wie im Beispiel `Corndered` und `Weirdo`
```suggestion
+ Die erweiternden Klassen befinden sich in derselben Compile-Unit wie im Beispiel `Corndered` und `Weirdo`.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> ++ erweiternden Klassen werden explizit hinter dem `permits` Keyword angegeben, wie im Beispiel von `Rectangle` und
```suggestion
+ Die erweiternden Klassen werden explizit hinter dem `permits` Keyword angegeben wie im Beispiel von `Rectangle` und
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +`Square`
```suggestion
`Square`.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Mit Propagation ist gemeint, dass in jede Klasse bzw. jedem Interface welches eine Sealed Class erweitert angegeben
```suggestion
Mit Propagation ist gemeint, dass in jede Klasse bzw. jedem Interface, welches eine Sealed Class erweitert, angegeben
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +werden muss wie die Hierarchie sich fortsetzt.
```suggestion
werden muss, wie die Hierarchie sich fortsetzt.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> ++ _die Hierarchy endet hier_ dabei wird die Klasse als `final` markiert, wie im Beispiel die Klasse `Reactangle`
```suggestion
+ _die Hierarchy endet hier_ dabei wird die Klasse als `final` markiert wie im Beispiel die Klasse `Reactangle`
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> ++ _die Hierarchy geht verschlossen weiter_ die Klasse wird als sealed markiert und muss ebenfalls Aussagen welche
```suggestion
+ _die Hierarchy geht verschlossen weiter_ die Klasse wird als sealed markiert und muss ebenfalls Aussagen, welche
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Es ist nun wieder erlaubt beliebige Erweiterungen zu implementieren
```suggestion
Es ist nun wieder erlaubt, beliebige Erweiterungen zu implementieren
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Einen erstmal offensichtlichen Fall stellt das Record `Square` da.
```suggestion
Einen erstmal offensichtlichen Fall stellt das Record `Square` dar.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Hier ist keine explizite Angabe der Propagation notwendig, denn wie Records sind nach [JEP 459](#jep-459-records)
Der Satz passt grammatikalisch nicht, guck da bitte nochmal drüber.

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Record und Sealed Classes bieten uns neue Möglichkeiten an unsere Domainmodell zu implementieren.
```suggestion
Record und Sealed Classes bieten uns neue Möglichkeiten an, unsere Domänenmodelle zu implementieren.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Ihr wares Potenzial zeigen Sie aber erst durch die Einführung von Pattern Matching in Java.
```suggestion
Ihr wares Potenzial zeigen Record und Sealed Classes aber erst durch die Einführung von Pattern Matching in Java.
```

2022-07-15 12:13 UTC, jo2 commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Dieses dritte Thema von Projekt Amber werde ich in dem nächsten Beitrag dieser Reihe behandel.
```suggestion
Dieses dritte Thema von Project Amber werde ich in dem nächsten Beitrag dieser Reihe behandeln.
```

2022-07-15 14:16 UTC, MBoegers commented on _posts/2022-07-13-schmuckes_java_records_und_sealed_classes.md
> +Hier ist keine explizite Angabe der Propagation notwendig, denn wie Records sind nach [JEP 459](#jep-459-records)
Umformuliert

2022-07-19 06:39 UTC, jo2 approved these changes

2022-08-18 14:25 UTC, acetous approved these changes

2022-08-18 14:27 UTC, merged