Komplex vernetzte Logistikdaten persistieren - Von Objekten in die Gr…
adessoSE/devblog pull request #250
Opened 2022-07-26 19:49 UTC by x1285

…aphdatenbank per OGM

Post inkl. Bilder hinzugefügt
Author Info inkl. avatar hinzugefügt
PR template ausgefüllt

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-07-27 18:08 UTC, x1285 commented
@jo2 Ready for Review :)

2022-07-29 15:41 UTC, jo2 requested changes
Das Thema ist ganz interessant, der Artikel mMn. aber noch ein bisschen dünn. Grade etwas komplexere Beispiele oder Details dazu, wie ihr bestimmte Probleme gelöst habt, wären interessant. Hilfreich wäre auch ein Link zu GitHub o.ä., damit man als Leser das Framework auch ausprobieren kann.

2022-07-29 15:41 UTC, jo2 commented on _data/authors.yml
> +  bio: "Maik ist Senior Software Engineer bei adesso in Essen. Hier entwickelt er unter anderem Java Anwendungen. Mit Leidenschaft erarbeitet er Lösungen für komplexe Probleme, die Benutzer sowie Ent
```suggestion
  bio: "Maik ist Senior Software Engineer bei adesso in Essen. Hier entwickelt er unter anderem Java-Anwendungen. Mit Leidenschaft erarbeitet er Lösungen für komplexe Probleme, die Personen im Alltag unterstützt."
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Neptune unterstützt Gremlin als Abfragesprache, die von Apache als Teil des TinkerPop Frameworks zur Verfügung gestellt wird.
```suggestion
Neptune unterstützt Gremlin als Abfragesprache, die von Apache als Teil des TinkerPop-Frameworks zur Verfügung gestellt wird.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Für relationale Datenbanken bietet sich bei Java Anwendungen als Schnittstelle die Jakarta Persistence API (JPA; ehemals Java Persistence API) und als implementierendes ORM-Framework (object-relation
```suggestion
Für relationale Datenbanken bietet sich bei Java-Anwendungen als Schnittstelle die Jakarta Persistence API (JPA; ehemals Java Persistence API) und als implementierendes ORM-Framework (object-relational mapping) beispielsweise Hibernate an.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Für die neu entwickelte Logistik Anwendung war das Ziel ein Tool nutzen zu können, das automatisiert Gremlin Queries erzeugt, um Daten in der Graphdatenbank persistieren zu können, sowie diese durch
```suggestion
Für die neu entwickelte Logistikanwendung war das Ziel, ein Tool nutzen zu können, das automatisiert Gremlin Queries erzeugt, um Daten in der Graphdatenbank persistieren zu können, sowie diese durch definierte Abfragen wieder zur Laufzeit in die Anwendung zu laden.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Dahingegen existiert für Graphdatenbanken derzeit keine offizielle Java API.
Was ist bspw. [hiermit](https://github.com/awslabs/amazon-neptune-tools/tree/master/neptune-gremlin-client)?

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Nachfolgend wird das entwickelte OGM-Framework (object-graph mapping) zusammengefasst und gehen auf Herausforderungen ein, die bei stark vernetzten Daten auftreten.
```suggestion
Nachfolgend fassen wir das entwickelte OGM-Framework (object-graph mapping) zusammen und wir gehen auf Herausforderungen ein, die bei stark vernetzten Daten auftreten.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Um Java Objekte in der Graphdatenbank zu persistieren, ist zunächst ein System notwendig, welches definiert, wie die Daten als Graph abzubilden sind.
```suggestion
Um Java-Objekte in der Graphdatenbank zu persistieren, ist zunächst ein System notwendig, welches definiert, wie die Daten als Graph abzubilden sind.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Diese Schnittstelle, die zwischen dem Datenmodell der Anwendung und dem entwickelten Persistenz-Framework agiert, wurde unter anderem als Annotation-API umgesetzt, wie Entwickler sie bereits von JPA
```suggestion
Diese Schnittstelle, die zwischen dem Datenmodell der Anwendung und dem entwickelten Persistenzframework agiert, wurde unter anderem als Annotation API umgesetzt, wie sie bereits von JPA bekannt sind.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Um definieren zu können, ob Klassen die in der Graphdatenbank als Knoten oder Kanten zu modellieren sind, werden zusätzlich folgende abstrakte Klassen angeboten:
```suggestion
Um definieren zu können, ob Klassen in der Graphdatenbank als Knoten oder Kanten zu modellieren sind, werden zusätzlich folgende abstrakte Klassen angeboten:
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +- Edge
```suggestion
* Vertex
* Edge
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +In den implementierenden Java Klassen kann über die zuvor genannte Annotation-API definiert werden, wie einzelne Klassenvariablen in der Graphdatenbank darzustellen sind:
```suggestion
In den implementierenden Java-Klassen kann über die zuvor genannte Annotation API definiert werden, wie einzelne Klassenvariablen in der Graphdatenbank darzustellen sind:
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +| `@Property` | Die Klassenvariable ist als Eigenschaft des Elements darzustellen.<br>Der Variablentyp muss ein direkt unterstützter Datentyp* sein.                                                |
Ist der Stern hier der Auslöser der Fußnote? Die wird unten als 1 Dargestellt. Kannst du das so abändern, dass an beiden Stellen das gleiche Symbol verwendet wird?

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +| `@ViaEdge`  | Die Klassenvariable ist als Knoten über eine Kante darzustellen.<br>Der Variablentyp muss vom Typ `Vertex`, `Collection<? extends Vertex>` oder ein unterstützer Datentyp[^1] sein. |
```suggestion
| `@ViaEdge`  | Die Klassenvariable ist als Knoten über eine Kante darzustellen.<br>Der Variablentyp muss vom Typ `Vertex`, `Collection<? extends Vertex>` oder einem unterstützer Datentyp[^1] sein. |
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +[^1]: Direkt unterstützte Datentypen sind alle primitiven Java Datentypen und Strings.
```suggestion
[^1]: Direkt unterstützte Datentypen sind alle primitiven Java-Datentypen und Strings.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Um auch komplexere Typen, wie beispielsweise `LocalDate` als Datenbank Property modellieren zu können, wird durch das Attribut `mapToJson` und mithilfe des Jackson Projekts ein Mapping zu JSON ermögl
```suggestion
Um auch komplexere Typen wie beispielsweise `LocalDate` als Datenbank Property modellieren zu können, wird durch das Attribut `mapToJson` und mithilfe des Jackson-Projekts ein Mapping zu JSON ermöglicht, sofern dies notwendig ist und Gremlin oder die Datenbank den Datentyp nicht direkt unterstützen.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +So kann etwa in unserem Beispiel die Kanten von bekannten Personen verändert werden:
```suggestion
So können etwa in unserem Beispiel die Kanten von bekannten Personen verändert werden:
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Mit dem Framework können so Java Objekte vom Typ Vertex in einer Graphdatenbank gespeichert werden.
```suggestion
Mit dem Framework können so Java-Objekte vom Typ Vertex in einer Graphdatenbank gespeichert werden.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Dazu wird vom Framework zur Laufzeit ein Klassenmodell der zu persistierenden Knoten- und Kanten-Objekte erzeugt.
```suggestion
Dazu wird vom Framework zur Laufzeit ein Klassenmodell der zu persistierenden Knoten- und Kantenobjekte erzeugt.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Dieses Modell wird daraufhin von unserem Query Builder verwendet, um das Gremlin-Statement zu erzeugen, welches letztendlich genutzt wird, um die komplex verstrickte Datenmenge in der Datenbank ableg
```suggestion
Dieses Modell wird daraufhin von unserem Query Builder verwendet, um das Gremlin-Statement zu erzeugen, welches letztendlich dazu genutzt wird, um die komplex verstrickte Datenmenge in der Datenbank ablegen zu können.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Nach dieser Relation wird jedoch nicht wieder mit Jana fortgefahren, da man sich sonst in eine Schleife begibt.
Woher erkennt das Framework denn, dass die Beziehung von Florian zu Jana dann den kreis bildet? Das ist ja der eigentlich interessante Punkt beim erkennen von Kreisen.

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Rückblickend konnten wir innerhalb kürzester Zeit ein robustes und effizientes OGM-Framework entwickeln, das bei den Entwicklern dank bekannter Konzepte schnell hohe Akzeptanz fand und positives Feed
```suggestion
Rückblickend konnten wir innerhalb kürzester Zeit ein robustes und effizientes OGM-Framework entwickeln, das im Entwicklungsteam dank bekannter Konzepte schnell hohe Akzeptanz fand und positives Feedback brachte.
```

2022-07-29 15:41 UTC, jo2 commented on _posts/2022-07-27-Komplex-vernetzte-Logistikdaten-persistieren.md
> +Graphdatenbanken stellen gerade für Datenstrukturen mit vielen Beziehungen untereinander eine clevere Möglichkeit dar, um aufwendige Join-Table Strukturen zu vermeiden und wie in unserem Beispiel züg
```suggestion
Graphdatenbanken stellen gerade für Datenstrukturen mit vielen Beziehungen untereinander eine clevere Möglichkeit dar, um aufwendige Join-Table-Strukturen zu vermeiden und, wie in unserem Beispiel, zügig Lösungen zu realisieren.
```

2023-01-20 12:03 UTC, jo2 commented
@x1285 wie ist hier der Stand?

2023-02-01 08:39 UTC, acetous commented
Ich schließe den PR in Rücksprache mit @x1285 
Er macht einen neuen PR auf, sobald der Blogpost überarbeitet ist.

2023-02-01 08:39 UTC, closed without merging