Künstliche Kreativität - Kann eine KI kreativ sein?
adessoSE/devblog pull request #253
Opened 2022-08-27 13:01 UTC by hasslinger

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-09-02 15:10 UTC, jo2 requested changes
Ein paar Kleinigkeiten habe ich dir noch angemerkt. Grundsätzlich ist das ein sehr interessanter Artikel. Mich würde besonders noch interessieren, wie es mit dem Urheberrecht aussieht. Theoretisch ist, bspw. im Fall von Dall-E , ja die KI der Urheber. Da eine KI aber nicht als juristische Person auftreten kann, stellt sich mir hier die Frage, wie das rechtlich aussieht.

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Dies unterstreicht warum es für eine KI so schwierig ist Kunst auf dem menschlichen Niveau zu erzeugen.
```suggestion
Dies unterstreicht, warum es für eine KI so schwierig ist, Kunst auf dem menschlichen Niveau zu erzeugen.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Viele der angesprochenen Grenzen einer kreativen KI, lassen sich auf die Frage danach zurückführen, wie eine Maschine selbstständig Kreativität messen bzw. evaluieren kann.
```suggestion
Viele der angesprochenen Grenzen einer kreativen KI lassen sich auf die Frage danach zurückführen, wie eine Maschine selbstständig Kreativität messen bzw. evaluieren kann.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Einerseits scheint eine ganze Reihe von Forschungsarbeiten dem Einsatz von KI als autarke Generatoren gewidmet zu sein, die versuchen mit wenig Input des Benutzers, ganze Kunstwerke zu erzeugen.
```suggestion
Einerseits scheint eine ganze Reihe von Forschungsarbeiten dem Einsatz von KI als autarke Generatoren gewidmet zu sein, die versuchen, mit wenig Input des Benutzers ganze Kunstwerke zu erzeugen.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Andererseits werden KI-Systeme auch als Kreativwerkzeuge betrachtet, die es uns ermöglichen unsere eigene Kreativität zu steigern.
```suggestion
Andererseits werden KI-Systeme auch als Kreativwerkzeuge betrachtet, die es uns ermöglichen, unsere eigene Kreativität zu steigern.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +In der Hinsicht wird KI verglichen mit einer Art weiterentwickelter Pinsel für einen Maler.
```suggestion
In der Hinsicht wird KI mit einer Art weiterentwickeltem Pinsel für einen Maler verglichen.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Eine KI kann nicht dieselbe Lebenserfahrung sammeln oder die gleichen Emotionen haben.
```suggestion
Eine KI kann nicht dieselbe Lebenserfahrung sammeln oder die gleichen Emotionen haben, wie ein Mensch.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +In der Kombination einer Partnerschaft mit dem Menschen, kann KI jedoch diejenigen des Künstlers wirkungsvoll zum Ausdruck bringen.
```suggestion
In der Kombination einer Partnerschaft mit dem Menschen kann KI jedoch diejenigen des Künstlers wirkungsvoll zum Ausdruck bringen.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Sie hat das Potenzial noch viel mehr als ein einfaches Werkzeug zu sein und könnte den Kreativsektor gänzlich revolutionieren.
```suggestion
Sie hat das Potenzial, noch viel mehr als ein einfaches Werkzeug zu sein, und könnte den Kreativsektor gänzlich revolutionieren.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Mit KI hat man ein weiterentwickeltes Werkzeug welches erfolgreich eingesetzt werden kann, um dem Künstler Aufgaben abzunehmen, die zeitaufwendig sind.
```suggestion
Mit KI hat man ein weiterentwickeltes Werkzeug welches erfolgreich eingesetzt werden kann, um dem Künstler Aufgaben abzunehmen, die zeitaufwändig sind.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Oder auch in den Arbeitsläufen der Postproduktion wird KI verstärkt zum Einsatz kommen, unter anderem in Form von verbesserten Tools für die Rauschunterdrückung, Kolorierung, Segmentierung, Rendering
```suggestion
Oder auch in den Arbeitsläufen der Postproduktion wird KI verstärkt zum Einsatz kommen, unter anderem in Form von verbesserten Tools für die Rauschunterdrückung, die Kolorierung, die Segmentierung, das Rendering und das Tracking.
```

2022-09-02 15:10 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Eine Umfrage von Adobe (2018) zeigte, dass drei Viertel der befragten Künstler sich vorstellen können KI als unterstützendes Werkzeug zu nutzen.
```suggestion
Eine Umfrage von Adobe (2018) zeigte, dass drei Viertel der befragten Künstler sich vorstellen können, KI als unterstützendes Werkzeug zu nutzen.
```

2022-09-05 06:50 UTC, hasslinger commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +<div align='center'>
Ich habe das gemacht, damit ich die Größe der Bilder anpassen und sie zentrieren kann. Ich wusste jetzt nicht wie das in Markdown geht, aber setze das gerne um, falls du einen Vorschlag hast? :)

2022-09-05 08:12 UTC, hasslinger commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Wo sie sich aber noch schwer tun ist z.B. bei sogenannter transformationaler Kreativität (das bedeutet völlig neuartige und den bisherigen Konzeptraum gänzlich verlassene Ideen).
Dall-E bewegt sich eher noch im Bereich der "explorativen Kreativität". Das geht schon über einfache "kombinatorische Kreativität" hinaus, denn es schafft noch nie dar gewesenes. Allerdings bewegt es sich noch in einem bestehenden Konzeptraum. 
"Während die Exploration einer neuen Dimension innerhalb eines Konzeptraums bereits durch relativ
kleine Veränderungen auf eher oberflächlicher Ebene erreicht werden kann, ist transformationale 
Kreativität nur durch fundamentale und radikale Änderungen in einem Konzeptraum zu erreichen. Hierbei geht es eher um eine völlig neuartige Idee, die bisherige Denkmuster
fundamental ändert und zu einem neuen Stil oder sogar einem neuen Konzeptraum führt"

Es gibt eine KI namens DeepDream, wo man argumentieren könnte, dass sie teilweise transformationale Kreativität kann. Ich hatte die jetzt raus gelassen weil ich dachte dass mein Artikel jetzt schon viel zu lang ist. Wie schätzt du das ein? Kann/Sollte ich das noch mit aufnehmen? Wie lang darf so ein Artikel sein?

2022-09-05 08:21 UTC, hasslinger commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Außerdem ist zu erwähnen, dass KI zwar wertvolle Kunstwerke erzeugen kann, teilweise aber auch solche resultieren, die entweder nicht neuartig sind, oder vom Menschen als sinnlos angesehen werden.
Ich habe hierzu noch zwei Sätze ergänzt. Greift das das auf was du meinst?

2022-09-05 08:26 UTC, hasslinger commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Konträr dazu steht allerdings das Ziel im kreativen Prozess novelty zu generieren, wenn solch ungewöhnlichen Datenpunkten geringe Gewichtung zugeschrieben wird.
Dann könnte es darauf hinaus laufen, dass man nur noch völlig zufällige Ergebnisse erhält, weil die KI dann nicht lernt wie Kunst grundlegend aussehen sollte. Hier zeigt sich wieder die Schwierigkeit einer KI sowohl novelty als auch value zu erzeugen. Ich habe dazu noch einen Satz ergänzt.

2022-09-05 08:31 UTC, hasslinger commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Mit KI hat man ein weiterentwickeltes Werkzeug welches erfolgreich eingesetzt werden kann, um dem Künstler Aufgaben abzunehmen, die zeitaufwendig sind.
Ist das tatsächlich die richtige Schreibweise? Wenn ich das richtig sehe empfiehlt der Duden "zeitaufwendig"

2022-09-05 08:42 UTC, hasslinger commented
Die meisten Anmerkungen habe ich umgesetzt. Bei ein paar Sachen habe ich noch eine Frage als Kommentar angefügt.

Bezüglich der Thematik Urheberrecht stimme ich zu dass das eine sehr interessante Frage ist. Bei der Recherche bin ich auch auf ganze Kapitel und Bücher gestoßen, die sich damit beschäftigen, wobei ich mir das noch nicht genau angeguckt habe. Die Frage ist allerdings ob das nicht den Rahmen des Artikels sprengen würde ... was meinst du?

2022-09-06 08:14 UTC, jo2 requested changes
Eine Kleinigkeit ist noch drin. Zum Thema Urheberrecht, vielleicht kannst du das im Rahmen eines zweiten Artikels klären? Da weiß ich aber nicht, wie das bei dir zeitlich aussieht. Generell Urheberrecht bei KI-Generiertem ist auch im Hinblick auf bspw. GitHub Copilot ein interessantes Thema. Wenn du einen zweiten Artikel dazu machst, könntest du hier ggf. noch einen Teaser ergänzen, das musst du aber wissen.

2022-09-06 08:14 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +<div align='center'>
ne, dann passt es.

2022-09-06 09:49 UTC, hasslinger commented
Danke für das schnelle erneute Review!

Die Kleinigkeit habe ich ausgebessert.
Zeitlich ist es gerade tatsächlich relativ schwierig bei mir einen zweiten Artikel zu schreiben. Vielleicht mach ich das nochmal, aber könnte mich da jetzt nicht festlegen, ob es in naher Zukunft passieren könnte ... :D

Ich hatte noch eine Frage bezüglich deiner Anmerkung zur Zeile 122. Meinst du ich sollte DeepDream noch ergänzen, oder lieber nicht um den Artikel nicht zu lang werden zu lassen?

2022-09-06 10:22 UTC, jo2 commented
Die Änderungen passen soweit. Wie viel wäre das denn zu DeepDream? Wenn das so ~10 Zeilen sind, würde ich es der Vollständigkeit mit rein nehmen.

2022-09-06 11:41 UTC, hasslinger commented
Ich habe ein paar Zeilen bezüglich DeepDream nun ergänzt

2022-09-09 12:24 UTC, acetous commented
Hallo @hasslinger 

kannst Du bitte noch bei dem Blogpost den Teaser (1. Absatz) auf ca. die Hälfte kürzen oder teilen? Ansonsten ist der Teaser zu lang.
Zudem solltest Du noch Quellenverweise zu den Bildern geben, damit klar ist, woher die kommen. Manche KI-Generatoren erfordern das auch bei weiterer Nutzung.

Danke!

2022-09-09 12:43 UTC, hasslinger commented
Hi @acetous 
ich habe in anderen Blogposts wie z.B. "Schließung der Versorgungslücke durch Energie aus Kohle – oder doch Atomkraft?" vom 31.08. gesehen dass in dem Teaser (also das was man von der Startseite aus lesen kann) etwas anderes stand als in der Einleitung wenn man den Blogpost geöffnet hat.
Vielleicht würde sich das hier auch anbieten, dass ich die Einleitung so lasse, aber 1-2 Sätze schreibe, die dann in der Startseite angezeigt werden? Falls das in Frage kommen würde, hast du einen Tipp für mich wie das funktioniert? :D

2022-09-12 15:27 UTC, jo2 requested changes
3 Kleinigkeitn sind noch drin. Ein Kommentar von mir ist auch noch drin, auf den musst du aber nicht unbedingt eingehen.

2022-09-12 15:27 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +Googles DeepDream wird als eine der wenigen KI-Systeme genannt, das bereits transformationale Kreativität zumindest teilweise beherrscht.
```suggestion
Googles DeepDream wird als ein der wenigen KIs genannt, die bereits transformationale Kreativität zumindest teilweise beherrscht.
```

2022-09-12 15:27 UTC, jo2 commented on _posts/2022-08-22-existenz-und-potenzial-kreativer-KI.md
> +<img width="290px" height="200" alt="Bild gemalt von DeepDream" src="/assets/images/posts/existenz-und-potenzial-kreativer-KI/DeepDream.jpg"/>
Wird das echt als bisher nie dagewesener Stil bezeichnet?? Das ist das Bob-Ross-Meme und das Awkward-Seal-Meme verknüpft und ein Effekt darauf gelegt.. Ich würde nicht sagen, dass ich ähnliches schon tausendfach gesehen habe, aber sicherlich nicht zum ersten Mal..

2022-09-13 14:32 UTC, jo2 approved these changes

2022-10-26 11:47 UTC, acetous approved these changes

2022-10-26 11:49 UTC, merged

2022-10-26 16:30 UTC, hasslinger commented
Hey @acetous vielen Dank für das Mergen! Ich habe mich gefreut zu sehen, dass der Artikel veröffentlicht wurde. Jedoch scheint es nicht zu funktionieren, dass mein Bild angezeigt wird. In der Preview war/ist es zu sehen, aber auf der Webseite ist nur das adesso Logo zu sehen ... ist hier etwas schief gelaufen?