Blog Erstellung - IT-Sicherheitskennzeichen
adessoSE/devblog pull request #255
Opened 2022-09-02 08:16 UTC by VivienEmily

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-09-02 08:17 UTC, jekyll2cms commented
author_ids: Author github is missing for author vschiller. Provide a github link.

2022-09-02 08:22 UTC, jekyll2cms commented
author_ids: Author github is missing for author vschiller. Provide a github link.

2022-09-02 15:43 UTC, jo2 requested changes
Ein paar Sachen habe ich dir noch angemerkt. MMn. ist der Artikel noch etwas dünn. Gibt es bspw. Umfragen zu Kauftendenzen mit und ohne IT-Sicherheitskennzeichen? Hat adesso entsprechend gekennzeichnete Produkte? Wie sieht es mit einer Prüfung auf bestehende CVEs aus? Vielleicht gibt dir das noch ein paar Anhaltspunkte, auf was du noch eingehen könntest.

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Hersteller von IT-Produkten können ihre Produkte vom Bundesamt für Sicherheit in der Informationstechnik (BSI) mit dem IT-Sicherheitskennzeichnen auszeichnen lassen.
```suggestion
IT-Unternehmen können ihre Produkte vom Bundesamt für Sicherheit in der Informationstechnik (BSI) mit dem IT-Sicherheitskennzeichnen auszeichnen lassen. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Die Produkthersteller sichern dabei zu, die jeweiligen Sicherheitsrichtlinien ihrer Produktkategorie einzuhalten.
```suggestion
Die Unternehmen sichern dabei zu, die jeweiligen Sicherheitsrichtlinien für ihre Produktkategorie einzuhalten. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Das IT-Sicherheitskennzeichen gibt den VerbraucherInnen eine transparente und schnelle Übersicht, ob ein Produkt die von ihnen geforderten Sicherheitsrichtlinien einhält.
```suggestion
Das IT-Sicherheitskennzeichen gibt den Nutzenden eine transparente und schnelle Übersicht, ob ein Produkt die von ihnen geforderten Sicherheitsrichtlinien einhält. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Damit trägt es zu mehr Transparenz im digitalen Verbraucherschutz in Deutschland bei.
```suggestion
Damit trägt es zu mehr Transparenz im digitalen Konsumierendenschutz in Deutschland bei. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +VerbraucherInnen wird es dadurch ermöglicht einfacher und informierter zu beurteilen, ob ein bestimmtes Produkt die Sicherheitsanforderungen einhält.
```suggestion
Nutzenden wird es dadurch ermöglicht einfacher und informierter zu beurteilen, ob ein bestimmtes Produkt die Sicherheitsanforderungen einhält. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Zu jedem IT-Sicherheitskennzeichen gibt es eine Produktseite des BSI auf der aufgelistet ist, ob das Produkt die Sicherheitsanforderungen erfüllt.
```suggestion
Zu jedem IT-Sicherheitskennzeichen gibt es eine Produktseite des BSI, auf der aufgelistet ist, ob das Produkt die Sicherheitsanforderungen erfüllt. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Die technischen Richtlinien, die zur jeweiligen Produktkategorie gehören werden ebenfalls an gleicher Stelle zur Verfügung gestellt. Auch wenn es bislang wenige zu sein scheinen, wird die Liste konti
```suggestion
Die technischen Richtlinien, die zur jeweiligen Produktkategorie gehören, werden ebenfalls an gleicher Stelle zur Verfügung gestellt. Auch wenn es bislang wenige zu sein scheinen, wird die Liste kontinuierlich erweitert werden. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Unsere Welt wird immer smarter und vernetzter, dementsprechend werden auch an die Produkte IT Sicherheitsanforderungen gestellt.
```suggestion
Unsere Welt wird immer smarter und vernetzter, dementsprechend werden auch an die IT-Produkte höhere Sicherheitsanforderungen gestellt.
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Zunächst einmal liegt es an den Herstellern, dass das Produkt von Anfang an sicher gestaltet wird (Security by Design) und alle technischen Sicherheitsrichtlinien der jeweiligen Produktgruppe des BSI
```suggestion
Zunächst einmal liegt es an den herstellenden Unternehmen, dass das Produkt von Anfang an sicher gestaltet wird (Security by Design) und alle technischen Sicherheitsrichtlinien der jeweiligen Produktgruppe des BSI umgesetzt sind. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Das IT-Sicherheitskennzeichen kann auf den Seiten des BSI beantragt werden.
Fehlt hier was? Hier ist ein ziemlich harter Bruch im Text, allerdings geht es im gleichen Absatz weiter..

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Die Formulare befinden sich [hier](https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/IT-Sicherheitskennzeichen/fuer-Hersteller/Antrag/IT-SiK-Antrag.html)
```suggestion
Die Formulare befinden sich [hier](https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/IT-Sicherheitskennzeichen/fuer-Hersteller/Antrag/IT-SiK-Antrag.html).
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Unter den Anlagen befindet sich auch die Technische Erklärung, die unter anderem folgende Punkte fragt:
```suggestion
Unter den Anlagen befindet sich auch die technische Erklärung, die unter anderem folgende Punkte abfragt: 
```
oder ist Technische Erklärung in dem Fall ein feststehender Begriff?

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +-	Wie werden Standardpasswörter falls nötig generiert?
```suggestion
- Wie werden Standardpasswörter falls nötig generiert?
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +-	Wie verlaufen die Meldeverfahren zum Umgang mit Schwachstellen?
```suggestion
- Wie verlaufen die Meldeverfahren zum Umgang mit Schwachstellen?
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +-	Wie werden zugesicherte Supportzeiten gegenüber den VerbraucherInnen transparent gemacht?
```suggestion
- Wie werden zugesicherte Supportzeiten gegenüber den Nutzenden transparent gemacht?
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +-	Wie wird sichergestellt, dass über das Netzwerk keine unautorisierten sicherheitsrelevanten Änderungen an der Konfiguration des Produkts vorgenommen werden können?
```suggestion
- Wie wird sichergestellt, dass über das Netzwerk keine unautorisierten sicherheitsrelevanten Änderungen an der Konfiguration des Produkts vorgenommen werden können?
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +-	uvm.
```suggestion
- uvm.
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Auch wird nach dem Handbuch für Benutzende, Richtlinie zum Umgang mit Schwachstellen und falls vorhanden einem technischen Produktblatt gefragt.
Die Richtlinien zum Umgang mit Schwachstellen hattest du oben in den Stichpunkten schon

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Eine technische Prüfung jedes einzelnen Produktes erfolgt nicht, sondern kann stichprobenartig von der Marktaufsicht überprüft werden.
```suggestion
Eine technische Prüfung jedes einzelnen Produktes erfolgt nicht, stattdessen können einzelne Produkte stichprobenartig von der Marktaufsicht überprüft werden.
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Zudem kann es von Seiten des BSI widerrufen werden, falls Sicherheitsstandard nicht gehalten werden.
```suggestion
Zudem kann es von Seiten des BSI widerrufen werden, falls Sicherheitsstandards nicht eingehalten werden. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +# Welche Informationen können VerbraucherInnen sehen?
```suggestion
# Welche Informationen können Nutzende sehen? 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Insbesondere liegt es am Nutzenden Sicherheitsfeatures nicht auszuschalten oder Produkte so zu nutzen, dass der Zugang zu Passwörtern und co. einem Kriminellen erleichtert wird.
```suggestion
Insbesondere liegt es am Nutzenden, Sicherheitsfeatures nicht auszuschalten oder Produkte so zu nutzen, dass Dritten der Zugang zu Passwörtern und co. erleichtert wird. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +VerbraucherInnen sind durch das IT-Sicherheitskennzeichen in der Lage wichtige Fakten zu Sicherheitseigenschaften eines vernetzten Produkts auf einen Blick zu erhalten.
```suggestion
Nutzende sind durch das IT-Sicherheitskennzeichen in der Lage, auf einen Blick wichtige Fakten zu Sicherheitseigenschaften eines vernetzten Produkts zu erhalten. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +[Hier](https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/IT-Sicherheitskennzeichen/Vorschau_Produktseite/Beispiel_Produktinformationsseite.html?nn=936796) eine Beispielseite.
```suggestion
Über einen QR-Code gelangen sie zu der Produktseite des BSI und dem aktuellen Status des Produktes, [hier](https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/IT-Sicherheitskennzeichen/Vorschau_Produktseite/Beispiel_Produktinformationsseite.html?nn=936796) eine Beispielseite dazu. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +So können sie sehen, dass sich ein Hersteller eines Produkts freiwillig dazu verpflichtet hat die Anforderung des BSI einzuhalten.
```suggestion
So können sie sehen, dass sich die Herstellerfirma eines Produkts freiwillig dazu verpflichtet hat, die Anforderung des BSI einzuhalten. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Dies kann ein Wettbewerbsvorteil darstellen.
```suggestion
Dies kann einen Wettbewerbsvorteil darstellen. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Die Analoge Welt wird immer digitaler, für VerbraucherInnen ist es schwierig zu erkennen, ob ein smartes Gerät auch digital sicher ist oder nicht.
```suggestion
Die analoge Welt wird immer digitaler, für Nutzende ist es schwierig, zu erkennen, ob ein smartes Gerät auch digital sicher ist oder nicht. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Wir wissen welchen Stromverbrauch Geräte haben, aber oftmals nicht wie abgesichert unsere Daten sind.
```suggestion
Wir wissen, welchen Stromverbrauch Geräte haben, aber oftmals nicht, wie unsere Daten abgesichert sind. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Dies könnte mehr vertrauen schaffen.
```suggestion
Das IT-Sicherheitskennzeichen könnte mehr vertrauen schaffen.
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Durch das IT-Sicherheitskennzeichen fließt eine weitere wichtige Komponente in die Kaufentscheidung der VerbraucherInnen ein.
```suggestion
Das IT-Sicherheitskennzeichen ist eine wichtige Komponente in der Kaufentscheidung von Nutzenden. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Sie ist eine zusätzliche Komponente die mehr Transparenz in der smarten Welt schafft.
```suggestion
Es ist außerdem eine zusätzliche Komponente, die mehr Transparenz in der smarten Welt schafft. 
```

2022-09-02 15:43 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Es ist nicht das Allheilmittel und garantiert auch nicht, dass ein IT-Prdoukt absolut sicher ist (es können immer neue Angriffsvektoren entstehen), jedoch der erste Schritt für mehr Vertrauen in digi
```suggestion
Es ist nicht das Allheilmittel und garantiert auch nicht, dass ein IT-Prdoukt absolut sicher ist, da immer neue Angriffsvektoren entstehen können.
Es ist jedoch der erste Schritt für mehr Vertrauen in digitale Produkte und gleichzeitig eine Selbstverpflichtung von Produktherstellern gegenüber ihren Kundinnen und Kunden.
```

2022-09-02 15:51 UTC, jo2 commented
Den Kommentar von jekyll2cms kannst du übrigens ignorieren. Der GitHub-Nutzername wird seit kurzem nicht mehr aufgenommen, wir sind noch nicht dazu gekommen, das Tool, das die formale Korrektheit der Beitrags überprüft, anzupassen.

2022-09-19 12:37 UTC, VivienEmily commented
> Ein paar Sachen habe ich dir noch angemerkt. MMn. ist der Artikel noch etwas dünn. Gibt es bspw. Umfragen zu Kauftendenzen mit und ohne IT-Sicherheitskennzeichen? Hat adesso entsprechend gekennzeichnete Produkte? Wie sieht es mit einer Prüfung auf bestehende CVEs aus? Vielleicht gibt dir das noch ein paar Anhaltspunkte, auf was du noch eingehen könntest.

Hi, 
die gibt es leider noch nicht. Das Kennzeichen gibt es auch erst seit Anfang des Jahres. Ich denke es muss im Sinne des Verbraucherschutzes auch erst noch bekannter werden. Bislang gab es auch nur zwei Produktarten die das Siegel erhalten haben: E-Mail Dienste und Breitbandrouter. Ob andere Anträge noch nicht angenommen wurden oder es nicht mehr Anträge gibt ist leider nicht bekannt. Ich habe alle infos zusammengekratzt die ich finden konnte. Da ich das eine gute Sache für den Verbraucherschutz finde. Auch interessant für die LOB MI, selber haben wir aber bislang noch nicht beraten, da zu neu und zu unbekannt bisher. Aber vielleicht und hoffentlich ändert sich das noch :)

2022-09-19 12:39 UTC, VivienEmily commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Damit trägt es zu mehr Transparenz im digitalen Verbraucherschutz in Deutschland bei.
Ist Verbraucherschutz auch wenn nicht gegendert nicht der Standard? Heißt ja auch noch Verbraucherzentrale & co?

2022-09-19 12:44 UTC, VivienEmily commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Unter den Anlagen befindet sich auch die Technische Erklärung, die unter anderem folgende Punkte fragt:
Technische Richtlinie wäre einer, aber für die Erklärung nicht

2022-09-19 15:39 UTC, jo2 requested changes

2022-09-19 15:39 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Damit trägt es zu mehr Transparenz im digitalen Verbraucherschutz in Deutschland bei.
Laut https://geschicktgendern.de/ und https://www.scribbr.de/gendern/woerterbuch/verbraucherschutz-verbraucherinnenschutz/ sollte es gegendert werden. Die Institution heißt zwar Verbraucherzentrale, die Umbenennung von Institutionen aufgrund von gendergerechter Sprache kann aber grade bei deutschen Behörden eine ganze Weile dauern. Ich bin aber auch kein Experte in Sachen gendergerechter Sprache.

2022-09-19 15:39 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Das IT-Sicherheitskennzeichen ist eine wichtige Komponente in der Kaufentscheidung von Nutzenden.
Wenn es hierzu noch keine Befragungen o.ä. gibt, solltest du das hier im Konjunktiv formulieren.

2022-09-19 15:39 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Es ist jedoch der erste Schritt für mehr Vertrauen in digitale Produkte und gleichzeitig eine Selbstverpflichtung von Produktherstellern gegenüber ihren Kundinnen und Kunden.
Konjunktiv s.o.

2022-09-20 09:02 UTC, VivienEmily commented
@jo2 ich war gestern noch nicht fertig, musste meinen Sohn von der Kita abholen :) Ich schreibe hier rein sobald alles durch ist.

2022-09-20 09:11 UTC, VivienEmily commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Das IT-Sicherheitskennzeichen kann auf den Seiten des BSI beantragt werden.
Ich glaube da war ein Enter zu viel habs korrigiert.

2022-09-20 09:12 UTC, VivienEmily commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Auch wird nach dem Handbuch für Benutzende, Richtlinie zum Umgang mit Schwachstellen und falls vorhanden einem technischen Produktblatt gefragt.
Habe ich gelöscht

2022-09-20 09:15 UTC, VivienEmily commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Das IT-Sicherheitskennzeichen ist eine wichtige Komponente in der Kaufentscheidung von Nutzenden.
Habe ich geändert und noch 2-3 Schlusssätze geändert

2022-09-20 09:16 UTC, VivienEmily commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Es ist jedoch der erste Schritt für mehr Vertrauen in digitale Produkte und gleichzeitig eine Selbstverpflichtung von Produktherstellern gegenüber ihren Kundinnen und Kunden.
Passe ich an

2022-09-20 09:23 UTC, VivienEmily commented
@jo2 fertig

2022-09-23 13:19 UTC, jo2 requested changes
Eine Sache ist noch drin.

2022-09-23 13:19 UTC, jo2 commented on _posts/2022-09-02-IT-Sicherheitskennzeichen-.md
> +Bislang haben zwei Produktarten das IT-Sicherheitskennzeichen erhalten: E-Mail Dienste und Breindbandrouter. Das IT-Sicherheitskennzeichen ist in der breiten Massen, insbesondere im herstellenden Gew
```suggestion
Bislang haben zwei Produktarten das IT-Sicherheitskennzeichen erhalten: E-Mail-Dienste und Breitbandrouter. Das IT-Sicherheitskennzeichen ist in der breiten Massen, insbesondere im herstellenden Gewerbe, noch nicht bekannt. Dies könnte sich im Laufe der Jahre ändern.
```

2022-09-29 05:59 UTC, VivienEmily commented
So jetzt hoffentlich :)

2022-10-14 07:16 UTC, VivienEmily commented
@jo2 ? :)

2022-10-18 09:20 UTC, jo2 submitted a review, later dismissed

2022-10-18 09:21 UTC, jo2 commented
@acetous von meiner Seite ist der Beitrag soweit fertig, willst du noch drüber gucken?

2022-11-09 08:49 UTC, acetous approved these changes

2022-11-09 08:50 UTC, merged