Artikel "Volltextsuchen mit Elasticsearch"
adessoSE/devblog pull request #256
Opened 2022-09-09 20:48 UTC by sypste

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [x] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-09-09 20:48 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-12 16:28 UTC, jo2 requested changes
Das ist ein sehr interessanter Artikel zum Thema Suchen in Elasticsearch, aber auch zur Volltextsuche generell. Ein paar Kleinigkeiten habe ich dir noch angemerkt.

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +['lä', 'län', 'äng', 'nge', 'ge']
Verwende bitte hier und im Folgenden Codeblöcke. Diese kannst du durch jeweils drei Backticks (**``` ` ```**) davor und dahinter kennzeichnen.

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Obwohl einige Ngramme auch in der Tokenisierung von Michael auftauchen würden, gibt es nichts Besonderes an ihnen - Elasticsearch wird einfach mit den Dokumenten übereinstimmen, die die Token am häuf
```suggestion
Obwohl einige Ngramme auch in der Tokenisierung von "Michael" auftauchen würden, gibt es nichts Besonderes an ihnen - eine Suche mit Elasticsearch wird einfach die Dokumente mit den meisten Übereinstimmungen in der Tokenliste liefern.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Im Allgemeinen braucht es ein wenig Test und Versuch und Irrtum, um die besten Minimal- und Maximalwerte für die Ngrammlänge zu finden (je länger, desto spezifischer die Treffer, aber weniger fehlert
```suggestion
Im Allgemeinen braucht es ein wenig Test, Versuch und Irrtum, um die besten Minimal- und Maximalwerte für die Ngrammlänge zu finden (je länger, desto spezifischer die Treffer, aber weniger fehlertolerant).
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Während des Tippens wird die Ergebnismenge bereits eingegrenzt und könnte verwendet werden, um Benutzer zum gewünschten Suchergebnis zu leiten.
```suggestion
Während des Tippens wird die Ergebnismenge bereits eingegrenzt und sie könnte schon verwendet werden, um Benutzer zum gewünschten Suchergebnis zu leiten.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Hier werfen wir einen Blick auf das Plugin für die phonetische Analyse, das es uns ermöglicht, phonetische Repräsentationen von Eingabe-Token zu erhalten.
```suggestion
Hier werfen wir einen Blick auf das Plugin für die phonetische Analyse, das es uns ermöglicht, phonetische Repräsentationen von Eingabetoken zu erhalten.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Nachdem ein Analyzer definiert wurde, der den phonetischen Token-Filter verwendet, kann natürliche Sprache in eine phonetische Repräsentation gebracht werden.
```suggestion
Nachdem ein Analyzer definiert wurde, der den phonetischen Tokenfilter verwendet, kann natürliche Sprache in eine phonetische Repräsentation gebracht werden.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Um den Analyzer zu testen, vergleichen wir die Token, die jeweils aus der Analyse von 'Michael' und 'Micheal' hervorgehen.
```suggestion
Um den Analyzer zu testen, vergleichen wir die Token, die jeweils aus der Analyse von "Michael" und "Micheal" hervorgehen.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +So sollten wir bereits einige Ergebnisse gefunden werden, die für eine Testnutzerbasis einigermaßen akzeptabel sein könnten.
```suggestion
So sollten wir bereits einige Ergebnisse erhalten, die für eine Testnutzerbasis einigermaßen akzeptabel sein könnten.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +[^3]: Siehe [Präzisions- und Recall-Problem](https://en.wikipedia.org/wiki/Precision_and_recall).
```suggestion
[^3]: Siehe [Präzisions- und Recall-Problem](https://en.wikipedia.org/wiki/Precision_and_recall)
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +- Zweitens legen wir einen Basis-Score für alle Dokumente fest, die eine Fuzzy-Transposition des Suchbegriffs in denselben Feldern enthalten. Da wir die Anzahl der Kandidaten bereits reduziert haben,
Was ist der Bearbeitungsabschtand und warum ist das ein geringer Ansatz? Kannst du da bei Fuzziness noch etwas zu schreiben?

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +- Anschließend werden die Dokumente höher bewertet, die mit einer oder beiden übereinstimmenden Suchanfragen übereinstimmen, entweder mit einer phonetischen Äquivalenz oder einer direkten lexikalisch
Hier hast du drei mal übereinstimmen, kannst du den Satz etwas umformulieren?

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Um die Benutzerfreundlichkeit durch Vorschläge während der Eingabe zu verbessern, könnten wir die vorher verwendeten `search_as_you_type`-Felder weiter einbeziehen.
```suggestion
Um die Benutzerfreundlichkeit durch Vorschläge während der Eingabe zu verbessern, könnten wir die vorher verwendeten "search-as-you-type"-Felder weiter einbeziehen.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Die ["Search-as-you-type"-Funktionalität](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-as-you-type.html) nutzt Ngramme auf eine etwas andere Art und Weise als bisher gezeigt
```suggestion
Die ["search-as-you-type"-Funktionalität](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-as-you-type.html) nutzt Ngramme auf eine etwas andere Art und Weise als bisher gezeigt.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Damit können eine Reihe von Dokumenten definiert werden, die in Abhängigkeit von der Abfrage und ihren Parametern in der Suchergebnisliste erscheinen sollen oder nicht erscheinen sollen.
```suggestion
Damit können eine Reihe von Dokumenten definiert werden, die in Abhängigkeit von der Abfrage und ihren Parametern in der Suchergebnisliste erscheinen oder nicht erscheinen sollen.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Normalerweise sollten die Felder eines Indexes, wie wir es bisher getan haben, vor der Aufnahme von Daten deklariert werden, d.h. bevor irgendwelche Daten in Elasticsearch geladen werden.
```suggestion
Normalerweise sollten die Felder eines Index, wie wir es bisher getan haben, vor der Aufnahme von Daten deklariert werden, d.h. bevor irgendwelche Daten in Elasticsearch geladen werden.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Zum Abschluss etwas Ausgefalleneres.
```suggestion
Zum Abschluss betrachten wir etwas Ausgefalleneres.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Dazu müssen zunächst das [Plugin](https://github.com/spinscale/elasticsearch-ingest-opennlp) und die erforderlichen ML-Modelle in Elasticsearch geladen werden, um anschließend eine Ingest-Pipeline zu
```suggestion
Dazu müssen zunächst das [Plugin](https://github.com/spinscale/elasticsearch-ingest-opennlp) und die erforderlichen ML-Modelle in Elasticsearch geladen werden, um anschließend eine Ingest-Pipeline zu definieren, die den zu indizierenden Text um die gewünschten Annotationen erweitert.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Die Einrichtungsschritte werden im oben genannten Gitpod-Workspace zur Verfügung gestellt, und die NER-Modelle können mit dem beschriebenen Code ausprobiert werden.
```suggestion
Die Einrichtungsschritte werden im oben genannten Gitpod-Workspace zur Verfügung gestellt und die NER-Modelle können mit dem beschriebenen Code ausprobiert werden.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Eingaben können mithilfe von Ngrammen und phonetischer Transformation fehlertoleranter gestaltet werden, sowie bereits während der Nutzereingabe (also unvollständiger Suchparameter) Vorschläge für Su
```suggestion
Eingaben können mithilfe von Ngrammen und phonetischer Transformation fehlertoleranter gestaltet werden, außerdem können bereits während der Nutzereingabe (also unvollständiger Suchparameter) Vorschläge für Suchtreffer geliefert werden.
```

2022-09-12 16:28 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +Mit Fuzzy Search und der Verbindung der erarbeiteten Suchheuristiken werden die erarbeiteten Suchheuristiken kombiniert, um eine mehrschichtige Suche zu designen, die sowohl schnell als auch fehlerto
```suggestion
Mit Fuzzy Search und der Verbindung der erarbeiteten Suchheuristiken werden diese kombiniert, um eine mehrschichtige Suche zu designen, die sowohl schnell als auch fehlertolerant ist.
```

2022-09-13 14:49 UTC, sypste commented on _data/authors.yml
> +  github: https://github.com/mboegers
Keine Absicht, der Beitrag hat leider ein bisschen gedauert und beim Rebase ist mir das nicht aufgefallen

2022-09-13 15:05 UTC, sypste commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +[^1]: Dazu einfach das Template-Repo nutzen, um ein persönliches Repo zu erstellen, den Link zum Repo benutzen, um über das GitPod-Dashboard einen Workspace zu erstellen und anschließend zu öffnen. D
Die Fußnote habe ich weiter angepasst, damit die Schritte zum Setup klarer werden - so verständlich?

2022-09-13 15:14 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:15 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:15 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:16 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:16 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:16 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:17 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:18 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:28 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:29 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:30 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:30 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:31 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:32 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:36 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-13 15:38 UTC, sypste commented
@jo2 deine Vorschläge habe ich so gut wie alle angenommen. Bei ein zwei habe ich den Text etwas versucht klarer zu formulieren, hoffe das hat geklappt!

2022-09-16 14:29 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-19 15:23 UTC, jo2 requested changes

2022-09-19 15:23 UTC, jo2 commented on _data/authors.yml
> +  github: https://github.com/mboegers
Bitte ändere keine Einträge von anderen

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +In diesem Beitrag zeige ich euch, wie ihr auf Basis der Open-Source-Software Elasticsearch textbasierte Daten speichert, indiziert und für menschliche User einfach durchsuchbar gestalten könnt.
Die Satzanfänge in diesem und dem vorherigen Satz sind sehr ähnlich und sagen das gleiche aus. Kannst du die verknüpfen?

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    input = 'micheal'
Verwende für allen mehrzeiligen Code bitte den [Codeblock](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) von Markdown.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    Input "mi" yields a total 33 results with titles ['1974 United States Senate election in Missouri', '103 Mile Lake', 'Peter Milliman', 'Micropterix lambesiella', 'Middle nasal concha', 'Middletow
Codeblock s.o.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    client.indices.put_settings(
Codeblock s.o.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    michael_phonetic_tokens = [t['token'] for t in client.indices.analyze(
Codeblock s.o.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    client.search(index='logstash-articles', query={
Codeblock s.o.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    "bool": {
Codeblock s.o.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    client.search(index='logstash-articles', query={
Codeblock s.o.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    POST logstash-articles/_rank_eval
Codeblock s.o.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    GET logstash-articles/_search
Codeblock s.o.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    client.ingest.put_pipeline(
Codeblock s.o.

2022-09-19 15:23 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +    'Condor', 'Sandro Miller', 'Marv Albert', 'Chris Mullin', 'Simon', 'Michael', 'Karl Malone', 'Jason Kidd', 'Story', 'Bryant', 'Harper San Francisco', 'Charles Oakley', 'Mark Vancil', 'Mike', 'Jam
Codeblock s.o.

2022-09-20 13:34 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-20 13:43 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-20 13:47 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-20 13:48 UTC, sypste commented
Hi @jo2, passt die Formatierung der Codeblöcke jetzt?

2022-09-23 13:22 UTC, jo2 commented on _posts/2022-09-09-Volltextsuchen-mit-Elasticsearch.md
> +```['lä', 'län', 'äng', 'nge', 'ge']```
Mach nach den drei Backticks bitte einen Zeilenumbruch, die Einrückung brauchst du dann nicht

2022-09-23 13:25 UTC, jo2 commented
@sypste mach bitte nach den drei Backticks einen Zeilenumbruch. Die Einrückung brauchst du dann nicht. Zusätzlich kannst du nach den Backticks noch die Sprache angeben. Ein Beispiel siehst du [hier](https://raw.githubusercontent.com/adessoSE/devblog/master/examples/2021-08-23-blog-post-guide.md): 
![image](https://user-images.githubusercontent.com/7516893/191970338-0132e4e3-5f26-487c-9ec2-7c45245222be.png)

2022-09-23 17:40 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-26 08:02 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-09-26 08:03 UTC, sypste commented
@jo2 Einrückung und Sprache in den Code-Blöcken sind jeweils angepasst

2022-09-28 09:16 UTC, jo2 approved these changes

2022-09-28 09:17 UTC, jo2 commented
@acetous willst du hier noch drüber gucken? ansonsten ist der Post soweit fertig.

2022-12-13 07:56 UTC, sypste commented
Hi @acetous , gibt es eine TImeline, wann der Artikel veröffentlicht wird?

2023-01-25 09:32 UTC, acetous approved these changes

2023-01-25 09:34 UTC, merged