Neuer Blogpost "Orchestrierung mit Nomad"
adessoSE/devblog pull request #264
Opened 2022-10-20 16:44 UTC by unexist

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-10-20 16:44 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-10-27 12:37 UTC, jo2 requested changes
Der Artikel ist sehr interessant, ein paar generelle Anmerkungen noch:
* Du verwendest sehr viele Links bzw. Fußnoten, wenn du einen Begriff hast, verwende den Link bitte nur bei der ersten Verwendung des Begriffs, ansonsten wir der Text schnell unübersichtlich wegen der vielen Links.

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +ihren bereitgestellten Diensten registrieren und andere Anwendungen dann Informationen über
```suggestion
ihren bereitgestellten Diensten registrieren und bei dem andere Anwendungen dann Informationen über
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +die [Artifact][2] Stanza und lassen [Nomad][35] die Anwendung direkt aus dem Internet laden und
Meinst du hier so etwas wie eine Registry? Irgendwie fehlt da noch ein Wort

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Nach ein paar Sekunden sollte [Consul][8] dann gestartet über folgende URL im Browser aufrufbar sein
```suggestion
Nach ein paar Sekunden sollte [Consul][8] dann gestartet und über folgende URL im Browser aufrufbar sein
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Alle bekannten Services werden dann auf dem **Services** Reiter aufgeführt - dazu zählen [Consul][8]
```suggestion
Alle bekannten Services werden dann auf dem **Services**-Reiter aufgeführt - dazu zählen [Consul][8]
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +selbst und [Nomad][35] - allerdings leider Fehlanzeige was unseren Instanzen betrifft.
```suggestion
selbst und [Nomad][35] - allerdings leider Fehlanzeige was unsere Instanzen betrifft.
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +**<1>** [Nomad][35] erlaubt es [Tag][53]s zu vergeben, die sich in etwa so verhalten wie [Label][31] bei [Kubernetes][29].
```suggestion
**<1>** [Nomad][35] erlaubt es, [Tags][53]s zu vergeben, die sich in etwa so verhalten wie [Label][31] bei [Kubernetes][29].
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Was es mit diesem konkreten [Tag][53] auf sich hat erfahrt ihr im nächsten Kapitel.<br />
```suggestion
Was es mit diesem konkreten [Tag][53] auf sich hat, erfahrt ihr im nächsten Kapitel.<br />
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +**<2>** Über das [Check][5] Stanza legen wir fest wie [Healthchecks][17] durchführt werden.
```suggestion
**<2>** Über das [Check][5] Stanza legen wir fest, wie [Healthchecks][17] durchführt werden.
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Hier werden dann noch einmal alle Parameter aufgeführt und man bekommt eine Idee was für weitere
```suggestion
Hier werden dann noch einmal alle Parameter aufgeführt und man bekommt eine Idee, was für weitere
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Konfigurationsmöglichkeiten obige Stanza noch mitbringen.
```suggestion
Konfigurationsmöglichkeiten obige Stanza noch mitbringt.
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Schnell noch ein erneuter **Dry-Run**, um weitere Überraschungen auszuschließen:
```suggestion
Danach führen wir schnell noch einen neuen **Dry-Run** aus, um weitere Überraschungen auszuschließen:
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Haben wir alles überprüft können wir den [Job][26] ausführen und sehen dann hoffentlich nach kurzer
```suggestion
Haben wir alles überprüft, können wir den [Job][26] ausführen und sehen dann hoffentlich nach kurzer
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Sprechen wir jetzt [Fabio][14] über den Defaultport `9999` an bekommen wir erneut die altbekannte
```suggestion
Sprechen wir jetzt [Fabio][14] über den Defaultport `9999` an, bekommen wir erneut die altbekannte
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Wenn wir das ganze jetzt wiederholen sollte [Fabio][14] theoretisch die Last gleichmäßig auf unsere
```suggestion
Wenn wir das ganze jetzt wiederholen, sollte [Fabio][14] theoretisch die Last gleichmäßig auf unsere
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Instanzen, allerdings würden wir davon derzeit nichts mitbekommen.
```suggestion
Instanzen verteilen, allerdings würden wir davon derzeit nichts mitbekommen.
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Ein einfacher Trick hier ist einen neuen [HTTP Header][20] zu setzen, der die entsprechende
```suggestion
Ein einfacher Trick hier ist, einen neuen [HTTP Header][20] zu setzen, der die entsprechende
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Vermutlich könnt ihr euch die nächsten Schritte denken, daher das ganze in Schnelldurchlauf:
```suggestion
Vermutlich könnt ihr euch die nächsten Schritte denken, daher das ganze im Schnelldurchlauf:
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Testen wir das ganze nach erfolgreichem Deployment und sehen wir wunderbar wie die verschiedenen
```suggestion
Testen wir das ganze nach erfolgreichem Deployment, sehen wir, wie die verschiedenen
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Falls ihr euch jetzt fragt weshalb das ganze überhaupt ohne weitere Konfiguration funktioniert:
```suggestion
Falls ihr euch jetzt fragt weshalb, das ganze überhaupt ohne weitere Konfiguration funktioniert:
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Einer der großen Vorteile von [Fabio][14] ist Routen können über [Service Tags][49] festgelegt werden.
```suggestion
Einer der großen Vorteile von [Fabio][14] ist, Routen können über [Service Tags][49] festgelegt werden.
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Unsere Anwendung läuft jetzt erfolgreich auf einem einzelnen Client und wir haben sowohl
```suggestion
Unsere Anwendung läuft jetzt erfolgreich auf einem einzelnen Client und wir haben sowohl die
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Ausfallwahrscheinlichkeit reduziert als auch Lastverteilung eingeführt, in dem wir unsere fünf
```suggestion
Ausfallwahrscheinlichkeit reduziert als auch Lastverteilung eingeführt, indem wir unsere fünf
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Instanzen in einen gemeinsamem [Load Balancer][32] Verbund zusammengefasst haben.
```suggestion
Instanzen in einem gemeinsamen [Load-Balancer][32]-Verbund zusammengefasst haben.
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Soweit so gut - aber wie können wir hier jetzt am geschicktesten Updates durchführen?
```suggestion
Soweit, so gut - aber wie können wir hier jetzt am geschicktesten Updates durchführen?
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Grundsätzlich stehen dafür verschiedene Ansätze zur Verfügung und der einfachste ist natürlich alle
```suggestion
Grundsätzlich stehen dafür verschiedene Ansätze zur Verfügung und der einfachste ist natürlich, alle Instanzen
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Wählen wir diesen Ansatz negieren wir vermutlich einige der vorhin angesprochenen Vorteile und
```suggestion
Wählen wir diesen Ansatz, negieren wir vermutlich einige der vorhin angesprochenen Vorteile und
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +enden im Fehlerfall möglicherweise mit einer zu geringen Anzahl für unseren Workload.
```suggestion
enden im Fehlerfall möglicherweise mit einer zu geringen Anzahl an Instanzen für unseren Workload.
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Ein besserer Ansatz hier ist eine möglichst kleine [Batch Size][3] zu wählen und die Instanzen
```suggestion
Ein besserer Ansatz hier ist, eine möglichst kleine [Batch Size][3] zu wählen und die Instanzen
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +rollierend - sprich nach und nach - zu aktualisieren.
```suggestion
rollend - sprich nach und nach - zu aktualisieren.
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Bevor wir jetzt als einfaches Beispiel ein [Canary Update][4] durchführen sollten wir noch einmal
```suggestion
Bevor wir jetzt als einfaches Beispiel ein [Canary Update][4] durchführen, sollten wir noch einmal
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +kurz in uns gehen und überlegen wie wir sicherstellen können, dass ein Update den gewünschten
```suggestion
kurz in uns gehen und überlegen, wie wir sicherstellen können, dass ein Update den gewünschten
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Ein [Canary Update][4] mit `canary = 1` bedeutet unser Orchestrator startet eine neue Instanz und
```suggestion
Ein [Canary Update][4] mit `canary = 1` bedeutet, unser Orchestrator startet eine neue Instanz und
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +wartet anschließend auf die Bestätigung fortzufahren.
```suggestion
wartet anschließend auf die Bestätigung, fortzufahren.
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Unsere Aufgabe hier ist also zu prüfen, ob diese neue Instanz ordnungsgemäß funktioniert, laufen
```suggestion
Bei unserer Aufgabe zu prüfen, ob diese neue Instanz ordnungsgemäß funktioniert, laufen
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +aber natürlich wieder in die altbekannte Problematik.
Welche Problematik  genau? Wir erkennen nicht, welche Instanz antwortet? Kannst du das noch in einem Satz erwähnen?

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Erneuter **Dry-Run** gefolgt von einem Deployment:
```suggestion
Wir führen erneut einen **Dry-Run** gefolgt von einem Deployment aus:
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Der spannende Teil hier ist [Nomad] unterbricht das Deployment und wir bekommen die nötige Zeit zu
```suggestion
Der spannende Teil hier ist, dass [Nomad] das Deployment unterbricht und wir die nötige Zeit bekommen, um zu 
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Haben wir uns davon ausreichend überzeugt, können wir [Nomad][35] anweisen das Deployment fortzusetzen
```suggestion
Haben wir uns davon ausreichend überzeugt, können wir [Nomad][35] anweisen, das Deployment fortzusetzen
```

2022-10-27 12:37 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Sämtliche Beispiele dieses Beitrags können im folgenden Repository eingesehen werden:
```suggestion
Sämtliche Beispiele dieses Beitrags könnt ihr in folgendem Repository einsehen:
```

2022-10-27 15:32 UTC, unexist commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +die [Artifact][2] Stanza und lassen [Nomad][35] die Anwendung direkt aus dem Internet laden und
Hm, wo denn genau? Nomad soll hier einfach das Binary von Github laden und im Kontext wird das dann über die Artifact Stanza konfiguriert.

2022-10-27 15:43 UTC, unexist commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Orchestrierung ist in aller Munde und aus vielen Bereichen gar nicht mehr wegzudenken - doch gibt es
Eigentlich nicht, das nach der Leerzeile gehört noch dazu - ich nehme mal die Leerzeile raus.

2022-10-27 15:47 UTC, unexist commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +aber natürlich wieder in die altbekannte Problematik.
Jap, ich beziehe mich hier auf das Problem wir wissen nicht auf welche Instanz uns der LB schickt und daher ist es schwierig zu sehen, ob das Canary Update hier auch geklappt hat, ohne alle aus dem LB-Verbund zu werfen. Ich erwähne das nochmal explizit.

2022-11-02 07:14 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +rollierend - sprich nach und nach - zu aktualisieren.
Tatsache, das las sich für mich wie eine schlechte Google-Translate-Übersetzung. Das steht aber sogar im [Duden](https://www.duden.de/rechtschreibung/rollieren)..

2022-11-02 07:20 UTC, jo2 requested changes
Zwei kleine Sachen sind noch drin, danach ist der Post von meiner Seite aus fertig.

2022-11-02 07:20 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +neben dem Platzhirschen [Kubernetes][29] eigentlich Alternativen?
Nach [interner Vorgabe](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#einleitung--teaser) sollen im Teaser keine Links verwendet werden. Setze die Links bitte beim ersten Vorkommen des Worts nach dem Teaser. Bei Nomad (Z. 21) passt es, bei Task Driver (Z.24, Z.27) noch nicht.

2022-11-02 07:20 UTC, jo2 commented on _posts/2022-10-20-Orchestrierung-mit-Nomad.md
> +Dies wird über Task-Driver realisiert, die sowohl von der Community beigesteuert werden aber
Du beziehst dich hier wahrscheinlich auf den englischsprachigen Fachbegriff, oder? Dann muss es hier und im Folgenden Task Driver (ohne Bindestrich) heißen.

2022-11-02 11:23 UTC, jo2 submitted a review, later dismissed

2022-11-02 11:24 UTC, jo2 commented
@unexist kannst du bitte noch einmal den aktuellen adessosSE/devblog:master in deinen Branch mergen?
@acetous möchtest du noch mal drüber gucken?

2022-11-02 11:25 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-13 10:24 UTC, acetous approved these changes

2023-02-13 10:25 UTC, merged