First commit for Java Mulesoft Blog
adessoSE/devblog pull request #265
Opened 2022-10-29 09:11 UTC by tonyHorst

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-10-29 09:12 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-11-02 08:25 UTC, jo2 requested changes
Der Artikel ist recht interessant, ich freue mich schon, darauf zu sehen, wie das an einem Beispiel umgesetzt wird. Einige Aspekte sind mir noch aufgefallen:
* Achte bitte auf eine einheitliche Schreibweise von Begriffen, bisher sind mir aufgefallen
  * MuleSoft (teilweise hast du Mulesoft geschrieben)
  * ApiKit Router (teilweise hast du API Kit Router geschrieben)
* Du verwendest einige Bilder von Quellcode. Binde hier den Quellcode bitte direkt als Codeblock ein.
* Du wechselst teilweise deinen Schreibstil, mal schreibst aus deiner Sicht (Z. 53), mal verwendest du Formulierungen mit "man" (Z. 37) und mal verwendest du eine Pluralformulierung mit "wir" (Z. 104). Achte bitte darauf, dass das über deinen Beitrag hinweg einheitlich ist.

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Weiterhin erkennt das geschulte Auge eine Maven POM Datei. 
```suggestion
Weiterhin erkennt das geschulte Auge eine Maven-POM-Datei. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Auch MuleSoft stellt das, ein oder andere, Repository selbst zur Verfügung. 
```suggestion
Auch MuleSoft stellt das ein oder andere Maven-Repository selbst zur Verfügung. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Teilweise sind diese, wie beispielsweise das Nexus Repository,  lizenzpflichtig. 
```suggestion
Teilweise sind diese wie beispielsweise das Nexus-Repository lizenzpflichtig. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Viele davon, wie der HTTP Connector oder der APIKit Router, werden standardmäßig bei der Neu Anlage eines Projektes eingetragen. 
```suggestion
Viele davon, zum Beispiel der HTTP Connector oder der APIKit Router, werden standardmäßig beim Erstellen eines Projektes eingetragen. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Auch erkennt man beim letzten Eintrag die Einbindung einer API Referenz - in dem Fall handelt es sich um die eigene API Definition. 
```suggestion
Auch erkennt man beim letzten Eintrag die Einbindung einer API-Referenz - in dem Fall handelt es sich um die eigene API-Definition. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Dies repräsentiert ein ganz typisches Implementierungsszenario - die API wird im API Designer entworfen, im Exchange bekannt gemacht und von dessen Repository Eintrag direkt in Maven eingebunden. 
```suggestion
Dies repräsentiert ein ganz typisches Implementierungsszenario - die API wird im API Designer entworfen, im Exchange bekannt gemacht und von dessen Repositoryeintrag direkt in Maven eingebunden. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Auch hier können wir auf ein bekanntes und beliebtes Java Framework zurückgreifen. 
```suggestion
Auch hier können wir auf ein bekanntes und beliebtes Java-Framework zurückgreifen. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Der Dateiname verrät es natürlich bereits - es handelt sich in dem Fall um Log4J in der Version 2. In der Konfigurationsdatei definiert man dann, wie gewohnt, seine eigenen Logger. Und ja, auch MuleS
```suggestion
Der Dateiname verrät es natürlich bereits - es handelt sich in dem Fall um Log4J in der Version 2. In der Konfigurationsdatei definiert man dann, wie gewohnt, seine eigenen Logger. Und ja, auch MuleSoft hatte mit der im letzten Jahr auftretenden globalen Sicherheitslücke zu kämpfen - aber auch hier helfen Versionsupdates:-) 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Spätestens seit Spring Boot beliebt und bekannt, ist es auch in Mulesoft möglich eigene Stage Properties und eine „common“ Property Datei zu definieren. 
```suggestion
Spätestens seit Spring Boot beliebt und bekannt, ist es auch in MuleSoft möglich, eigene Stage Properties und eine "common"-Property-Datei zu definieren. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +In dem Fall wird eine HTTP Connector Konfiguration soweit vordefiniert, dass sie dynamisch, je nach hinterlegter Stage, auf die host und Port Informationen zugreifen kann. 
```suggestion
In dem Fall wird eine HTTP-Connector-Konfiguration soweit vordefiniert, dass sie dynamisch, je nach hinterlegter Stage, auf die Host- und Port-Informationen zugreifen kann. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Genauso kann aber auch unter Dataweave auf die Property Konfiguration zugegriffen werden. 
```suggestion
Genauso kann aber auch in DataWeave auf die Property-Konfigurationen zugegriffen werden. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Hier macht man aber typischerweise von der „p“ DataWeave Funktion Gebrauch: 
```suggestion
Hier macht man aber typischerweise von der DataWeave-Funktion `p` Gebrauch: 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Hier wurde beispielsweise im JSON Zweig „headers“ ==> „client_id“ die property „p.service.client.id“ dynamisch aufgerufen. 
```suggestion
Hier wurde beispielsweise im JSON-Zweig `"headers" ==> „client_id“` die Property `p.service.client.id` dynamisch aufgerufen. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Dieser kann beispielsweise extern ausgelesen oder über einen Start Parameter mitgegeben werden. 
```suggestion
Dieser kann beispielsweise extern ausgelesen oder über einen Startparameter mitgegeben werden. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Bei diesen ganzen Verfahren können auch die, aus Java allseits bekannten und beliebten, KeyStores und TrustStores eingesetzt und eingebunden werden. 
```suggestion
Bei diesem ganzen Verfahren können auch die aus Java allseits bekannten und beliebten KeyStores und TrustStores eingesetzt und eingebunden werden. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Im Java Umfeld ist das Spring Framework in aller Munde und mittlerweile, spätestens durch Spring Boot, zum Standard geworden. 
```suggestion
Im Java-Umfeld ist das Spring-Framework in aller Munde und mittlerweile, spätestens durch Spring Boot, zum Standard geworden. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Die dazugehörigen Spring Beans können natürlich auch in MuleSoft selbst definiert werden. Neben der ersichtlichen Datenbank Konfiguration können auch Authentifizierungsprovider und Filter definiert w
```suggestion
Die dazugehörigen Spring Beans können natürlich auch in MuleSoft selbst definiert werden. Neben der ersichtlichen Datenbankkonfiguration können auch Authentifizierungsprovider und Filter definiert werden. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Neben der Möglichkeit Tests, mit Hilfe der hauseigenen Munit Technologie, zu zeichnen oder zeichnen zu lassen gibt es auch mit MuleSoft die Möglichkeit Junit Tests zu schreiben. Man kann nun auch mit
```suggestion
Neben der Möglichkeit, Tests mit Hilfe der hauseigenen MUnit-Technologie zu zeichnen oder zeichnen zu lassen, gibt es auch mit MuleSoft die Möglichkeit, JUnit-Tests zu schreiben. Man kann nun auch mit seinem gesamten Java-Wissen glänzen :-) 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +In dem vorliegenden Beispiel wird dabei ein Flow mit dem Bezeichnet „myFlow“ gestartet und vorher ein SQL Select gemockt. 
```suggestion
In dem vorliegenden Beispiel wird dabei ein Flow mit dem Bezeichner "myFlow" gestartet und vorher ein SQL Select gemockt. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +In dem Fall wird das Result mit dem vordefinierten Ergebnis „815-OA“ gefüllt und am Ende über ein Assert geprüft. 
```suggestion
In dem Fall wird das Result mit dem vordefinierten Ergebnis "815-OA" gefüllt und am Ende über ein Assert geprüft. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Teilweise geliebt, teilweise akzeptiert haben wir ein großes Sammelsurium von Tools und Technologien gleich an Board und müssen uns beispielweise nicht mehr mit der Implementierung von Connectoren zu
```suggestion
Teilweise geliebt, teilweise akzeptiert haben wir ein großes Sammelsurium von Tools und Technologien gleich an Board und müssen uns beispielweise nicht mehr mit der Implementierung von Konnectoren zu den einzelnen Systemen auseinandersetzen. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> + - oder deren komplizierte Struktur in Gänze begreifen. 
```suggestion
Auch müssen wir nicht die komplizierte Struktur dieser Systeme in Gänze begreifen. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Es nimmt uns bei der Integration von anderen Systemen als Middleware und Rest API Lösung viel ab. 
```suggestion
Es nimmt uns bei der Integration von anderen Systemen als Middleware und Rest-API-Lösung viel ab. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Das merke ich auch - und gerade - in meinen jetzigen Java Projekt, bei dem die Entwicklung der Connectoren Stunden/Tage und nicht Minuten in Anspruch nimmt.
```suggestion
Das merke ich auch - und gerade - in meinem jetzigen Java-Projekt, bei dem die Entwicklung der Konnektoren Stunden/Tage und nicht Minuten in Anspruch nimmt.
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Sicherlich muss man auch festhalten das es für „Hardcore Entwickler“ in der Regel zu limitiert ist und die hauseigene Script Sprache „Dataweave“ eher wie ein missglückter Versuch , auch diese Gruppe
```suggestion
Sicherlich muss man auch festhalten, dass es für Spezialfälle in der Regel zu limitiert ist und die hauseigene Skriptsprache DataWeave eher wie ein missglückter Versuch, auch diese Gruppe abzudecken, wirkt. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Ein „Test-Driven“ Ansatz ist auch praktisch unmöglich zu realisieren und MuleSoft selber weiß auch das Testing nicht gerade ihre Parade- Disziplin ist. 
```suggestion
Ein "Test-Driven"-Ansatz ist auch praktisch unmöglich zu realisieren und MuleSoft selber weiß auch das Testing nicht gerade ihre Paradedisziplin ist. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Wenn man aber über diese Nachteile hinweg sieht, integrieren möchte und bereits Salesforce im Projektkontext einsetzt lohnt sich der Blick Richtung MuleSoft auf jeden Fall. 
```suggestion
Wenn man aber über diese Nachteile hinweg sieht, integrieren möchte und bereits Salesforce im Projektkontext einsetzt, lohnt sich der Blick Richtung MuleSoft auf jeden Fall. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Auch ein technisch eher unbegabter Kunde wird eure Flows verstehen. Ihr müsst euch in eurem Projekt nicht mit Integrationen herum rumschlagen, sondern könnt euch ganz auf die Implementierung der Busi
```suggestion
Auch ein technisch eher unbegabter Kunde wird eure Flows verstehen. Ihr müsst euch in eurem Projekt nicht mit Integrationen rumschlagen, sondern könnt euch ganz auf die Implementierung der Businesslogik konzentrieren. 
```

2022-11-02 08:25 UTC, jo2 commented on _posts/2022-10-26-mulesoft-for-java-developers.md
> +Und schlussendlich könnt Ihr im geliebten Java Umfeld bleiben - Lets give it a try :-) 
```suggestion
Und schlussendlich könnt ihr im geliebten Java-Umfeld bleiben - Lets give it a try :-) 
```

2023-01-20 12:04 UTC, jo2 commented
@tonyHorst wie ist hier der Stand?

2023-09-01 11:26 UTC, closed without merging

2023-09-01 11:26 UTC, jo2 commented
Wegen Inaktivität geschlossen