Flutter Beitrag
adessoSE/devblog pull request #268
Opened 2022-12-07 12:42 UTC by Arnold-Adesso

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#online-preview) geprüft 
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [x] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2022-12-07 12:43 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-12-09 08:09 UTC, jo2 requested changes
Einige Sachen habe ich dir noch angemerkt. Außerdem:
* Die Pipeline schlägt fehlt, weil du in deinem Artikelnamen eine Raute verwendest. Das ist in URLs ein Sonderzeichen für Anchor-Links und nicht mitten in der URL erlaubt. Entsprechend ist das Zeichen nicht im Dateinamen erlaubt. Das musst du noch ändern.
* Der Artikel wirkt für mich noch ein bisschen dünn, kannst du vielleicht nochmal ein Beispiel einfügen, das zeigt, wie die Theorie umgesetzt wird? Hier wäre es gut, wenn das Beispiel etwas tiefer geht, als nur "Hello World", bspw. kannst du auch noch auf das Testen eingehen.

2022-12-09 08:09 UTC, jo2 commented on _posts/2022-12-01-Flutter#1–Entwicklung-und-Abgrenzung.md
> +Jedoch besitzt Flutter auch eine große Community, die etliche Packages zur Verfügung stellen. Wie etwa das flutter\_bloc-Package, die die Implementierung des BLoC (Business Logic Component) -Designmu
```suggestion
Darüber hinaus besitzt Flutter auch eine große Community, die etliche Packages zur Verfügung stellt. Hierzu gehört beispielsweise das flutter_bloc-Package, das die Implementierung des BLoC (Business Logic Component)-Designmusters erleichtert.
```

2022-12-09 08:09 UTC, jo2 commented on _posts/2022-12-01-Flutter#1–Entwicklung-und-Abgrenzung.md
> +Google hat mit Flutter einen neuen Ansatz für Multi-Plattform-Entwicklung gemacht. In der Mobile-Entwicklung hat Flutter schon einen großen Marktanteil bekommen, auf den anderen Plattformen wird sich
```suggestion
Google hat mit Flutter einen neuen Ansatz für Multi-Plattform-Entwicklung gemacht. In der Mobile-Entwicklung hat Flutter schon einen großen Marktanteil erreicht, auf den anderen Plattformen wird sich das noch zeigen. Sowohl die Integration der Google-Services als auch die große Community unterstützen Flutter immer besser und leichter zu werden.
```
Was heißt hier, leichter zu werden?

2022-12-09 08:09 UTC, jo2 commented on _posts/2022-12-01-Flutter#1–Entwicklung-und-Abgrenzung.md
> +Ich gehe davon aus, dass Flutter immer mehr an Bedeutung in der Industrie findet, große Unternehmen wie BMW und Toyota nutzen Flutter heute schon.
```suggestion
Ich gehe davon aus, dass Flutter immer mehr an Bedeutung in der Industrie findet, da große Unternehmen wie BMW und Toyota Flutter heute schon nutzen.
```

2022-12-09 08:09 UTC, jo2 commented on _posts/2022-12-01-Flutter#1–Entwicklung-und-Abgrenzung.md
> +Abbildungen-Quellen:
```suggestion
Abbildungsquellen:
```
Überschriften s.o.

2022-12-09 08:09 UTC, jo2 commented on _posts/2022-12-01-Flutter#1–Entwicklung-und-Abgrenzung.md
> +<https://medium.com/flutter/introducing-flutter-3-5eb69151622f>
Kannst du die Links bitte jeweils an das entsprechende Bild schreiben?

2022-12-12 20:31 UTC, Arnold-Adesso commented on _posts/2022-12-01-Flutter#1–Entwicklung-und-Abgrenzung.md
> +![](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Verlauf.png) Heute im Jahr 2022 wird der Begriff React Native nur zu 30% gesucht im Vergleich zu Flutter.
Das ist der Vergleichsalgorithmus von Google, wenn man dort 2 Begriffe eingibt. Natürlich ist dieser Vergleich relativ zu dem höheren . D.h. flutter wurd z.B. 10 gesucht =100% und react native nur 3 =30%

2022-12-12 20:49 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-12-12 20:51 UTC, Arnold-Adesso commented on _posts/2022-12-01-Flutter#1–Entwicklung-und-Abgrenzung.md
> +![](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/FlutterLogo.png)
wie genau wird das gemacht ? 
![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/FlutterLogo.png,"Flutter-Logo")

2022-12-12 20:51 UTC, Arnold-Adesso commented on _posts/2022-12-01-Flutter#1–Entwicklung-und-Abgrenzung.md
> +![](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/FlutterLogo.png)
"   ![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/FlutterLogo.png,"Flutter-Logo") "

2022-12-12 20:52 UTC, Arnold-Adesso commented on _posts/2022-12-01-Flutter#1–Entwicklung-und-Abgrenzung.md
> +![](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/FlutterLogo.png)
![Alt]
(/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/FlutterLogo.png,"Flutter-Logo")

2022-12-12 20:58 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2022-12-13 11:56 UTC, jo2 requested changes
Einige Sachen sind noch drin, vor allem musst du aber noch die nicht erlaubten Zeichen im Name 
des Asset-Order entfernen.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Flutter vs. React Native. Hybride Appentwicklung bieten hierzu eine elegante und effiziente Alternative plattformübergreifende Software zu schreiben. Flutter und React Native sind in diesem Markt zwe
```suggestion
Hybride Appentwicklung bietet eine elegante und effiziente Möglichkeit, plattformübergreifende Software zu schreiben. Flutter und React Native sind in diesem Markt zwei sehr populäre Frameworks, die man für die Cross-Platform-Entwicklung definitiv kennen sollte. Trotz technologischen Unterschieden ermöglichen beide Frameworks die Erstellung von Apps für verschiedene Endgerätsysteme mit nur einer Codebasis. In diesem Artikel werden wir sowohl die Unterschiede als auch die Vor- und Nachteile beider Framework kennenlernen. Außerdem beschäftigen wir uns mit der Entwicklung von Flutter und seiner Popularität. 
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/FlutterLogo.png,"Flutter-Logo")
Alt-Tags werden in Markdown so angegeben, so, wie du es gemacht hast, wird der Title gesetzt:
```suggestion
![Flutter-Logo](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/FlutterLogo.png)
```
Hier musst du die URL auch noch korrigieren.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +#Flutter #1 - build apps for every screen
Wofür hast du hier das `#1` in der Überschrift? Du kannst gut diese Überschrift und die nächste kombinieren, da beide fast gleich sind und hier nur ein Bild in dem zugehörigen Abschnitt steht.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +[Flutter] https://flutter.dev/ ist ein Open Source Framework von Google zur Entwicklung von nativen Anwendungen für verschiedene Plattformen. Mit Flutter können Anwendungen für Mobile, Web und Deskto
```suggestion
[Flutter](https://flutter.dev/) ist ein Open-Source-Framework von Google zur Entwicklung von nativen Anwendungen für verschiedene Plattformen. Mit Flutter können Anwendungen für Mobile, Web und Desktop erstellt werden.  In erster Linie wird Flutter für die Android- und iOS-Entwicklung verwendet.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Heute, im Jahre 2022, läuft Flutter mit der Version 3.0, dabei wurde die Unterstützung für MacOS- und Linux-Desktop-Anwendungen bereitgestellt und somit ist die Veröffentlichung nun auf allen Desktop
```suggestion
Heute, im Jahre 2022, läuft Flutter in der Version 3.0, dabei wurde die Unterstützung für MacOS- und Linux-Desktop-Anwendungen bereitgestellt und somit ist die Veröffentlichung nun auf allen Desktop-Plattformen möglich.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Timeline.png "Timeline")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Code.png ,"Widget-Code")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Fluttervsreact.png,"Flutter vs React")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Verlauf.png,"Google Trends")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Region.png,"Google Trends Regionen")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Overview.png,"Flutter Architektur")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Settings-Widgets.png,"Settings-Image")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Icons.png,"Widget-Baum")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Layout.png,"Layout")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +![Alt](/assets/images/posts/Flutter#1–Entwicklung-und-Abgrenzung/Popularität.png,"Examples Apps")
Bild, s.o.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +https://medium.com/flutter/introducing-flutter-3-5eb69151622f
Ich bin nochmal andere Blogbeiträge durchgeguckt, nahezu kaum jemand gibt die Quellen für bspw. Bilder an. Von mir aus kannst du sie auch raus lassen.

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Fluter unterstützt dabei folgende Versionen auf den Plattformen.
```suggestion
Fluter unterstützt folgende Versionen auf den Plattformen.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Flutter wurde 2017 von Google vorgestellt und 2018 offiziell veröffentlicht und ist somit ein relativ neues und modernes Framework. Es basiert dabei auf der von Google entwickelten Programmiersprache
```suggestion
Flutter ist ein relativ neues und modernes Framework. Es basiert auf der von Google entwickelten Programmiersprache Dart. Dabei steht Flutter bei der hybriden Appentwicklung in direkter Konkurrenz zu React Native.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +React Native wurde 2015 von Facebook entwickelt und ist das am weitverbreitetsten Framework für die Entwicklung von hybriden Apps. Dabei basiert das Framework auf der Programmiersprache JavaScript.
```suggestion
React Native wurde 2015 von Facebook entwickelt und ist das am weitesten verbreitete Framework für die Entwicklung von hybriden Apps. Das Framework basiert auf der Programmiersprache JavaScript.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Flutter verwendet hierbei im Code sogenannte Widget, diese werden für alle Formen, Grafiken und Animationen, wie hier z.B. Row und Text verwendet.
Diese Zeile würde ich unter den Part zu Flutter schreiben, sodass du hier zwei Absätze hast, einen zu Flutter und einen zu React Native. Außerdem gehst du im Abschnitt Abgrenzung schon auf die Widgets ein, die würde ich dann hier raus lassen.
```suggestion
Flutter verwendet im Code sogenannte Widgets. Diese werden für alle Formen, Grafiken und Animationen, hier z. B. Row und Text, verwendet.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +React Native verwendet für die Beschreibung der UI sogenannte Tags, diese bauen dann auf den nativen Komponenten für Android und iOS auf.
```suggestion
React Native verwendet für die Beschreibung der UI sogenannte Tags. Diese bauen dann auf den nativen Komponenten für Android und iOS auf.  
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Im Gegensatz zu anderen vergleichbaren Technologien, wie z. B. React Native hat Flutter einen neuen Ansatz. Flutter-Apps benutzen Widgets. Anders als normalerweise handelt es sich hier aber nicht um
```suggestion
Im Gegensatz zu anderen vergleichbaren Technologien wie React Native verwendet Flutter einen neuen Ansatz. Flutter-Apps benutzen Widgets. Anders als normalerweise handelt es sich hier aber nicht um sogenannte Native-Widgets (OEM), die schon vom jeweiligen mobilen Endgerät zur Verfügung gestellt werden. Stattdessen werden diese Widgets erstellt und benötigen somit keine Brücke (Bridge), sodass die Leistungsprobleme der Bridge vermieden werden können. 
```
Wer erstellt die Wirdgets?

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +In einem Zeitraum von 2017 bis 2022 wurden die beiden Suchbegriffe „Flutter“ und „React Native“ in Deutschland miteinander verglichen.  In diesem Diagramm ist zu erkennen, dass Flutter Anfang 2019 Re
```suggestion
In einem Zeitraum von 2017 bis 2022 wurden die beiden Suchbegriffe "Flutter" und "React Native" in Deutschland miteinander verglichen.  In diesem Diagramm ist zu erkennen, dass Flutter Anfang 2019 React Native mit den Suchanfragen überholt. Zu diesem Zeitpunkt befand sich Flutter in der Version 1.5. 
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Heute im Jahr 2022 wird der Begriff React Native nur zu 30% gesucht im Vergleich zu Flutter.
Was bedeutet hier die Prozentzahl?
```suggestion
Heute, im Jahr 2022, wird der Begriff React Native im Vergleich zu Flutter nur zu 30% gesucht.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Der weltweite Vergleich zeigt einen ähnlichen Trend. Der Unterschied zwischen Flutter und React Native im Jahr 2022 befindet sich auch hier bei ca. 70%.
Was bedeutet hier die Prozentzahl?

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +#Framework:
```suggestion
## Framework: 
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +- Die Hot Reload-Funktion ist ein sehr nützliches Feature.
Ist das nicht bei nahezu jedem Frontend-Framework dabei?
```suggestion
- Die Hot-Reload-Funktion ist ein sehr nützliches Feature.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +- Alle Plattformen werden unterstützt
```suggestion
- Alle Plattformen werden unterstützt.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Flutter ist Googles neustes Cross-Plattform-Framework, das mit der Programmiersprache Dart, welches auch von Google entwickelt wird, sehr gut zusammenpasst. Meistens werden Flutter- und Dart-Major-Up
```suggestion
Flutter ist Googles neustes Cross-Plattform-Framework, das mit der Programmiersprache Dart, welche auch von Google entwickelt wird, sehr gut harmoniert. Beispielsweise werden Flutter- und Dart-Major-Updates meistens gleichzeitig veröffentlicht. 
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Google hatte mit Flutter einen schwierigen Start gehabt, jedoch ist mit der Version 2.0, die im März 2021 erschienen ist, ein stetig steigendes Interesse geweckt worden. Die Release-Veröffentlichunge
```suggestion
Google hatte mit Flutter einen schwierigen Start gehabt, jedoch ist mit der Version 2.0 das Interesse an dem Framework stetig gewachsen. Die Release-Veröffentlichungen fanden in immer kürzeren Abständen statt, sodass nach etwas mehr als einem Jahr die Version 3.0 veröffentlicht wurde, in der nun alle Plattformen unterstützt werden. 
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Flutter macht die Entwicklung von Apps auf mehreren Plattformen leicht. Dabei wird Flutter primär für die Entwicklung von Android und iOS-Apps verwendet. Der Platzhirsch React Native bekommt immer me
Existieren 150.000 Apps im Store, die Flutter in der Version 2.0 verwenden oder wie ist das gemeint?
```suggestion
Flutter macht die Entwicklung von Apps auf mehreren Plattformen leicht. Dabei wird Flutter primär für die Entwicklung von Android- und iOS-Apps verwendet. Der Platzhirsch React Native bekommt hier immer mehr Konkurrenz und verliert immer mehr Marktanteile. Mit der Version 2.0 existierten weit mehr als 150.000 Apps von Flutter im Play Store. 
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Die Entwicklung von Desktop-Anwendungen war früher nur mit verschiedenen Programmiersprachen möglich. Flutter ermöglicht es jetzt mit einer Code-Basis auf mehreren Plattformen gleichzeitig zu veröffe
```suggestion
Die Entwicklung von Desktop-Anwendungen war früher nur mit verschiedenen Programmiersprachen möglich. Flutter ermöglicht es, jetzt mit einer Codebasis auf mehreren Plattformen gleichzeitig zu veröffentlichen. Da die Unterstützung von Desktop-Anwendungen erst vor Kurzem bereitgestellt wurde, muss sich Flutter hier noch beweisen.  
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Die große Unterstützung von Google für Flutter wurde bei der Google I/O 2022 sehr deutlich, neben etlichen neuen Features, die es in die Version 3.0 geschafft haben, kriegen Googles Hausmarken wie z.
```suggestion
Die große Unterstützung von Google für Flutter wurde bei der Google I/O 2022 sehr deutlich. Neben etlichen neuen Features, die es in die Version 3.0 geschafft haben, kriegen Googles Hausmarken wie Firebase immer mehr Unterstützung für die Integration. Dabei werden Packages von Google veröffentlicht, die die Services wie Authentication, Firestore Database, Realtime Database, Storage oder Analytics anbieten. 
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Google hat mit Flutter einen neuen Ansatz für Multi-Plattform-Entwicklung gemacht. In der Mobile-Entwicklung hat Flutter schon einen großen Marktanteil erreicht, auf den anderen Plattformen wird sich
```suggestion
Google hat mit Flutter einen neuen Ansatz für Multi-Plattform-Entwicklung implementiert. In der Mobile-Entwicklung hat Flutter schon einen großen Marktanteil erreicht, auf den anderen Plattformen wird sich das noch zeigen. Sowohl die Integration der Google-Services als auch die große Community unterstützten Flutter, immer besser und anfängerfreundlicher zu werden.
```

2022-12-13 11:56 UTC, jo2 commented on _posts/2022-12-01-Flutter–Entwicklung-und-Abgrenzung.md
> +Ich gehe davon aus, dass Flutter immer mehr an Bedeutung in der Industrie findet,da große Unternehmen wie BMW und Toyota Flutter heute schon nutzen.
```suggestion
Ich gehe davon aus, dass Flutter immer mehr an Bedeutung in der Industrie findet, da große Unternehmen wie BMW und Toyota Flutter heute schon nutzen.
```

2023-09-01 11:24 UTC, jo2 commented
@Arnold-Adesso arbeitest du hier noch dran?

2023-09-06 14:15 UTC, closed without merging