Digi mhb
adessoSE/devblog pull request #272
Opened 2023-02-11 21:26 UTC by c0c0bird

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2023-02-11 21:27 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-11 21:33 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-11 21:38 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-11 21:40 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-11 21:42 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-11 21:46 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-11 21:53 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-11 21:59 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-11 22:08 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-11 22:10 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-14 15:19 UTC, jo2 requested changes
Ein sehr interessanter Artikel, ein paar Kleinigkeiten habe ich dir noch angemerkt.

2023-02-14 15:19 UTC, jo2 commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Vorsicht ist noch geboten bei Koloniebrütern, wie etwa einer Hecke voller Spatzen, oder Wasservögeln die sich einen See teilen.
```suggestion
Vorsicht ist noch geboten bei Koloniebrütern, wie etwa einer Hecke voller Spatzen, oder Wasservögeln, die sich einen See teilen.
```

2023-02-14 15:19 UTC, jo2 commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Ohne deren kostenlose Expertise wäre ein Überblick über europaweite Umweltdaten kaum möglich.
Was mich hier persönlich interessieren würde ist, wie lösen andere Länder dieses Problem? Arbeiten die auch mit ehrenamtlichen? Gibt es dort auch ähnliche Digitalisierungsstrategien? Könnte man ggf. voneinander lernen oder profitieren?

2023-02-14 21:58 UTC, c0c0bird commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Ist die Wirklichkeit zu komplex ist, so wird sie auf vergleichbare Zahlen, sogenannte Indikatoren, reduziert.
Danke, ist korrigiert.

2023-02-14 21:59 UTC, c0c0bird commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Ebenfalls aus dem Monitoring häufiger Brutvögel.
Ich hab den Teil als ein Satz hinter den Folgeabsatz gehängt. So passt es wirklich besser.

2023-02-14 21:59 UTC, c0c0bird commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +An den DDA eingeschickt wird letzten Endes eine Excel-Tabelle mit den Anzahlen der Reviere pro Vogelart und Landschaftstyp.
Das hatte ich wohl vergessen, ist jetzt weiter oben drin.

2023-02-14 22:00 UTC, c0c0bird commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Schließlich zählten Sie die Reviere durch und trugen das Ergebnis in den Zählbogen sein.
Danke, ist korrigiert.

2023-02-14 22:02 UTC, c0c0bird commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Das normale Frontend war aber nur eingeschränkt geeignet, unter anderem erforderte das MhB drei große Änderungen:
"MhB" führe ich jetzt im ersten Satz unter der Überschrift "Monitoring häufiger Brutvögel" ein.

2023-02-14 22:02 UTC, c0c0bird commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Diese erhält als Wert einen regulären Ausdruck, der den Monat aus dem Datumsfeld herauspickt (siehe Abbildung) und zusätzlich den Atlascode.
Danke, auch das ist korrigiert.

2023-02-14 22:03 UTC, c0c0bird commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Vorsicht ist noch geboten bei Koloniebrütern, wie etwa einer Hecke voller Spatzen, oder Wasservögeln die sich einen See teilen.
Danke, auch das ist korrigiert.

2023-02-14 22:12 UTC, c0c0bird commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Ohne deren kostenlose Expertise wäre ein Überblick über europaweite Umweltdaten kaum möglich.
Einen Absatz über freiwillige Vogelzählungen im Rest der EU habe ich eingefügt, ansonsten müsste ich über die Frage einen Extraartikel schreiben. Denn das Ornitho-System ist in mehreren Ländern etabliert, über die anderen gibt es Informationen nur in Landessprache. Und dann gibt es ja noch viel mehr Indikatoren mit ganz anderen Datenquellen. Eigentlich müsste man ein ganzes Buch darüber schreiben. ;)

2023-02-14 22:13 UTC, c0c0bird commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Versierte "Birdnerds" dürfen die selbst erfassten Rohdaten auch auf angenehmere Art verarbeiten.
Okay, Eigenwerbung ist drin!

2023-02-16 17:29 UTC, jo2 commented on _posts/2023-02-03-digitale-vogelzaehlung.md
> +Ohne deren kostenlose Expertise wäre ein Überblick über europaweite Umweltdaten kaum möglich.
Das passt so, interessant, dass es so unterschiedlich in Europa ist.

2023-02-16 17:31 UTC, jo2 submitted a review, later dismissed
Von meiner Seite ist der Artikel soweit fertig. 
@c0c0bird kannst du noch einen Rebase auf den `master`-Branch machen, dann meckert der Blogpost-Validator auch nicht mehr.
@acetous möchtest du noch drüber gucken? Ansonsten kann der Artikel nach dem Rebase zur Veröffentlichung gehen.

2023-02-16 17:40 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-02-16 17:43 UTC, c0c0bird commented
Der Rebase auf 'master' ist erledigt, jetzt laufen alle Checks wieder durch.

2023-02-16 17:44 UTC, jo2 commented
@c0c0bird da ist leider was schiefgegangen, du hast aktuell jetzt noch Blogposts von zwei Kollegen mit drin. Ich vermute, du hast den Rebase nicht auf den adessoSE/devblog:master sondern auf deinen lokalen master gemacht, kannst du dir das nochmal ansehen?

2023-02-16 17:54 UTC, c0c0bird commented
@jo2 Die fremden Dateien sind jetzt wieder raus. Ich hatte zuerst den lokalen master gegen den adessoSE/devblog:master aktualisiert und danach das Rebase innerhalb von c0c0bird/devblog gemacht.

2023-02-16 17:56 UTC, jo2 submitted a review, later dismissed

2023-04-13 11:29 UTC, jo2 commented
@acetous wie sieht es hier aus?

2023-04-28 06:31 UTC, jo2 approved these changes

2023-04-28 06:49 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-28 07:01 UTC, jo2 commented
@c0c0bird es gab leider einige Konflikte mit dem Branch. Den Artikel habe ich jetzt lokal in den master gebracht, ich schließe daher den PR.

2023-04-28 07:01 UTC, closed without merging