ATDD with Spring Boot and Cucumber
adessoSE/devblog pull request #275
Opened 2023-04-03 12:21 UTC by bjoern-thalheim

Im Preview ist mir folgendes aufgefallen: ich benutze Blockquotes (> ) für ein Zitat aus Wikipedia sowie zwei kleine Blöcke, die ich wie eine Infobox darstellen wollen würde. Mir ist in der Jekyll Dokumentation (https://cloudcannon.com/cheat-sheets/jekyll/) kein Format aufgefallen, welches dafür gut geeignet ist. Habt ihr da für die Formatierung einen Hinweis?

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [x] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2023-04-03 12:31 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-03 12:33 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-03 17:14 UTC, jo2 requested changes
Der Artikel ist ziemlich interessant. Ein paar Kleinigkeiten habe ich dir noch angemerkt. Zu deiner Frage im Bezug auf die Formatierung von Block quotes: Jekyll unterstützt Block quotes so, wie du sie geschrieben hast. Lediglich das CSS des adresso-Blog macht für Block quotes keinen Unterschied. Du kannst es aber so lassen, falls das mal implementiert wird, ist es hier dann direkt richtig.,

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +    @PostMapping("/{thought}")
Das wäre als Body besser, sonst kann es Konflikte mit anderen URLs geben. Es ist weder ein Identifier, noch ein Filter, was eine Path Variable oder einen Parameter rechtfertigen würden.

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +Now, if we let Maven run, during the test run an error will pop up that the Glue-Code is missing.
```suggestion
Now, if we let Maven run, during the test run an error will pop up that the glue code is missing. 
```

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +Let's write this glue code (src/test/java/de/adesso/thalheim/gtd/CaptureStepDefinitions.java):
Kannst du hier den Link ins Repo angeben?

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +Before even starting on our feature, let’s define the acceptance tests of our feature (src/test/resources/features/collect-thought.feature):
```suggestion
Before even starting on our feature, let's define the acceptance tests of our feature (src/test/resources/features/collect-thought.feature):
```

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +> Of course, one could have just @Inject the REST controller and use plain Java for testing, which would have made things easier.
```suggestion
> Of course, one could have just `@Inject` the REST controller and use plain Java for testing, which would have made things easier.
```

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +We need to implement the controller, so let's write a this in a normal TDD style with a test case first (src/test/java/de/adesso/thalheim/gtd/controller/InboxControllerTest.java):
```suggestion
We need to implement the controller, so let's write this in normal TDD style with a test case first (src/test/java/de/adesso/thalheim/gtd/controller/InboxControllerTest.java):
```
Kannst du hier den Link ins Repo angeben?

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +Now we can finish writing the Controller, Entity, Repository etc. (src/main/java/de/adesso/thalheim/gtd/controller/InboxController.java, src/main/java/de/adesso/thalheim/gtd/controller/Thought.java,
```suggestion
Now we can finish writing the controller, the entity, the repository etc. (src/main/java/de/adesso/thalheim/gtd/controller/InboxController.java, src/main/java/de/adesso/thalheim/gtd/controller/Thought.java, src/main/java/de/adesso/thalheim/gtd/repository/ThoughtRepository.java):
```
Kannst du hier die Links ins Repo angeben?

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +    @PostMapping("/{thought}")
Path Variable, s.o.

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +
Kannst du hier draus drei Codeblöcke machen, dann ist das etwas übersichtlicher.

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +Of course, you would never expose an @Entity as the result type of a REST call.
```suggestion
Of course, you would never expose an `@Entity` as the result type of a REST call.
```

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +That's it. We have driven a small feature implementation  by writing an acceptance test scenario and glue code to test the behavior of a part of our application first in Cucumber.
```suggestion
That's it. We have driven a small feature implementation by writing an acceptance test scenario and glue code to test the behavior of a part of our application first in Cucumber.
```

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +Before writing a single line of productive code, I took the time in this dummy project that the execution of unit tests, @SpringBootTest, and Cucumber tests were possible.
```suggestion
Before writing a single line of productive code, I took the time and made sure that in this dummy project the execution of unit tests, `@SpringBootTest`, and Cucumber tests were possible.
```

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +I have kept the acceptance tests free of details which are not relevant to them, hence raising refactoring safety. I would try to do the same with regular @SpringBootTests.
```suggestion
I have kept the acceptance tests free of implementation details which are not relevant to them, hence raising refactoring safety. I would try to do the same with regular `@SpringBootTests`.
```

2023-04-03 17:14 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +If you like, you can see all code here: [Demo Code](https://github.com/bjoern-thalheim/cucumber_demo).
```suggestion
If you like, you can see all code [in this repository](https://github.com/bjoern-thalheim/cucumber_demo).
```

2023-04-03 17:14 UTC, jo2 commented on _data/authors.yml
> +  bio: "Björn ist Softwareentwickler und Architekt mit einem großen Interesse an Qualität, insbesondere TDD, Clean Code und Architekturthemen."
```suggestion
  bio: "Björn ist Softwareentwickler und Architekt mit einem großen Interesse an Softwarequalität, insbesondere durch TDD, Clean Code und Architekturthemen."
```

2023-04-03 17:15 UTC, jo2 requested changes
Der Artikel ist ziemlich interessant. Ein paar Kleinigkeiten habe ich dir noch angemerkt. Zu deiner Frage im Bezug auf die Formatierung von Block quotes: Jekyll unterstützt Block quotes so, wie du sie geschrieben hast. Lediglich das CSS des adresso-Blog macht für Block quotes keinen Unterschied. Du kannst es aber so lassen, falls das mal implementiert wird, ist es hier dann direkt richtig.

2023-04-05 07:00 UTC, bjoern-thalheim commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +            <scope>provided</scope>
Da habe ich noch gar nicht darüber nachgedacht.
Wenn ich https://projectlombok.org/setup/maven und https://stackoverflow.com/questions/29385921/maven-scope-for-lombok-compile-vs-provided richtig verstanden habe, ist die Lombok-Dependency provided, weil sie beim Kompilieren den Bytecode verändert, danach aber nicht mehr benötigt wird (also keine dependency des fertigen Jar ist). Laut dem Stackoverflow Link sollte sie m.E. entweder provided sein oder compile mit optional=true. Ich würde da hier nicht hinein gehen. Es funktioniert offensichtlich und Lombok ist ja auch kein Fokus des Artikels,

2023-04-05 07:06 UTC, bjoern-thalheim commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +* We want the Application to start up with an external database (on my local machine, I let a PostgreSQL DB run in Docker)
Das mit der DB sehe ich anders - solang man Standard SQL benutzt funktioniert das m.E. zu 99% in H2 genauso wie in PostgreSQL, MySQL oder Oracle. Und im Test eine H2 zu verwenden, auch wenn man in Prod was anderes benutzt ist einfach der leichtere Weg fürs Erste. Wollte man das ändern, müsste man eine PostgreSQL DB in einem Testcontainer verwenden. Könnte man machen, ist auch cool. Aber auch irgendwie für diesen Artikel off topic.

2023-04-05 07:17 UTC, bjoern-thalheim commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +  driver-class-name=org.h2.Driver
Tatsächlich geht beides, aber in https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config ist für Properties das = angegeben, für YML das :. Daran sollte ich mich halten.
Man kann sogar = und : mischen (https://stackoverflow.com/questions/37059979/difference-between-equals-and-colon-in-java-properties-file), aber das ist nicht schön. Ich habe den Code und den Artikel aktualisiert.

2023-04-05 07:17 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-05 07:18 UTC, bjoern-thalheim commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +<dependency>
Erledigt!

2023-04-05 07:18 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-05 07:35 UTC, bjoern-thalheim commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +    @PostMapping("/{thought}")
Absolut korrekt.
Habe das in der Codebasis und im Artikel geändert.

2023-04-05 07:36 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-05 07:37 UTC, bjoern-thalheim commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +    @PostMapping("/{thought}")
Erledigt!

2023-04-05 07:38 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-05 07:40 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-05 07:47 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-05 08:04 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-05 08:04 UTC, bjoern-thalheim reviewed
Ich denke, ich habe alle Anmerkungen soweit eingepflegt.
Vielen Dank @jo2 an die vielen hilfreichen Hinweise!

2023-04-05 08:14 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-05 08:19 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-06 05:35 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +            <scope>provided</scope>
ah ok, klar, ist auch logisch, dass es so gemacht wird.

2023-04-06 06:06 UTC, jo2 requested changes
Drei Kleinigkeiten hatte ich übersehen. Kannst du die Verlinkungen auf das Repository, die du eingebaut hast, entweder so einbauen, dass sie im sinnvoll in den Text passen (vgl. mein Kommentar in Z. 164) oder sie als "Caption" an den Codeauszug schreiben, indem du den Link als kursiven Text unter den Codeauszug schreibst.

2023-04-14 09:07 UTC, bjoern-thalheim commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +    <parent>
Ich hatte das probiert, aber wie auch immer ich es machte, die Einrückung der ersten Zeile wird ignoriert.
Ich entferne einfach alle Einrückungen, dann sieht es auch gut aus.

2023-04-14 09:25 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-14 09:28 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-14 09:36 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-14 09:45 UTC, jo2 requested changes
Kannst du die Verlinkungen auf das Repository, die du eingebaut hast, entweder so einbauen, dass sie im sinnvoll in den Text passen (vgl. mein Kommentar in Z. 164) oder sie als "Caption" an den Codeauszug schreiben, indem du den Link als kursiven Text unter den Codeauszug schreibst. Ein Beispiel zur sinnvollen Eingliederung in den Text habe ich dir in dieser Review gemacht.

2023-04-14 09:45 UTC, jo2 commented on _posts/2023-04-03-atdd-with-springboot-and-cucumber.md
> +Because I want to start a Spring Boot project and I'm a fan of Lombok, I add the following dependencies and add the Spring Boot Starter parent relation [pom.xml](https://github.com/bjoern-thalheim/cu
```suggestion
Because I want to start a Spring Boot project and I'm a fan of Lombok, I add the following dependencies and the Spring Boot Starter parent relation to the [pom.xml](https://github.com/bjoern-thalheim/cucumber_demo/blob/master/pom.xml):
```

2023-04-14 10:08 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-04-14 10:55 UTC, jo2 submitted a review, later dismissed

2023-04-14 10:57 UTC, jo2 commented
@acetous von mir aus ist der Artikel soweit fertig, möchtest du noch drüber gucken?

2023-05-15 07:19 UTC, jo2 commented
Der [Artikel](https://www.adesso.de/de/news/blog/atdd-on-spring-boot-with-cucumber.jsp) ist veröffentlicht, allerdings nicht über den PR. Wir arbeiten daran, dass auch der Autor angezeigt wird.

2023-05-15 07:19 UTC, closed without merging