Blogbeitrag - API Spezifikationen mit OpenAPI Style Validator prüfen
adessoSE/devblog pull request #276
Opened 2023-06-23 17:23 UTC by claudioaltamura

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [x] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2023-06-23 17:24 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-03 05:36 UTC, jo2 requested changes
Der Artikel ist recht interessant, ich fände es noch schön, zu wissen, ob das Plugin brauchbare Fehlermeldungen liefert, wenn gegen eine Konvention verstoßen wird. Es hilft mir wenig, wenn ich dann erst lange jede einzelne Zeile gegen ein Beispiel abgleichen muss. Kannst du da noch ein bisschen zu schreiben? Ein paar Kleinigkeiten habe ich dir außerdem noch dran geschrieben. Kannst du außerdem noch bei deinen Codebeispielen einen Blick auf die Einrückung werfen?

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +# Das Problem mit API Beschreibungen
```suggestion
# Das Problem mit API-Beschreibungen
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Hier kann der OpenAPI Style Validator [1] helfen genau solche Schwächen in OpenAPI-Spezifikationen zu finden.
```suggestion
Hier kann der OpenAPI Style Validator [1] helfen, genau solche Schwächen in OpenAPI-Spezifikationen zu finden. 
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Mit definierten Regeln wird beschrieben wie Elemente einer API-Spezifikation auszusehen hat.
```suggestion
Mit definierten Regeln wird beschrieben, wie Elemente einer API-Spezifikation auszusehen haben.
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Für die nähere Erläuterung der Dinge, die der OpenAPI Validator leistet, nehmen wir das beliebte Petstore-Beispiel [2].
```suggestion
Für die nähere Erläuterung der Vorteile, die der OpenAPI Validator mitbringt, nehmen wir das beliebte Petstore-Beispiel [2]. 
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Eine OpenAPI-Beschreibung beginnt ja bekanntlich mit dem Info-Objekt und den dazugehörigen Contact- und License-Objekt (siehe Listing 1).
```suggestion
Eine OpenAPI-Beschreibung beginnt ja bekanntlich mit dem Info-Objekt und den dazugehörigen Contact- und License-Objekten (siehe Listing 1). 
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Beim Info-Object wird der Titel und die Beschreibung vernachlässigt, Kontakt- oder Lizenzinformationen fehlen meistens komplett.
```suggestion
Beim Info-Objekt wird der Titel und die Beschreibung vernachlässigt, Kontakt- oder Lizenzinformationen fehlen meistens komplett.
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Aber die meisten Regelverstöße sind auf Ebene der Path bzw. Operation Objects.
Oben fängst du mit Objekt an, hier schreibst du jetzt Object. Was von beidem du machst, ist letztendlich egal, solange es einheitlich ist. Bitte entscheide dich für eine Variante. Bedenke dabei: verwendest du das deutsche Wort Objekt zusammen mit dem englischsprachigen Feldbezeichner, bspw. Contact, werden beide Wörter mit einem Bindestrich verbunden. Verwendest du zwei englische Begriffe, werden sie auseinander geschrieben.
Die Stellen, an denen du Object bzw. Objekt verwendet hast, werde ich daher in dieser ersten Review nicht weiter korrigieren.

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +enthält dann die Operationen, also den erlaubten Methoden.
```suggestion
enthält dann die Operationen, also die erlaubten Methoden.
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Im Listing 2 fehlz z.B. das Property „summary“.
```suggestion
Im Listing 2 fehlz z.B. das Property "summary". 
```
Das verwenden besonderer Anführungszeichen kann zu Fehlern in der Verarbeitung des Blogposts führen.

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Dafür ist eine „description“ vorhanden.
```suggestion
Dafür ist eine "description" vorhanden.
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +können wir bestimmen wie beispielweise ein Path auszusehen hat. Unter [1] sind alle Optionen genannt.
```suggestion
können wir bestimmen, wie beispielweise ein Path auszusehen hat. Unter [1] sind alle Optionen genannt.
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Jede Option kann als Parameter unter <configuration> als XML-Tag hinzugefügt. Und schließlich können wir der Validator kann mit folgendem Befehl ausgeführt werden:
```suggestion
Jede Option kann als Parameter unter <configuration> als XML-Tag hinzugefügt werden. Und schließlich kann der Validator mit folgendem Befehl ausgeführt werden:
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Das Werkzeug ist eine Hilfe bei der Umsetzung von API-Richtlinien. Mit definierten Regeln können API-Spezifikationen ein einheitliches „Look and Feel“ gegeben werden.
```suggestion
Das Werkzeug ist eine Hilfe bei der Umsetzung von API-Richtlinien. Mit definierten Regeln kann API-Spezifikationen ein einheitliches "Look and Feel" gegeben werden.
```

2023-07-03 05:36 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +        <exclusions>
Kannst du hier noch ein Beispiel für die Konfiguration angeben?

2023-07-03 18:02 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-03 18:02 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-03 18:03 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-03 18:04 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-03 18:04 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-03 18:04 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-03 18:04 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-03 18:08 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-07 17:18 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-07 17:21 UTC, claudioaltamura commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +        <exclusions>
Ich habe im Commit c746c3110dc16c5e154a7187cc353380b70cafbb ein Bespiel angegeben.

2023-07-07 17:22 UTC, claudioaltamura commented
In 3cfdbaffc17e1d519d4d6787925c12134fd219be habe ich zusätzlich die Listing reformatiert.

2023-07-07 17:23 UTC, claudioaltamura commented
In f0110a2ee546a4a075ff44fcdb9bec30a8875f20 habe cih ein Beispiel angegeben, das zum Build Break führt. 
@jo2  Gibt es noch etwas, was ich verbessern kann?

2023-07-14 06:06 UTC, jo2 requested changes
Bitte schau dir nochmal die noch offenen Kommentare an.

2023-07-14 06:06 UTC, jo2 commented on _posts/2023-06-23-api-spefizikationen-openapi-style-validator-pruefen.md
> +Jede Option kann als Parameter unter <configuration> als XML-Tag hinzugefügt werden. Stellen wir uns folgenden hypothetischen Fall vor. Wir haben eine kleine OpenAPI-Beschreibungen und möchte hier au
```suggestion
Jede Option kann als Parameter unter <configuration> als XML-Tag hinzugefügt werden. Stellen wir uns folgenden hypothetischen Fall vor. Wir haben eine kleine OpenAPI-Beschreibungen und möchte hier auf den Operation Tag verzichten. Dann können wir, wie in Listing 4 gezeigt, die Validierung mit der Option "validateOperationTag" und  "false" als Content ausschalten. Schließlich kann der Validator mit folgendem Befehl ausgeführt werden:
```

2023-07-17 17:24 UTC, claudioaltamura commented
@jo2 Die Validierung der Blogpost bricht mit einer Exception ab: https://github.com/adessoSE/devblog/actions/runs/5578661902/jobs/10193165441?pr=276#step:6:104

2023-07-18 06:55 UTC, jo2 commented
Bitte schau dir auch nochmal die offenen Kommentare an, da ist noch offenes Feedback drin.

Die Pipeline schlägt fehl, weil die Pipeline versucht, einen Diff zwischen deinem Stand und dem Current Head zu bilden. Das geht nicht, weil der Current Head in deinem PR nicht gefunden werden kann. Du müsstest da einmal einen Rebase von deinem Fork auf den adesssoSE/devblog:master Branch machen.

2023-08-18 13:18 UTC, closed without merging