Artikel 'Einfache Bildverarbeitung mit Python' und OpenCV Bibliothek
adessoSE/devblog pull request #278
Opened 2023-07-13 16:34 UTC by alexsuperdev

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#dateiname-und-ablageort)
  - [ x] [Autoreninfo gepflegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#autoren-informationen)
  - [ x] [Metadaten gepflegt:](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#metadaten)
    - [x ] "title" vergeben
    - [x ] "author_ids" angegeben
    - [x ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ x] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x ] [Teaser entspricht den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#einleitung--teaser)
  - [x ] Rechtschreibung korrigiert
  - [x ] [Ein Satz pro Zeile](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#ein-satz-pro-zeile)
  - [x ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#bilder)
  - [ x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#%C3%9Cberschriften)
  - [ x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2023-07-13 16:35 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-14 07:11 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +title:  "Einfache Bildverarbeitung mit Python und OpenCV Bibliothek"         # Pflichtfeld. Bitte einen Titel für den Blog Post angeben.
```suggestion
title:  "Einfache Bildverarbeitung mit Python und der OpenCV-Bibliothek"         # Pflichtfeld. Bitte einen Titel für den Blog Post angeben.
```

2023-07-14 07:12 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Python ist eine populäre Programmiersprache, die vor allem in Bereich machine learning zum Einsatz kommt.
```suggestion
Python ist eine populäre Programmiersprache, die vor allem in Bereich Machine Learning zum Einsatz kommt.
```

2023-07-14 07:12 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +# OpenCV Bibliothek
```suggestion
# OpenCV-Bibliothek
```

2023-07-14 07:13 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +# Python Projekt mit OpenCV aufsetzen
```suggestion
# Python-Projekt mit OpenCV aufsetzen
```

2023-07-14 07:14 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Wir wollen eine einfache Slideshow aus mehreren Bildern mithilfe von OpenCV Bibliothek erstellen.
```suggestion
Wir wollen eine einfache Slideshow aus mehreren Bildern mithilfe der OpenCV-Bibliothek erstellen.
```

2023-07-14 07:14 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Diese Slideshow soll aus zwei Bilder eine Videodatei erstellen, die ähnliche Effekte verwendet wie es bei Powerpoint der Fall ist.
```suggestion
Diese Slideshow soll aus zwei Bildern eine Videodatei erstellen, die ähnliche Effekte verwendet wie es bei Powerpoint der Fall ist.
```

2023-07-14 07:14 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Um OpenCV Bibliothek verwenden zu können, müssen wir erstmal diese installieren.
```suggestion
Um die OpenCV-Bibliothek verwenden zu können, müssen wir diese erstmal installieren.
```

2023-07-14 07:16 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +pip install opencv-python
Verwende für den Kommandozeilenbefehl bitte auch einen Codeblock.

2023-07-14 07:16 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Wir werden erstmal damit anfangen, dass wir ein Bild einlesen mit OpenCV und diesen anzeigen.
```suggestion
Wir werden erstmal damit anfangen, dass wir ein Bild mit OpenCV einlesen und es danach anzeigen.
```

2023-07-14 07:17 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Das Bild muss in diesem Fall innerhalb vom Projektverzeichnis in dem Ordner "images" liegen und "image1.jpg" heißen.
```suggestion
Das Bild muss in diesem Fall innerhalb des Projektverzeichnisses in dem Ordner "images" liegen und "image1.jpg" heißen.
```

2023-07-14 07:17 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Jetzt erstellen wir ein Python Script File und nennen den zum Beispiel Slideshow.py
```suggestion
Jetzt erstellen wir ein Python Script File und nennen es zum Beispiel "Slideshow.py".
```

2023-07-14 07:18 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Hier verwenden wir die Funktion cv2.imread() um das Bild einzulesen und die Funktion cv2.VideoWriter() mit dem folgenden
```suggestion
Hier verwenden wir die Funktion `cv2.imread()`, um das Bild einzulesen, und die Funktion `cv2.VideoWriter()` mit dem folgenden
```

2023-07-14 07:18 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Parameter (const String &filename, int fourcc, double fps, Size frameSize, bool isColor=true)
```suggestion
Parameter `(const String &filename, int fourcc, double fps, Size frameSize, bool isColor=true)`,
```

2023-07-14 07:18 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +um eine Videodatei mit dem Namen Slideshow.mp4 aus diesem Bild zu erstellen. Als Videocodec
```suggestion
um eine Videodatei mit dem Namen "Slideshow.mp4" aus diesem Bild zu erstellen. Als Videocodec
```

2023-07-14 07:19 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +wird in diesem Beispiel mp4 genommen, fps(Frame per Second) setzen wir auf 1, frameSize setzen wird auf die Breite und
```suggestion
wird in diesem Beispiel "mp4" genommen, die fps (Frames per Second) setzen wir auf 1, frameSize setzen wird auf die Breite und 
```

2023-07-14 07:19 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Länge von dem Bild image1 gesetzt.
```suggestion
Länge von dem Bild "image1".
```

2023-07-14 07:19 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Die Liste der möglichen Videocodecs findet man unter https://learn.microsoft.com/en-us/windows/win32/medfound/video-fourccs
```suggestion
Die Liste der möglichen Videocodecs findet man unter [https://learn.microsoft.com/en-us/windows/win32/medfound/video-fourccs](https://learn.microsoft.com/en-us/windows/win32/medfound/video-fourccs).
```

2023-07-14 07:20 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Eine weitere Funktion von OpenCV, die wir verwenden, ist video.write(), die ein Bild zu dem Video hinzufügt.
```suggestion
Eine weitere Funktion von OpenCV, die wir verwenden, ist `video.write()`, die ein Bild zu dem Video hinzufügt.
```

2023-07-14 07:20 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +# Video mit einem 'Verblassen' Effekt
```suggestion
# Video mit einem "Verblassen"-Effekt
```

2023-07-14 07:21 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +In OpenCV Bibliothek gibt es viele Möglichkeiten ein Bild zu verändern.
```suggestion
In der OpenCV-Bibliothek gibt es viele Möglichkeiten, ein Bild zu verändern.
```

2023-07-14 07:21 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Zum Beispiel es ist möglich ein Bild ausblenden und ein anderes Bild anzeigen.
```suggestion
Zum Beispiel es ist möglich, ein Bild auszublenden und ein anderes Bild anzuzeigen.
```

2023-07-14 07:22 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Dieser Effekt heißt in Powerpoint 'Verblassen'
```suggestion
Dieser Effekt heißt in Powerpoint "Verblassen".
```

2023-07-14 07:22 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Dafür eignet sich die Funktion addWeighted(src1,  alpha, src2, beta, gamma[, dst[, dtype]]) von OpenCV
```suggestion
Dafür eignet sich die Funktion `addWeighted(src1, alpha, src2, beta, gamma[, dst[, dtype]])` von OpenCV.
```

2023-07-14 07:22 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +src1 ist das erste Bild, src2 ist das zweite Bild
```suggestion
`src1` ist das erste Bild, `src2` ist das zweite Bild.
```

2023-07-14 07:23 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +alpha ist der Transparenzwert für das erste Bild,
```suggestion
`alpha` ist der Transparenzwert für das erste Bild,
```

2023-07-14 07:23 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +beta ist der Transparenzwert für das zweite Bild.
```suggestion
`beta` ist der Transparenzwert für das zweite Bild.
```

2023-07-14 07:23 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Gamma ist eine Konstante, die zu dem Transparenzindex beider hinzugefügt werden kann, wir setzen die auf 0.
```suggestion
`gamma` ist eine Konstante, die zu dem Transparenzindex beider Bilder hinzugefügt werden kann, wir setzen sie auf 0.
```

2023-07-14 07:24 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Je kleiner alpha bzw. beta ist, desto durchsichtiger ist das entsprechende Bild, wobei die möglichen Werte sind von 0 bis 1
```suggestion
Je kleiner `alpha` bzw. `beta` ist, desto durchsichtiger ist das entsprechende Bild, wobei die möglichen Werte von 0 bis 1 liegen.
```

2023-07-14 07:24 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Schreiben wir eine Methode, die das Bild 1 schrittweise ausblendet und dafür Bild 2 einblendet.
```suggestion
Als nächstes schreiben wir eine Methode, die das erste Bild schrittweise ausblendet und dafür das zweite Bild einblendet.
```

2023-07-14 07:25 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Sehr wichtig ist, dass die beiden Bilder die gleiche Größe haben, sonst kommt die Fehlermeldung beim Ausführen des Programms.
```suggestion
Sehr wichtig ist, dass die beiden Bilder die gleiche Größe haben, sonst kommt eine Fehlermeldung beim Ausführen des Programms.
```

2023-07-14 07:25 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +    img_changed =verblassen(img1, img2, x)
```suggestion
    img_changed = verblassen(img1, img2, x)
```

2023-07-14 07:25 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +images = [0, 0.5, 1]
Währe hier `steps` ein besserer Name für das Array?

2023-07-14 07:26 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Wir haben die Funktion verblassen() geschrieben, die je größer der index Parameter ist, das erste Bild verblassen lässt und
```suggestion
Wir haben die Funktion `verblassen()` geschrieben, die je größer der `index`-Parameter ist, das erste Bild verblassen lässt und
```

2023-07-14 07:27 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Hier setzen wir mit cv2.waitKey(200) die Verzögerung beim Wechsel der Bilder auf 200 Millisekunden um den Bilderübergang langsamer zu machen.
```suggestion
Hier setzen wir mit `cv2.waitKey(200)` die Verzögerung beim Wechsel der Bilder auf 200 Millisekunden, um den Bilderübergang langsamer zu machen.
```

2023-07-14 07:27 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Die Funktion rufen wir 3 Mal, um das Ergebnis der Umwandlung der Bilder besser zu sehen.
```suggestion
Die Funktion rufen wir 3 Mal auf, um das Ergebnis der Umwandlung der Bilder besser zu sehen.
```

2023-07-14 07:27 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +# Video mit einem 'Blur' Effekt
```suggestion
# Video mit einem "Blur"-Effekt
```

2023-07-14 07:28 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Um das Bild zu blurren werden wir die Funktion cv2.blur(src, ksize[, dst[, anchor[, borderType]]]) anwenden.
```suggestion
Um das Bild zu blurren, werden wir die Funktion `cv2.blur(src, ksize[, dst[, anchor[, borderType]]])` verwenden.
```

2023-07-14 07:29 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Diese Funktion verwendet die Mittelwertmethode um unscharfes Bild zu erstellen.
```suggestion
Diese Funktion verwendet die Mittelwertmethode, um unscharfe Bilder zu erstellen.
```
Kannst du hier noch einen Link angeben oder kurz erklären, was die Methode macht bzw. wie sie funktioniert?

2023-07-14 07:32 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Die nimmt als Parameter das Bild und die sogenannte Kernelgröße, je größer diese ist, desto unschärfer wird das
```suggestion
Die Funktion nimmt als Parameter das Bild und die sogenannte Kernelgröße, je größer diese ist, desto unschärfer wird das
```

2023-07-14 07:32 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Schreiben wir die Funktion die das Bild unschärfer macht.
```suggestion
Als nächstes schreiben wir die Funktion, die das Bild unschärfer macht.
```

2023-07-14 07:32 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Anschließend rufen wir die Funktion drei Mal mit jeweils größeren Parameter um die Unschärfe des Bildes
```suggestion
Anschließend rufen wir die Funktion drei Mal mit jeweils größeren Parameter auf, um die Schärfe des Bildes zu reduzieren und so einen "Blur"-Effekt zu erreichen.
```

2023-07-14 07:33 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Wir haben gesehen, wie einfach es ist mit Python und OpenCV Bibliothek aus der Bilder ein Video zu erstellen.
```suggestion
Wir haben gesehen, wie einfach es mit Python und der OpenCV-Bibliothek ist, aus mehreren Bildern ein Video zu erstellen.
```

2023-07-14 07:34 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Die zwei Videoeffekten, die wir mit nur ein paar Zeilen Code implementiert haben, haben außerdem gezeigt wie einfach
```suggestion
Ebenfalls haben wir zwei Videoeffekte mit nur ein paar Zeilen Code implementiert.
```

2023-07-14 07:35 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +die Verwendung der OpenCV Bibliothek ist. Diese Bibliothek bietet noch sehr viele Möglichkeiten für die Bild und Videobearbeitung.
```suggestion
Die OpenCV-Bibliothek bietet neben den gezeigten Funktionen noch sehr viele weitere Möglichkeiten für die Bild- und Videobearbeitung.
```

2023-07-14 07:36 UTC, jo2 requested changes
Kannst du die in den jeweiligen Schritten erstellten Videos noch als GIF hinzufügen?

2023-07-14 08:59 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-15 19:16 UTC, alexsuperdev commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Diese Funktion verwendet die Mittelwertmethode um unscharfes Bild zu erstellen.
Ich habe eine Erklärung hinzugefügt

2023-07-15 20:47 UTC, alexsuperdev commented
> Kannst du die in den jeweiligen Schritten erstellten Videos noch als GIF hinzufügen?

hinzugefügt

2023-07-16 08:16 UTC, alexsuperdev commented
> Kannst du die in den jeweiligen Schritten erstellten Videos noch als GIF hinzufügen?

Ich habe die Gifs hinzugefügt, jetzt läuft validate-blogpost / pull-and-run-blogpost-checker-image (pull_request_target) auf Fehler.
Woran liegt das?

2023-07-18 06:51 UTC, jo2 requested changes
2 Kleinigkeiten sind noch drin, kannst du bitte außerdem die GIFs, die du nicht nutzt, aus dem PR entfernen?
Die Pipeline schlägt fehl, weil die Pipeline versucht, einen Diff zwischen deinem Stand und dem Current Head zu bilden. Das geht nicht, weil der Current Head in deinem PR nicht gefunden werden kann. Du müsstest da einmal einen Rebase von deinem Fork auf den adesssoSE/devblog:master Branch machen.

2023-07-18 06:51 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Die blur()-Funktion ermöglicht es, ein Bild zu verwischen oder zu glätten. Sie wird verwendet, um störende Details zu reduzieren oder Rauschen zu entfernen, indem die Pixelwerte im Bild verwischt wer
```suggestion
Die `blur()`-Funktion ermöglicht es, ein Bild zu verwischen oder zu glätten. Sie wird verwendet, um störende Details zu reduzieren oder Rauschen zu entfernen, indem die Pixelwerte im Bild verwischt werden.
```

2023-07-18 06:51 UTC, jo2 commented on _posts/2023-07-10-python-bildverarbeitung-mit-opensource-bibliothek.md
> +Die Funktion blur() akzeptiert zwei Parameter: das Eingangsbild (src) und die Größe des Kernel-Fensters (ksize), das angibt, wie stark das Bild verwischt werden soll.
```suggestion
Die Funktion `blur()` akzeptiert zwei Parameter: das Eingangsbild `(src)` und die Größe des Kernel-Fensters `(ksize)`, das angibt, wie stark das Bild verwischt werden soll.
```

2023-07-20 06:29 UTC, alexsuperdev commented
Muss ich noch was korrigieren oder passt alles jetzt?

2023-07-20 10:20 UTC, jo2 approved these changes

2023-07-20 10:20 UTC, jo2 commented
@acetous möchtest du hier noch drüber gucken? Von meiner Seite aus ist der PR soweit in Ordnung.

2023-08-03 06:19 UTC, alexsuperdev commented
@acetous  @jo2 Wie lange dauert noch das Review?

2023-08-14 13:07 UTC, alexsuperdev commented
@jo2 Kann man auf die Review von @acetous verzichten? Da sonst wird der Pullrequest glaube ich noch in 2024 nicht gemergt sein.

2023-08-14 14:03 UTC, jo2 commented
@alexsuperdev nach Rücksprache mit @acetous reicht meine Review, bitte führe ein Rebase auf den `adessoSE/devblog:master` aus, danach kann der PR gemergt werden.

2023-08-14 20:48 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-08-14 20:51 UTC, alexsuperdev commented
> @alexsuperdev nach Rücksprache mit @acetous reicht meine Review, bitte führe ein Rebase auf den `adessoSE/devblog:master` aus, danach kann der PR gemergt werden.

Vielen Dank, ich habe Rebase gemacht

2023-08-16 15:03 UTC, jo2 approved these changes

2023-08-16 15:03 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-08-16 15:04 UTC, merged