Blog-Post - F.I.R.S.T. Prinzipien für solides Unit-Testen
adessoSE/devblog pull request #280
Opened 2023-07-19 21:23 UTC by DK-Stern

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [x] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2023-07-19 21:24 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-19 21:26 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-20 12:22 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Durch das Aufteilen der Unit-Tests in diese drei Bereiche wird die Lesbarkeit gesteigert, was uns wiederrum dabei unterstützt Abhängigkeiten aufzudecken, besonders dann, wenn das Test-Setup mehr wie
```suggestion
Durch das Aufteilen der Unit-Tests in diese drei Bereiche wird die Lesbarkeit gesteigert, was uns wiederum dabei unterstützt, Abhängigkeiten aufzudecken, besonders dann, wenn das Test-Setup mehr als nur eine Zeile Code ist.
```

2023-07-20 12:23 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Da wir schon im Vorfeld Annahmen treffen, die sich am Ende unserer Geschichte bewahrheiten sollen.
```suggestion
Zugegeben, es mag keine besonders spannende Geschichte sein, da wir schon im Vorfeld Annahmen treffen, die sich am Ende unserer Geschichte bewahrheiten sollen.
```

2023-07-20 12:23 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Allerdings ist dies ja schließlich genau das, was wir in einem Unit-Test haben möchten: Erwartungen die sich bewahrheiten.
```suggestion
Allerdings ist dies ja schließlich genau das, was wir in einem Unit-Test haben möchten: Erwartungen, die sich bewahrheiten.
```

2023-07-20 12:25 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Also keine plötzlichen Site-Stories (Sprünge im Code) die mich als Lesenden dazu zwingen in der Geschichte hin und her zu springen, um das Gesamtbild zu durchblicken, sondern ich möchte einen Unit-Te
```suggestion
Es sollte also keine plötzlichen Site-Stories (Sprünge im Code) geben, die mich als Lesenden dazu zwingen, in der Geschichte hin und her zu springen, um das Gesamtbild zu durchblicken, sondern ich möchte einen Unit-Test von oben nach unten einfach durchlesen und verstehen können.
```

2023-07-20 12:25 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Unsere Unit-Tests sollen häufig und auf verschiedenen Umgebungen ausgeführt werden können, dabei liefern diese immer die gleichen Ergebnisse für die gleichen Eingaben.
```suggestion
Unsere Unit-Tests sollen häufig und auf verschiedenen Umgebungen ausgeführt werden können, dabei liefern sie immer die gleichen Ergebnisse für die gleichen Eingaben.
```

2023-07-20 12:26 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- unabhängig von der Uhrzeit der Ausführung
```suggestion
- unabhängig von der Uhrzeit der Ausführung,
```

2023-07-20 12:26 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- unabhängig der zuvor ausgeführten Unit-Tests
```suggestion
- unabhängig von den zuvor ausgeführten Unit-Tests und
```

2023-07-20 12:26 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- unabhängig zur Umgebung
```suggestion
- unabhängig von der Umgebung 
```

2023-07-20 12:27 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Wir möchten nicht nach jeder Testausführung selbst das Ergebnis auswerten müssen, indem wir bspw. in logfiles schauen.
```suggestion
Wir möchten nicht nach jeder Testausführung selbst das Ergebnis auswerten müssen, indem wir bspw. in Log Files schauen.
```

2023-07-20 12:30 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Es ist einfach schwerer produktiven Code auf Anhieb testbar zu schreiben, als wenn man schon vorher einen Unit-Test hat, welcher einen dazu nötigt, den produktiven Code testbar zu gestalten.
```suggestion
Es ist einfach schwerer, produktiven Code auf Anhieb testbar zu schreiben, als wenn man schon vorher einen Unit-Test hat, welcher einen dazu nötigt, den produktiven Code testbar zu gestalten.
```

2023-07-20 12:31 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Dies erreichen wir, indem nicht nur Testfälle für die Erfolgsfälle, sondern auch die Fehlerfälle, Grenzfälle und [Äquivalenzklassen](https://de.wikipedia.org/wiki/%C3%84quivalenzklassentest) geschrie
```suggestion
Dies erreichen wir, indem wir nicht nur Testfälle für die Erfolgsfälle, sondern auch für die Fehlerfälle, Grenzfälle und [Äquivalenzklassen](https://de.wikipedia.org/wiki/%C3%84quivalenzklassentest) schreiben.
```

2023-07-20 12:33 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- natürliche Zahlen die durch 3 teilbar sind mit "fizz" auf der Konsole ausgegeben werden sollen
```suggestion
- für natürliche Zahlen, die durch 3 teilbar sind, "fizz" auf der Konsole ausgegeben werden soll,
```

2023-07-20 12:33 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Diese Aufgabe sieht vor, dass für:
```suggestion
Diese Aufgabe sieht vor, dass:
```

2023-07-20 12:33 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- natürlichen Zahlen die durch 5 teilbar sind mit "buzz" auf der Konsole ausgeben werden sollen
```suggestion
- für natürlichen Zahlen, die durch 5 teilbar sind, "buzz" auf der Konsole ausgeben werden soll,
```

2023-07-20 12:34 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- natürliche Zahlen die sowohl durch 3 als auch durch 5 teilbar sind, mit "fizzbuzz" auf der Konsole ausgegeben werden sollen
```suggestion
- für natürliche Zahlen, die sowohl durch 3 als auch durch 5 teilbar sind, "fizzbuzz" auf der Konsole ausgegeben werden soll und
```

2023-07-20 12:34 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- alle anderen Zahlen, die jeweilige Zahl selbst auf der Konsole ausgeben werden soll
```suggestion
- für alle anderen Zahlen die jeweilige Zahl selbst auf der Konsole ausgeben werden soll.
```

2023-07-20 12:35 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Aus dieser Aufgabe ergeben sich nun diverse Testfälle, wie bspw. folgende:
```suggestion
Aus dieser Aufgabe ergeben sich nun diverse Testfälle:
```

2023-07-20 12:36 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- **Given** is number -1. **When** fizzbuzz function executes, **Then** an error should be thrown.
Wäre hier nicht die 0 besser?

2023-07-20 12:36 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +**Testfälle für Äquivalenzklassen-Abdeckung**
```suggestion
**Testfälle für Äquivalenzklassenabdeckung**
```

2023-07-20 12:38 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Wir haben hier Erfolgreiche-, Fehlerfall- und Grenzwert-Testfälle geschrieben und zusätzlich noch weitere um alle Äquivalenzklassen abzudecken.
```suggestion
Wir haben hier Erfolgsfall-, Fehlerfall- und Grenzwerttestfälle geschrieben und zusätzlich noch weitere, um alle Äquivalenzklassen abzudecken.
```

2023-07-20 12:38 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- **Given** is number 100. **When** fizzbuzz function executes, **Then** an error should be thrown.
Diese beiden Äquivalenzklassen sind doch schon oben durch die Fehlerfalltestfälle abgedeckt.

2023-07-20 12:39 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Denn Fakt ist, man kann nicht jedes Szenario Testen und das möchte man auch nicht.
```suggestion
Denn Fakt ist, man kann nicht jedes Szenario testen und das möchte man auch nicht.
```

2023-07-20 12:39 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Es würde einfach viel zu lange dauern und irgendwann ist der Mehrwert von zu vielen Unit-Tests auch nicht mehr gegeben, da diese auch gewartet werden müssen.
```suggestion
Es würde einfach viel zu lange dauern und irgendwann ist der Mehrwert der Unit-Tests auch nicht mehr gegeben, da diese auch gewartet werden müssen.
```

2023-07-20 12:40 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Aus diesem Grund versuchen wir so viele sinnvolle Tests zu schreiben wie möglich, aber gleichzeitig auch so wenig wie nötig.
```suggestion
Aus diesem Grund versuchen wir, so viele sinnvolle Tests zu schreiben wie möglich, aber gleichzeitig auch so wenig wie nötig.
```

2023-07-20 12:40 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- Sind alle wichtigen Positiv-Testfälle vorhanden?
```suggestion
- Sind alle wichtigen Positivtestfälle vorhanden?
```

2023-07-20 12:40 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- Sind alle wichtigen Fehlerfall-Testfälle vorhanden?
```suggestion
- Sind alle wichtigen Fehlerfalltestfälle vorhanden?
```

2023-07-20 12:40 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Nach Verinnerlichung und Verstehen dieser Prinzipien, sollte hoffentlich das Schreiben von Unit-Tests etwas leichter von der Hand gehen.
```suggestion
Nach Verinnerlichung und Verstehen dieser Prinzipien sollte das Schreiben von Unit-Tests etwas leichter von der Hand gehen.
```

2023-07-20 12:41 UTC, jo2 commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Letzten Endes finden sich die Test F.I.R.S.T. Prinzipien in Projekten mit gut strukturierten Unit-Tests immer wieder, auch eventuell in abgewandelter Form.
```suggestion
Letzten Endes finden sich die Test-F.I.R.S.T.-Prinzipien in Projekten mit gut strukturierten Unit-Tests immer wieder, wenn auch eventuell in abgewandelter Form.
```

2023-07-20 12:42 UTC, jo2 requested changes
Ein ganz interessanter Blogartikel, ein paar Kleinigkeiten habe ich dir noch angemerkt.

2023-07-20 12:58 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-07-20 20:40 UTC, DK-Stern commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +- **Given** is number 100. **When** fizzbuzz function executes, **Then** an error should be thrown.
Da hast du vollkommen recht. :)

2023-07-20 20:40 UTC, DK-Stern commented on _posts/2023-07-19-first-prinzipien-fuer-solides-unit-testen.md
> +Im schlimmsten Fall werden ohne Mocks Live-Services aufgerufen und ehe man sich versieht, hat man erfolgreich seinen ersten kleinen DOS-Angriff durchgeführt.
Das Beispiel ist sehr gut!

2023-07-20 20:50 UTC, DK-Stern commented
> Ein ganz interessanter Blogartikel, ein paar Kleinigkeiten habe ich dir noch angemerkt.

Vielen Dank für deine sehr guten Vorschläge und deiner sehr ausführlichen Review.  👍

2023-07-24 14:57 UTC, DK-Stern reviewed
Vielen Dank für deine sehr guten Vorschläge und deiner sehr ausführlichen Review. 👍
Ich habe die Stellen soweit nachgebessert.

2023-07-27 11:30 UTC, jo2 approved these changes

2023-07-27 11:31 UTC, jo2 commented
@acetous möchtest du hier noch drüber gucken? Von mir aus ist der Artikel so fertig.

2023-09-05 13:21 UTC, jo2 commented
@DK-Stern kannst du noch einen Rebase auf den `adessoSE/devblog:master` machen, dann sollte die Pipeline auch durchlaufen und wir können den Artikel veröffentlichen.

2023-09-14 07:24 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-14 11:10 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-20 06:54 UTC, jo2 approved these changes

2023-09-20 06:56 UTC, jo2 approved these changes

2023-09-20 06:56 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-20 06:59 UTC, merged