Add 2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md …
adessoSE/devblog pull request #281
Opened 2023-08-13 08:57 UTC by eleazar-araujo

…and assets

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2023-08-13 09:30 UTC, eleazar-araujo commented
Hallo. Ich verstehe leider nicht, warum der Build scheitert. Der Fehler scheint in einer Docker-Operation zu liegen
https://github.com/adessoSE/devblog/actions/runs/5846395095/job/15851545051?pr=281

2023-08-16 15:05 UTC, jo2 commented
Der Build schlägt aktuell fehl, weil der aktuelle Commit aus dem adessoSE/devblog:master in deinem Fork nicht gefunden werden kann. Das funktioniert, wenn du einen Rebase ausführst.

2023-08-17 08:52 UTC, jo2 requested changes
Ein ziemlich interessanter Blogbeitrag, ein paar Anmerkungen habe ich dir noch gemacht.

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Im obigen Diagramm können am Beispiel von einem E-Commerce-Bestellvorgang sehen, wie die Saga Pattern agiert:
```suggestion
Im obigen Diagramm können wir am Beispiel eines E-Commerce-Bestellvorgangs sehen, wie das Saga Pattern agiert:  
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Nach Eintreten des Auslösers (_Bestellung bestätigt_), werden die Teiltransaktionen der Saga schrittweise innerhalb jedes Microservices ausgeführt.
```suggestion
Nach Eintreten des Auslösers (_Bestellung bestätigt_), werden die Teiltransaktionen der Saga schrittweise innerhalb jedes Microservice ausgeführt.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Nachdem jedem seine internen Vorgänge abgeschlossen hat, wird ein Ereignis ausgelöst, das den nächsten Schritt anstoßt.
```suggestion
Nachdem jeder Service seine internen Vorgänge abgeschlossen hat, wird ein Ereignis ausgelöst, das den nächsten Schritt anstößt.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Bei einem Fehlschlag Mitte in der Saga werden wiederum Ereignisse in umgekehrten Richtung ausgelöst, die sogenannten "kompensierende Transaktionen" anstoßen sollen.
```suggestion
Bei einem Fehlschlag Mitten in der Saga werden wiederum Ereignisse in umgekehrter Richtung ausgelöst, die sogenannte "kompensierende Transaktionen" anstoßen sollen.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +## Arten von Sagas
```suggestion
# Arten von Sagas
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +### Choreografie
```suggestion
## Choreografie
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Eine Choreografie-Saga kann man mit einem einfachen Kochenabend bei Freunden vergleichen.
```suggestion
Eine Choreografie-Saga kann man mit einem einfachen Kochabend mit Freunden vergleichen.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Dies setzt voraus, dass die einzelnen Microservices koordinieren können, um den Transaktionszustand aufrechtzuerhalten.
```suggestion
Dies setzt voraus, dass sich die einzelnen Microservices koordinieren können, um den Transaktionszustand aufrechtzuerhalten.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Dieser Art von Saga ist in der Regel einfach umzusetzen und eignet sich gut für kurzlaufenden Transaktionen mit wenigen Schritten, wo kein Tracing notwendig ist und keinen Bedarf gibt, dessen Status
```suggestion
Diese Art von Saga ist in der Regel einfach umzusetzen und eignet sich gut für kurzlaufenden Transaktionen mit wenigen Schritten, wo kein Tracing notwendig ist und es keinen Bedarf gibt, den Transaktionsstatus zu tracken.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Auf der anderen Seite, wird bei einer zu großen Anzahl von beteiligten Services zunehmend schwieriger festzustellen, wo Fehler eingetreten sind.
```suggestion
Auf der anderen Seite, wird es bei einer zu großen Anzahl von beteiligten Services zunehmend schwieriger, festzustellen, wo Fehler eingetreten sind.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Gleichzeitig wird die Anzahl von Laufzeitabhängigkeiten unübersichtlicher und schnell zu verwalten.
```suggestion
Gleichzeitig wird die Anzahl von Laufzeitabhängigkeiten unübersichtlicher und schwerer zu verwalten.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Im obigen Diagramm können wir die schon benannte Bestellvorgang einsehen, diesmal aber als Orchestrator-Saga:
```suggestion
Im obigen Diagramm können wir den schon benannte Bestellvorgang einsehen, diesmal aber als Orchestrator-Saga:
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Der Hauptunterschied besteht aus dem Einsatz eines dedizierten Services, die für die Orchestrierung, Tracking und Tracing der notwendigen Schritte zuständig ist.
```suggestion
Der Hauptunterschied besteht aus dem Einsatz eines dedizierten Service, der für die Orchestrierung, das Tracking und das Tracing der notwendigen Schritte zuständig ist.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Ein weiterer Vorteil besteht aus dem Gewinn an Übersichtlichkeit, da die Definition des ganzen Workflows an einem einzigen Stellen liegt, wo es angepasst und getestet werden kann.
```suggestion
Ein weiterer Vorteil besteht aus dem Gewinn an Übersichtlichkeit, da die Definition des gesamten Workflows an einer einzigen Stellen liegt, wo sie angepasst und getestet werden kann.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Dennoch kommen diese Vorteile mit hohen Kosten: Der Orchestrator wird Single-Point-Of-Failure, d.h, wenn er nicht verfügbar oder in einem fehlerhaften Zustand ist, kann die ganze Transaktion nicht au
```suggestion
Dennoch kommen diese Vorteile mit hohen Kosten: Der Orchestrator wird ein Single Point Of Failure, d.h., wenn er nicht verfügbar oder in einem fehlerhaften Zustand ist, kann die ganze Transaktion nicht ausgeführt werden, egal wie zuverlässig die übrigen beteiligten Services sind.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Wegen der erhöhte Komplexität bei der Umsetzung und Wartung eignet sich dieser Art von Saga für Geschäftstransaktionen, die viele (i.d.R mehr als 4) teilnehmende Services und langlaufende Schritten b
```suggestion
Wegen der erhöhte Komplexität bei der Umsetzung und Wartung eignet sich diese Art von Saga für Geschäftstransaktionen, die viele (i.d.R. mehr als 4) teilnehmende Services mit langlaufenden Schritten beinhalten, deren Status getrackt werden muss.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +In unserem Küchebeispiel ist der Orchestrator der Chefkoch, der die Küchenstationen in einem Restaurant koordiniert.
```suggestion
In unserem Küchenbeispiel ist der Orchestrator der Chefkoch, der die Küchenstationen in dem Restaurant koordiniert.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Er gibt jedem Mitarbeitenden in der notwendigen Reihenfolge Anweisungen, über welche Zutaten zubereitet werden sollen.
```suggestion
Er gibt jedem Mitarbeitenden in der notwendigen Reihenfolge Anweisungen, welche Zutaten zubereitet werden sollen.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Falls es Probleme bei einer der Schritte gibt, stellt er sicher, dass jede Beteiligte Maßnahmen einleitet, sodass am Ende die Küche in einem ordentlichen Zustand bleibt.
```suggestion
Falls es Probleme bei einem der Schritte gibt, stellt er sicher, dass alle Beteiligten Maßnahmen einleiten, sodass am Ende die Küche in einem ordentlichen Zustand bleibt.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +## Fazit
```suggestion
# Fazit
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Jeder hat Vorteile und Nachteile, die bei jedem Anwendungsfall abzuwägen sind.
```suggestion
Jede hat Vorteile und Nachteile, die bei jedem Anwendungsfall abzuwägen sind.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Dabei Anzahl und Dauer der Arbeitsschritte, sowie der Bedarf an Status-tracking entscheidende Faktoren.
```suggestion
Bei der Auswahl sind die Anzahl und Dauer der Arbeitsschritte sowie der Bedarf an Status-Tracking entscheidende Faktoren.
```

2023-08-17 08:52 UTC, jo2 commented on _posts/2023-08-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Wenn du also das nächste Mal einen Kuchen backst oder versuchst, eine komplexe, verteilte Geschäftstransaktion in einer Microservice-Architektur abzuschließen, denkt an das Saga-Muster als Geheimzuta
```suggestion
Wenn du also das nächste Mal einen Kuchen backst oder versuchst, eine komplexe, verteilte Geschäftstransaktion in einer Microservicearchitektur abzuschließen, denk an das Saga-Muster als Geheimzutat für deinen Erfolg!
```

2023-08-20 13:20 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-08-23 09:24 UTC, eleazar-araujo commented
Danke für das Feedback @jo2 . Könntest du es bitte wieder reviewen?

2023-08-29 14:47 UTC, jo2 commented
@eleazar-araujo es sind noch einige Kommentare offen, sieh dir die bitte nochmal an.

2023-09-09 08:42 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-09 08:43 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-09 08:46 UTC, eleazar-araujo commented
Jetzt sollte alles erledigt sein. Vielen Dank @jo2

2023-09-13 12:03 UTC, jo2 requested changes
Ein paar Sachen sind noch drin, schau bitte nochmal drüber.

2023-09-13 12:03 UTC, jo2 commented on _posts/2023-09-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Wir haben uns das Saga-Muster und dessen Hauptmerkmale angeschaut.
```suggestion
Wir haben uns das Saga-Muster und dessen Hauptmerkmale kennengelernt.
```

2023-09-13 12:03 UTC, jo2 commented on _posts/2023-09-20-das-saga-muster-als-zutat-für-erfolgreiche-systeme.md
> +Ferner haben wir uns die Hauptarten von Sagas angeschaut: Choreografie und Orchestrierung.
```suggestion
Ferner haben wir uns mit den Hauptarten von Sagas beschäftigt: Choreografie und Orchestrierung.
```

2023-09-25 12:09 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-25 12:40 UTC, jo2 commented
Der Blogpost passt soweit. Möchtest du dein hier hinterlegtes Foto auch im offiziellen Blog verwenden? Führe bitte noch einen Rebase auf den adessoSE/devblog:master aus, danach kann dein Artikel veröffentlicht werden.

2023-09-25 12:41 UTC, jo2 submitted a review, later dismissed

2023-09-25 13:10 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-25 13:12 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-25 13:14 UTC, eleazar-araujo commented
Danke fürs Review @jo2. Mein hinterlegtes Foto würde ich gerne im offiziellen Blog verwenden. Es ist im assets/images/avatars/earaujo.png

2023-09-29 10:23 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-29 10:25 UTC, eleazar-araujo commented
Hallo @jo2 . Können wir das schon mergen?

2023-09-29 10:53 UTC, jo2 commented
@eleazar-araujo leider noch nicht, da das dein erster Blogbeitrag ist, bist du noch nicht als Autor im System hinterlegt. Ich hatte das am Mittwoch beauftragt, bisher aber noch keine Rückmeldung erhalten. Ich habe da jetzt nochmal nachgehakt.

2023-10-09 11:45 UTC, eleazar-araujo commented
Hallo @jo2 . Gibt es immer noch keine Rückmeldung?

2023-10-17 06:18 UTC, jo2 commented
Hier gibt es leider noch kein Update. Ich habe jetzt nochmal jemanden vom Redaktionsteam direkt angeschrieben, vielleicht gibt es da eher eine Antwort..

2023-10-17 11:03 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-10-17 11:04 UTC, merged