Blogbeitrag - API Spezifikationen mit OpenAPI Style Validator prüfen
adessoSE/devblog pull request #282
Opened 2023-08-18 14:49 UTC by claudioaltamura

Ich habe versehentlich den PR https://github.com/adessoSE/devblog/pull/276 geschlossen und die ursprünglichen Commits verloren!? Ich bin immer noch an einer Veröffentlichung interessiert. Das ist der zweite PR.

Es ist nun ein Beispiel mit Fehlermeldungen inklusive Beschreibung enthalten. Ebenso habe ich die Einrückung in den Code-Beispielen korrigiert. Damit habe ich alle offene und mir bekannten Kommentare erledigt.

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [x] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#dateiname-und-ablageort)
  - [x] [Autoreninfo gepflegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#autoren-informationen)
  - [x] [Metadaten gepflegt:](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#metadaten)
    - [x] "title" vergeben
    - [x] "author_ids" angegeben
    - [x] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [x] "tags" enthält (beliebige) passende Tags
  - [x] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [x] [Teaser entspricht den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#einleitung--teaser)
  - [x] Rechtschreibung korrigiert
  - [x] [Ein Satz pro Zeile](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#ein-satz-pro-zeile)
  - [x] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#bilder)
  - [x] [Überschriften entsprechen den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#%C3%9Cberschriften)
  - [x] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#syntax-highlighting) versehen
  - [x] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [x] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2023-08-29 15:02 UTC, jo2 requested changes
Ich habe nochmal über den Artikel gelesen und dir einige Kommentare dran geschrieben.

2023-08-29 15:02 UTC, jo2 commented on _posts/2023-06-23-api-spezifikationen-openapi-style-validator-pruefen.md
> +Jede Option kann als Parameter unter <configuration> als XML-Tag hinzugefügt werden. Stellen wir uns folgenden hypothetischen Fall vor. Wir haben eine kleine OpenAPI-Beschreibungen und möchte hier au
```suggestion
Jede Option kann als Parameter unter <configuration> als XML-Tag hinzugefügt werden. Stellen wir uns folgenden hypothetischen Fall vor. Wir haben eine kleine OpenAPI-Beschreibungen und möchten hier auf den Operation Tag verzichten. Dann können wir, wie in Listing 4 gezeigt, die Validierung mit der Option "validateOperationTag" und  "false" als Content ausschalten. Schließlich kann der Validator mit folgendem Befehl ausgeführt werden:
```

2023-09-01 16:46 UTC, claudioaltamura commented on _posts/2023-06-23-api-spezifikationen-openapi-style-validator-pruefen.md
> +Beim Info-Object wird der Titel und die Beschreibung vernachlässigt, Kontakt- oder Lizenzinformationen fehlen meistens komplett.
Vielen Dank für den Hinweis. Ich habe mich für die deutsche Schreibweise entschieden, siehe commit 2c7d5bf.

2023-09-01 16:47 UTC, claudioaltamura commented on _posts/2023-06-23-api-spezifikationen-openapi-style-validator-pruefen.md
> +Für Maven kann ein Plug-in konfiguriert werden:
Ich habe mich für die deutsche Schreibweise entschieden, siehe commit 296566b.

2023-09-01 16:58 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-05 13:12 UTC, jo2 submitted a review, later dismissed

2023-09-06 14:02 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-06 14:03 UTC, jo2 approved these changes

2023-09-06 14:03 UTC, merged