Blogbeitrag: Open Platform Communication
adessoSE/devblog pull request #284
Opened 2023-09-08 21:12 UTC by c0c0bird

Wenn du einen Pull-Request stellst, teile uns bitte deine Änderungen mit, indem du die unten angegebene Publish-Checkliste nutzt. 

# Publish Checkliste

- **Meta** (abzuhaken durch den Autor)
  - [ ] [Artikeldatei am richtigen Ort abgelegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#dateiname-und-ablageort)
  - [ ] [Autoreninfo gepflegt](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#autoren-informationen)
  - [ ] [Metadaten gepflegt:](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#metadaten)
    - [ ] "title" vergeben
    - [ ] "author_ids" angegeben
    - [ ] "categories" enthält maximal eine der Hauptkategorien (Architektur, Branchen, Digital Experience, Inside adesso, KI, Methodik, Softwareentwicklung)
    - [ ] "tags" enthält (beliebige) passende Tags
  - [ ] Der blogpost-checker hat die Richtigkeit der Metadaten bestätigt (siehe CI Check)
- **Text** (abzuhaken durch den Autor)
  - [ ] [Teaser entspricht den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#einleitung--teaser)
  - [ ] Rechtschreibung korrigiert
  - [ ] [Ein Satz pro Zeile](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#ein-satz-pro-zeile)
  - [ ] [Bilder sind korrekt in den Artikel eingebunden](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#bilder)
  - [ ] [Überschriften entsprechen den Vorgaben](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#%C3%9Cberschriften)
  - [ ] Code-Snippets wurden mit [Syntax Highlighting](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#syntax-highlighting) versehen
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
- **Review** (abzuhaken durch den Reviewer)
  - [ ] Rechtschreibung korrigiert
  - [ ] Der Artikel wurde in der [Vorschau](https://github.com/adessoSE/devblog/blob/master/examples/2021-08-23-blog-post-guide.md#online-preview) geprüft
  - [ ] Auf gendergerechte Formulierungen wurde geachtet
  - [ ] Der Autor ist bei CCO hinterlegt
  - [ ] CCO wurde über neuen Artikel informiert
  - [ ] Date-Angaben 
    - [ ] stimmen im Header und im Dateinamen überein
    - [ ] stehen auf dem heutigen Tag (aber in der Vergangenheit)

2023-09-08 21:12 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-08 21:15 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-13 12:40 UTC, jo2 requested changes
Der Artikel ist ziemlich interessant, ein paar Kleinigkeiten sind aber noch drin. Ich der leider keine Ahnung vom Thema hat, weiß allerdings nichts mit DCOM und OPC Classic anzufangen. Kannst du da einleitend noch drauf eingehen?

2023-09-13 12:40 UTC, jo2 commented on _posts/2023-09-08-open-platform-communication.md
> +Für den stabilen Netzbetrieb ist es außerdem wichtig, die aktuelle Einspeiseleistung genau zu kennen und gegebenenfalls herunter regeln zu können.
```suggestion
Für den stabilen Netzbetrieb ist es außerdem wichtig, die aktuelle Einspeiseleistung genau zu kennen und gegebenenfalls herunterregeln zu können.
```

2023-09-13 12:40 UTC, jo2 commented on _posts/2023-09-08-open-platform-communication.md
> +Bei der Steuersoftware für Maschinen, die über Jahrzehnte in der Produktion oder in Kraftwerken genutzt werden, ist kaum mit tiefgreifenden Updates zu rechnen.
```suggestion
Bei der Steuersoftware für Maschinen, die über Jahrzehnte in der Produktion oder in Kraftwerken genutzt wird, ist kaum mit tiefgreifenden Updates zu rechnen.
```

2023-09-13 12:40 UTC, jo2 commented on _posts/2023-09-08-open-platform-communication.md
> +Andere Geräte sind systemkritisch, so dass sie nicht für ein riskantes Upgrade mehrerer Software-Komponenten abgeschaltet werden sollen.
```suggestion
Andere Geräte sind systemkritisch, sodass sie nicht für ein riskantes Upgrade mehrerer Softwarekomponenten abgeschaltet werden sollen.
```

2023-09-13 14:44 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-13 14:44 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-13 14:44 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-13 14:44 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-13 18:31 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-13 18:33 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-13 18:49 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-13 18:52 UTC, c0c0bird commented
Wie glücklich muss man sein ohne COM ... okay, ich habe den Abschnitt "Geschichte" aufgeblasen. Der schaurige Albtraum aller Windows-Devs wird jetzt erklärt, inkluksive ein paar mahnender Worte, bitte schnell davon loszukommen. :)

2023-09-20 07:09 UTC, jo2 requested changes
Danke für den Geschichtsexkurs, wenn ich das so lese, bin ich froh, da drum rum gekommen zu sein. Eine Kleinigkeit ist noch drin. Kannst du außerdem einen Rebase auf den aktuellen adessoSE/devblog:master durchführen? Danach kann der Blogpost dann veröffentlicht werden.

2023-09-20 07:09 UTC, jo2 commented on _posts/2023-09-08-open-platform-communication.md
> +Dazu kommt, dass Windows in hardware-nahen Systemen an Relevanz verloren hat.
```suggestion
Dazu kommt, dass Windows in hardwarenahen Systemen an Relevanz verloren hat.
```

2023-09-20 07:28 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-20 07:28 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-20 07:29 UTC, c0c0bird commented
Alle Vorschläge commited, Rebase erledigt. :)

2023-09-25 12:32 UTC, jo2 approved these changes

2023-09-25 12:33 UTC, jekyll2cms commented
Blogpost seems formally correct and ready for review!

2023-09-25 12:35 UTC, merged